### ISSUE TITLE
[Kali2016.1] Impossible to select an interface 

### ISSUE THREAD

**Issue by kcdtv** [v1s1t0r1sh3r3/airgeddon#1]
Hi there!
I tried your script and i am stuck just after launching it.
I have a single wifi interface, i tried your script letting it in manged mode and putting it in monitor mode.
`************************************Welcome*************************************
Welcome to airgeddon script v2.02

This script is only for educational purposes. Be good boyz&girlz

Supported distros for this script: Kali and Wifislax
Detecting distro...

Kali Linux distro detected. Script can continue...

Press [Enter] key to continue...
                      (...)
******************************Interface selection*******************************
Select an interface to work with :

wlan0

Invalid interface was chosen

Press [Enter] key to continue...
                        (...)
******************************Interface selection*******************************
Select an interface to work with :

wlan0mon

Invalid interface was chosen

Press [Enter] key to continue...
  (...)
`
I tried to enter wlan0 or wlan0mon but did not get anything 
and i can see some error in coding, like you put somewhere "airmon-ng stop mon0"
mode monitor interface should be now wlanXmon and even if you use an outdated distribution that still have old airmon-ng  it doesn't have to be mon0... if your interface is wlan1 it will be mon1 (and now it should be wlan1mon) .. 
take care

**Comment by v1s1t0r1sh3r3** [comment]
Hi. Thank you for trying to use. Not sure what are you doing exactly. Maybe typing the card's name? You must enter the number assigned by menu, so 1 and press enter for example.

I tested it very well in Kali and I'm pretty sure is working. The script even manage the name change while putting in monitor mode.

Which version of Kali are you using?

**Comment by v1s1t0r1sh3r3** [comment]
Sorry, I see now the version you use in the title. I usually use Kali 2.0. Now I'm downloading Kali 2016.1 to test.

**Comment by v1s1t0r1sh3r3** [comment]
Thanks for your feedback. The problem was because in Kali 2016.1 the output of the ifconfig command is a quite different. I changed the interface detection method to be compatible with both versions.

Now is solved in version 2.03.
