### ISSUE TITLE
wpaclean

### ISSUE THREAD

**Issue by soxrok2212** [v1s1t0r1sh3r3/airgeddon#105]
#### What is your airgeddon version?

Null

#### What is your Linux O.S. and which version?

Null
#### Which is the chipset of your wireless card?

Null
#### Describe the issue and the steps to reproduce it

Please remove wpaclean support. It is known to corrupt capture files and can not be used when converting to hccapx for use with hashcat. There is no benefit to even leaving it as an option because it is very, very broken. Capture files either need to be manually cleaned for optimal performance, or just run through cap2hccapx (granted multiple handshakes will result in HUGE speed decreases).

**Comment by v1s1t0r1sh3r3** [comment]
You are pretty wrong.

You can do wpaclean over a handshake file and then convert it to hccapx flawlessly. I already tested it right now and the file was cracking without any problem using hashcat and a dictionary on this new format.

That option only makes sense if the capture file is a very large file. This only is happening if you leave the capture window for a long time. It is useful to clean even files captured out of airgeddon.

As the hints said: `Cleaning a Handshake file is recommended only for big size files. It's better to have a backup, sometimes file can be corrupted while cleaning it`

If you don't like the option, just don't use it. It's useful for others. For me is useful.
