### ISSUE TITLE
DHCP Error Kali Linux is using udhcpd not dhcpd

### ISSUE THREAD

**Issue by darkmatter1505** [v1s1t0r1sh3r3/airgeddon#114]
#### What is your airgeddon version?

8.0

#### What is your Linux O.S. and which version?

Kali 2018.1

#### Which is the chipset of your wireless card?

Intel Corporation Centrino Ultimate-N 6300

#### Describe the issue and the steps to reproduce it

Run the script I get an error for DHCPD, Kali is using udhcpd instead of dhcpd. How do I get airgeddon to use udhcpd since I want to be able to use the feature that require DHCPD.

**Comment by v1s1t0r1sh3r3** [comment]
dhcpd is the name of the missing command. The package name needed is shown on "possible package names". On Kali the needed package to install is isc-dhcp-server. It provides to you the needed dhcpd command. So uninstall what you installed and install isc-dhcp-server package.

Maybe one day we could implement to auto install missing packages.
