### ISSUE TITLE
[enhancement] save captured credentials on text file

### ISSUE THREAD

**Issue by Giova84** [v1s1t0r1sh3r3/airgeddon#115]
I'm running the latest available version of airgeddon on Kali Linux. 

After that credentials has been captured (eg wps pin and then wpa password by using before reaver with pixiewps and then by cracking the pin to get the wpa password), these credentials are just displayed inside an xterm window: at least here I am not able to copy and paste the credentials from such xterm window; in facts, airgeddon suggest me:
>After stopping the attack (using [Ctrl+C]), the window will not be closed automatically. So **you'll have time to write down the password** if successful. You'll have to close it manually

I see, however, that such credentials are present in the /tmp/ag.wpsout.txt text file.
Well, by using shell's utilities, like eg awk and grep, we could be able to grab these infos and write them in another text file, like eg, fluxion already does.

Imho would be a great/nice feature of airgeddon.

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, is something I have in mind since time ago. We can check it for future versions. I'll let this open as a reminder. Thank you for your suggestion.

**Comment by Giova84** [comment]
Maybe by adding another option in the menu, something like "do you wanna see only wep target"?
However I noticed that airgeddon remebers the latest chosen target: when I launch a wps attack, I select a target: when I exit from the attack, I want to perform another attack on another target, but airgeddon relies on the latest target which I choosed, and will performs again the attach on such target: maybe would be also nice to add another option, (maybe displayed only if there is a previously choosed  target) which asks if such target should be deleted; this could be achieved by saving the target in a temp text variable (eg: if last_target.txt contains some data, the option will be displayed; if the text file is empty, the option will not be displayed: bash scripts are able to make a lot of useful things :-)

**Comment by v1s1t0r1sh3r3** [comment]
This was added. It will be available on next v8.10 version (different than 8.01 which is incoming). You can check it on 8.10 specific branch. Closing.

**Comment by Saff2Maharjan** [comment]
How to delete saved session of pixie dust attack  and other attack of airgeddon in kali linux?Thanks in advance for any solution you can provide.

**Comment by OscarAkaElvis** [comment]
Not sure if you are referring to bully, or reaver... lack of data to answer you accurately... to put a comment in another issue (a closed one) is not the way.

Anyway, I can tell you that you can delete the existing sessions for bully deleting the `.bully` dir which is existing at your $HOME dir. And for reaver deleting the wpc files at `/usr/local/var/lib/reaver/`.

For further discussion join to our Discord channel please. Invitation link: https://discord.gg/sQ9dgt9
