### ISSUE TITLE
[enhancement] when do wep attack, airgeddon should only reports wep targets

### ISSUE THREAD

**Issue by Giova84** [v1s1t0r1sh3r3/airgeddon#116]
While "Explore for targets (wep)" is started, the xterm window also shows wpa targets, but here I expect to only see wep targets; nowadays, wep targets - at least where I live - are few: so, in the "Explore for targets"  window I see a lot of wpa targets, which make difficult focus to wep targets. Should be enough to run airodump-ng  with the  `--encrypt wep` flag, to filter out only wep targets.

**Comment by v1s1t0r1sh3r3** [comment]
This was discussed time ago. The point is that a selected target can be used in other parts of the script too. So it's not filtered intentionally. Anyway, before launching a WEP attack, everything is validated.

The same behavior is happening when selecting a WPA/WPA2 for handshake capture... everything is shown.

Anyway, the changes to do this are very simple. We'll see what other users think about this.

**Comment by Giova84** [comment]
Maybe by adding another option in the menu, something like "do you wanna see only wep target"?
However I noticed that airgeddon remebers the latest chosen target: when I launch a wps attack, I select a target: when I exit from the attack, I want to perform another attack on another target, but airgeddon relies on the latest target which I choosed, and will performs again the attach on such target: maybe would be also nice to add another option, (maybe displayed only if there is a previously choosed  target) which asks if such target should be deleted; this could be achieved by saving the target in a temp text variable (eg: if last_target.txt contains some data, the option will be displayed; if the text file is empty, the option will not be displayed: bash scripts are able to make a lot of useful things :-)

**Comment by v1s1t0r1sh3r3** [comment]
Really? I think I know it 🙄 

That's because "normal" target vars are shared over all menues excepting the wps menu. It has its own target vars. But this is not the point of this thread and I think is not important enough to open one for it.

Anyway, I already started development about this (filters on scannings).

**Comment by Giova84** [comment]
Yeah, I obviously knew that you know it :-) Was just to say "ok, I am aware of this", don't you worry :-)
Many thanks for your development :+1:

**Comment by v1s1t0r1sh3r3** [comment]
Done... this is already pushed on dev branch. It will be available on next 8.01 version and you can already test it downloading/clonning that branch. Closing...

You never saw faster development 🥇 😸  Contribute with a star on the project ⭐️
