### ISSUE TITLE
Error with hashcat 

### ISSUE THREAD

**Issue by MatheusViGo** [v1s1t0r1sh3r3/airgeddon#117]
Airgeddon 8.0 with kali linux rolling updated, with all dependencies, when i updated to newest hashcat package 4.1.0, the error appear:

"hashcat: unrecognized option '--weak-hash-threshold'
Invalid argument specified."
![captura de tela de 2018-02-26 18-51-39](https://user-images.githubusercontent.com/17281717/36697650-762f8694-1b26-11e8-8100-471b745392e6.png)

probably some function deprecated with this new version

**Comment by OscarAkaElvis** [comment]
Thank you for your report. I updated Kali to the max and the version is 4.0.1 not 4.1.0. Anyway, I guess the problem will be present from the version with the change and higher versions.... but we don't know exactly what version is that. I've been checking hashcat changelogs and there is nothing about removing weak-hash-threshold. There is something "similar" on 4.0.0 changelog: `Removed option --weak-hash-check (zero-length password check) to increase startup time, it also causes many Trap 6 error on macOS`

We need to know from which version is that option disappeared. Can somebody check this? Thank you.

**Comment by OscarAkaElvis** [comment]
Confirmed, this argument disappeared on v4.0.0 . I tested it and it's still present on 3.6.0 but it is not on 4.0.0.

We will check this for future versions.

**Comment by OscarAkaElvis** [comment]
Done, this will be fixed on next 8.01 version. It can be checked now on dev branch. Closing.

**Comment by MatheusViGo** [comment]
Ok, thanks !
