### ISSUE TITLE
(Question) Does this script work with 5 ghz network ?

### ISSUE THREAD

**Issue by cegi** [v1s1t0r1sh3r3/airgeddon#118]
I have a wireless adapter that support injection and monitor on 5 ghz network, but some tools (wifite) work only on 2 ghz. Does Airgeddon support 5 ghz ? Thanks

**Comment by OscarAkaElvis** [comment]
Yes, as you can see in the project tags, "5ghz" is supported since v8.0. You can see it also in "features" section at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Features

Closing.
