### ISSUE TITLE
/opt/airgeddon/airgeddon.sh: line 8393: /tmp/nws-01.csv: No such file or directory

### ISSUE THREAD

**Issue by geexmmo** [v1s1t0r1sh3r3/airgeddon#120]
#### What is your airgeddon version?
Docker version 18.03.0-ce, build 0520e2430
v1s1t0r1sh3r3/airgeddon:beta
v1s1t0r1sh3r3/airgeddon:latest

#### What is your Linux O.S. and which version?
Archlinux latest

#### Which is the chipset of your wireless card?
Intel Corporation Centrino Advanced-N 6205 [Taylor Peak] (rev 34)

#### Describe the issue and the steps to reproduce it
Error "/**opt/airgeddon/airgeddon.sh: line 8393: /tmp/nws-01.csv: No such file or directory**" shows up when i choosing option 4 ("4.  Explore for targets (monitor mode needed").

'ls' command on docker filesystem show that there may be some problems with 2 files in /tmp directory

echo $DISPLAY inside container shows my display,  ':0'

airgeddon execution: 
https://pastebin.com/AYK3iTy7

some docker fs-layer commands:
https://pastebin.com/H07tSmsj

**Comment by v1s1t0r1sh3r3** [comment]
At first sight, it sounds to me like airodump (scanning) window can't be opened because it can't connect to your X window system.

Three questions:

1. Regarding your version. Docker tag image is beta or is latest? You put both and that is not possible.

2. Do you have a running X window system on your Arch?

3. Can you put the complete "docker run" command you used?

**Comment by geexmmo** [comment]
Downloaded docker images: 
```
└─▪  docker image ls
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
v1s1t0r1sh3r3/airgeddon   beta                4a650154fd51        39 hours ago        2.23GB
v1s1t0r1sh3r3/airgeddon   latest              fa17eaa8ebc5        4 weeks ago         2.23GB
```

My 'docker run' command: 
```
docker run --rm \
           -ti \
           --net=host \
           --privileged \
           -v /home/geexmmo/airgeddon-files:/io \
           -p 3000:3000 \
           -e DISPLAY=$(env | grep DISPLAY | awk -F "=" '{print $2}') \
           v1s1t0r1sh3r3/airgeddon:beta
```
I am switching the last line to _v1s1t0r1sh3r3/airgeddon:latest_ or _beta_ to see if it works in one of those version.


Xorg status:
```
UID        PID  PPID  C STIME TTY          TIME CMD
root      2073   442  1 12:47 tty7     00:00:18 /usr/lib/xorg-server/Xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
```

**Comment by v1s1t0r1sh3r3** [comment]
Everything seems normal. And what is the output of your `env | grep DISPLAY | awk -F "=" '{print $2}'` command? As I can see on your Xorg status it should be":0". Can you confirm is your output at that command?

**Comment by geexmmo** [comment]
On host system output is:
```
┌─[geexmmo][heavyboi][~]
└─▪  env | grep DISPLAY | awk -F "=" '{print $2}'
:0
```

On docker container it's the same: 
```
root@heavyboi:/opt# env | grep DISPLAY | awk -F "=" '{print $2}'
:0
```

**Comment by geexmmo** [comment]
Getting closer to problem. It seems that it is some default xorg or docker configuration that permits container to host connection.
I run 'xhost +' on host machine to allow every connection and modified docker run script to use unix socket connection to Xorg:
```
docker run --rm \
           -ti \
           --net=host \
           --privileged \
           -v /home/geexmmo/airgeddon-files:/io \
           -v /tmp/.X11-unix:/tmp/.X11-unix \
           -p 3000:3000 \
           -e DISPLAY=unix$DISPLAY \
           v1s1t0r1sh3r3/airgeddon:beta
```

xterm now pops up without any problems except my xorg opened to network by 'xhost +', thanks

**Comment by v1s1t0r1sh3r3** [comment]
Great news. Closing.

**Comment by dkgitdev** [comment]
Can you please add this to the FAQ section for linux, cuz we're having it on debian 9 stable?

**Comment by v1s1t0r1sh3r3** [comment]
It is already documented. Read the Docker wiki section under "Display problems (resolution detection)". Please read before post. Thanks.

**Comment by AbhishekBhatP** [comment]
While I select for exploring target in airgeddon it throws below error. And Terminal which display's targets pops up goes.

Error:
./airgeddon.sh: line 11118: /tmp/nws-01.csv: No such file or directory

**Comment by OscarAkaElvis** [comment]
It seems airgeddon cant connect to your x server. Try before launching airgeddon: xhost +
