### ISSUE TITLE
Language string: command not found

### ISSUE THREAD

**Issue by OZeros** [v1s1t0r1sh3r3/airgeddon#122]
#### What is your airgeddon version?
8.01

#### What is your Linux O.S. and which version?
Linux Kali Rolling 2018

#### Which is the chipset of your wireless card?
RTL8723BE

#### Describe the issue and the steps to reproduce it

Today. script was checking for update and found one. when he downloaded it. something went wrong like he can't find **language string command not found** 

this screenshot the issue:
![screenshot from 2018-03-31 15-41-55](https://user-images.githubusercontent.com/5164489/38163268-178a85f6-34fa-11e8-8a58-ddae44f83c89.png)

**Comment by v1s1t0r1sh3r3** [comment]
I tested the new version and is working fine. I tested the updated and is working fine. It sounds like the file was download corruptly. Donwload it again and try. Tell to us the result.

**Comment by OZeros** [comment]
yes it was corrupted. when i re-download it it work thanks for your time :+1:
