### ISSUE TITLE
Makefile 

### ISSUE THREAD

**Issue by necrose99** [v1s1t0r1sh3r3/airgeddon#124]
https://raw.githubusercontent.com/necrose99/airgeddon/master/build/Makefile.txt
Its a Touch Fugglly   however  emake install should hopefully work with a new ebuild ...  @ v8.01.tar.gz
or "9999 version"  (git-r3.eclass Gentoo, git clone,  do emake (Makefile) install or if 9999 else @ stable release , also makes for quick and dirty testing with Gentoo/ @Pentoo  using a live ebuild/9999 
else I have to make a very Uggly Ebuild to Do more of the same work... 

and ideal should be anyone could make RPM, or Distro packing via makefile 
I also dumped the shell launcher out from Arch "Binary"   for symlinking via airgeddon-launch.sh /usr/bin/airgeddon   @ ./Build dir.. 

I can pull if you like ,  however for now the makefile is untested.  I can test latter in vm , main install is down on laptop /dev/sdb time for new HDD ... 

also https://stackoverflow.com/questions/2221562/using-gettext-in-bash  might be useful for **CI** 
as you can upload a pot to transifex or others like hosted.weblate.org  , can likely do some basic Japanese / にほんご or a few others..  and as pot files get translated less of a mess on upkeep on the script file.. 

However I can Add that to the pull.

**Comment by v1s1t0r1sh3r3** [comment]
Hello, not sure what is this for... can you explain a couple of things?

What is the propose of the issue? I mean, the target, the goal... not sure to understand. Is to create some kind of package? compatible with what?

I thought pentoo was discontinued. Can you put a link to the project?

If you want to add airgeddon to that distro, there is no problem for sure! but I think that if a build script is needed, that script must be on that distro repository, not in airgeddon repo. In the same way BlackArch or ArchStrike for example are doing it...

**Comment by necrose99** [comment]
https://github.com/pentoo/pentoo-overlay  , Gentoo Dev Zerochaos still runs it.  and blshvk, etc..
zero needs someone badly to keep pentoo.ch page updated.... but he himself is rather functional/utilitarian... cares more about working pentoo iso's etc... 
https://github.com/gentoo 
https://github.com/sakaki-/gentoo-on-rpi3-64bit if you want embed testing...  or easy pentesting device...  rock64-4-gigs... :-) 

1) generic Linux/Unix makefile for everyone.. atm WIP...  basicly a generic makefile ... still needs a bit of work... i surmise.. 

2) I can make Ebuild using ARCH bin , however its frowned on by Gentoo Devs.  SRC's are preferred... for qa... 

3) I can make ebuild script to do all the packaging , however , by giving a good makefile , was hoping to **make it braindead easy for anyone from any distro...  a win for all**  Distro  packagers invoking makefile would save many quite a lot of hell..   weather bsd rpm packager's etc.. 
 _**--a suggestion for Makefile for ease of install , no matter the platform...**_ 

3b) else i can make an ebuild but it wont be as clean or pretty...   (however src_Install {emake install....} also a win for me also )  over all as it would make just bumping the ebuild file and sig/hash of tarball. 

4) else necromancy-overlay , I have a number of ebuilds to hammer out before seeing if pentoo wants them.    routersploit not one of my prettiest ebuilds  by far... fuggly but works...  however blshkv cleaned up just a tad... 

5 dev branch sure I'll try to pop the Japanese translations their then.  as well as others. 

6) **I'm a touch Dyslexic** (so was Einstein)  , so it would be wise to get feedback on formention makefile just so I don't fubar something   and before pulling it , 2nd pair of eyeballs....  

7) pot file on transifex.com etc would be a plus , as mentioned in stackex... plus to your dev-branch translationed can be added via CI...CI/auto push  and also easier to use pot file's for translation... for the future....

**Comment by v1s1t0r1sh3r3** [comment]
Ok lets do it in this way...

1. Do a fork of the project of dev branch instead of master.

2. Finish the makefile.

3. Send me an email to explain how it works, which commands are needed to run/build it, which platforms are compatible.

4. If all the tests are ok, then we can do a pull request to "dev" branch.

Thanks. Closing.
