### ISSUE TITLE
Evil Twin captive portal; missing content

### ISSUE THREAD

**Issue by Mason10198** [v1s1t0r1sh3r3/airgeddon#130]
#### What is your airgeddon version?

v8.01

#### What is your Linux O.S. and which version?

Parrot Security 3.11

#### Which is the chipset of your wireless card?

Ralink RT5372

#### Describe the issue and the steps to reproduce it

When using an Evil Twin attack, everything seems to work properly, except that the captive portal does not appear to have any contents other than "Wireless network, ESSID:"
<img width="903" alt="screen shot 2018-05-01 at 4 11 17 pm" src="https://user-images.githubusercontent.com/31994327/39494327-9680e8cc-4d5b-11e8-8715-434d274f9f7f.png">

**Comment by v1s1t0r1sh3r3** [comment]
Which is the client on which did you saw the error? I think based on "captive.apple.com" appearing on your screenshot that is an Apple device... maybe an Iphone. I need more data. What is your iOS version? what browser are you using? Safari?

Can you perform more tests?

1. Are you able to reproduce it? I mean... we must be sure that it's not a punctual error.

2. It would be nice to create the Evil Twin and check at the same time from different devices: Iphone, Android, pc.... What I want to know is that if it's not working on an Iphone and it's working fine at the same time for other device... maybe it's related to the html, css and js used by the portal...

**Comment by Mason10198** [comment]
I'm Parrot as guest in VirtualBox, host is an Apple MacBook Pro (15-inch, 2017). My default browser is Chrome (Version 65.0.3325.181), but I believe that the login portal pop-ups on macOS are always just small Safari windows, no matter what browser you use.

I have reproduced this issue every time I have tried an Evil Twin. I have tried both an RT5372 and a RTL8812AU, and I have also tried attacking different AP's (home network, mobile device hotspot, etc).

**Comment by v1s1t0r1sh3r3** [comment]
Maybe is the opposite, right? The host is the machine creating the fake AP. So the host is Parrot. And the client (the victim) is the OSX.... I understand that the OSX is accesing to the captive portal using Chrome, is this right?

It's important to understand everything that is happening to be able to reproduce it. Can you paste the files of the captive portal? I'll explain... when the captive portal is set, airgeddon create the files at `/tmp/www/` , that files are `index.htm`, `portal.css` and `portal.js` . Maybe you can paste here the content of the files (try to format it to be clear). As I said, you can check the files while the portal is up. Thanks!

**Comment by OscarAkaElvis** [comment]
Closing due lack of info.
