### ISSUE TITLE
Small Issue setting monitor mode to my interface

### ISSUE THREAD

**Issue by inclinedlizard** [v1s1t0r1sh3r3/airgeddon#131]
#### What is your airgeddon version?
v8.01

#### What is your Linux O.S. and which version?

Kali Linux 2018.1 on VirtualBox using Macbook Pro 2012

#### Which is the chipset of your wireless card?

Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter

#### Describe the issue and the steps to reproduce it
I execute the file airgeddon loads up smoothly, I choose my interface (wlan0 in Managed Mode) 
When I want to put my interface into Monitor mode I get, "This interface does not support Monitor mode." Which doesn't make sense because I am able to set monitor mode manually via 
Ifconfig wlan0 down
iwconfig wlan0 mode monitor
ifconfig wlan0 up
Bam I'm in monitor mode.

Could this be my device that's not supported with airgeddon or its some just driver issue. 
Please let me know, Thank you

**Comment by v1s1t0r1sh3r3** [comment]
Sorry for the moment only cards compatible with airmon-ng are supported. Maybe in the future.... That's a very well known problem.

**Comment by OscarAkaElvis** [comment]
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer
