### ISSUE TITLE
Alfa awus1900

### ISSUE THREAD

**Issue by g0rbe** [v1s1t0r1sh3r3/airgeddon#133]
#### What is your airgeddon version? 

v8.01

#### What is your Linux O.S. and which version? 

ParrotSec

#### Which is the chipset of your wireless card?

RTL8814AU

#### Describe the issue and the steps to reproduce it

Airgeddon doesn't support Alfa awus1900 wifi dongle.
Can't put in monitor mode and cant start evil twin attacks.
The card use [THIS](https://github.com/aircrack-ng/rtl8812au) driver.
When i put the card in monitor mode before airgeddon, it is recognise the monitor mode.
At exit, i always choose to set back to managed mode, airgeddon said that set was successfull, but when i check the card with `iwfconfig` it is still in monitor mode.

![image](https://user-images.githubusercontent.com/36860942/39837574-2f052a1e-53d7-11e8-92b3-76aba49fce4a.png)
 When start evil twin, it said : `no such device` in most of terminals.

**Comment by OscarAkaElvis** [comment]
Yeah, that's because your card is not compatible with airmon. Sorry but airgeddon is compatible only with airmon compatible cards. Maybe one day could face this to try to open the compatibility, sorry.

**Comment by kimocoder** [comment]
aircrack-ng has added support for this driver now (rtl8812au)

**Comment by v1s1t0r1sh3r3** [comment]
Really? Good news.

**Comment by Dema323** [comment]
@g0rbe whats the status on your awus 1900 and drivers ? Having some issues myself with the awus1900

**Comment by SubaashNair** [comment]
@Dema323 I'm having the same issue with awus1900 driver. 
![Screenshot from 2019-06-01 22-03-26](https://user-images.githubusercontent.com/26023333/58749457-17863b80-84b9-11e9-85c9-95afab0591be.png)

**Comment by Dema323** [comment]
Buy another card.

**Comment by OscarAkaElvis** [comment]
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer
