### ISSUE TITLE
headless raspberry pi 3 + only ssh connection (tmux)

### ISSUE THREAD

**Issue by Mr-P3rry** [v1s1t0r1sh3r3/airgeddon#134]
#### What is your airgeddon version?

I'm running airgeddon script v8.01

#### What is your Linux O.S. and which version?

I'm using raspbian Linux 4.14.34-v7+ armv7l 

#### Which is the chipset of your wireless card?

Alfa Network AWUS036ACH with chipset rtl8812au running monitor mode

#### Describe the issue and the steps to reproduce it

Essential tools: checking...
ifconfig .... Ok
iwconfig .... Ok
iw .... Ok
awk .... Ok
airmon-ng .... Ok
airodump-ng .... Ok
aircrack-ng .... Ok
xterm .... Ok

Optional tools: checking...
iptables .... Ok
wpaclean .... Ok
packetforge-ng .... Ok
bully .... Ok
sslstrip .... Ok
aireplay-ng .... Ok
beef .... Error (Possible package name : beef-xss / beef-project)
unbuffer .... Ok
dhcpd .... Ok
lighttpd .... Ok
wash .... Ok
crunch .... Ok
etterlog .... Ok
dnsspoof .... Ok
ettercap .... Ok
hashcat .... Error (Possible package name : hashcat)
reaver .... Ok
mdk3 .... Ok
bettercap .... Error (Possible package name : bettercap)
pixiewps .... Ok
hostapd .... Ok

Update tools: checking...
curl .... Ok

I was wondering if you could integrate maybe something like tmux rather than X Window system in order to explore for targets without getting this error 

./airgeddon.sh: line 7117: /tmp/nws-01.csv: No such file or directory
No networks found

**Comment by v1s1t0r1sh3r3** [comment]
This was reopened. We are already working on this on "headless_tmux" branch. It will be released on v9.20

**Comment by OscarAkaElvis** [comment]
This was already released (at last!!!) on v9.20. Available now at master branch. Closing.

**Comment by zeluu** [comment]
Hi,
are there any dependencies needed to run this?
I have RPi4 with:
Manjaro kernel 4.19.97
airgeddon 10.01
tmux 3.0_a-1
and I use this RPi as headless devide. I simply make ssh to it and work without GUI.
When I run airgeddon and use "Explore for targets" I don't get any error, I see that it works as I see used resources in htop however I don't see any output, no new tmux pane open or anything in tmux interface.
I'm wondering if I've been missing something.

**Comment by OscarAkaElvis** [comment]
Next time open your own issue, or better, join discord channel to discuss there.

https://discord.gg/sQ9dgt9

Anyway, I must say that nothing is needed. Just launch airgeddon as normal after modifying the options file as explained in Wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

Then you can move through the tmux windows (no panes) as normal.

Locking.
