### ISSUE TITLE
Support for new bettercap version 

### ISSUE THREAD

**Issue by lolxnn** [v1s1t0r1sh3r3/airgeddon#135]
Bettercap is very useful for injecting beef hook.js in Evil Twin mode, but the new version in the kali repo has been syncronized with the new version that has been completly rewrited. Will the support for the new bettercap be reimplemented?

**Comment by v1s1t0r1sh3r3** [comment]
I'm checking new 2.x version... it seems the changes are so heavy. It hasn't a `-v` parameter to check version as other older versions used to have... it works in a very different way. It will be very hard to integrate. So, at this moment what I'm going to do is trying to detect it and if the version is the new (2x.s) I'll show a controllated error saying it's not compatible. Will see in the future if it's possible to integrate.

Thanks for the report. I'll let this open until the commit for this.

**Comment by v1s1t0r1sh3r3** [comment]
Done. Until see what to do with bettercap now at least there is a controlled error for the new 2.x unsupported version. This change will be available on airgeddon v8.10. Closing.
