### ISSUE TITLE
Evil twin captive portal attack bug

### ISSUE THREAD

**Issue by Bhagyesh19** [v1s1t0r1sh3r3/airgeddon#143]
#### What is your airgeddon version?

8.01

#### What is your Linux O.S. and which version?

kali linux

#### Which is the chipset of your wireless card?

TP-Link TL-WN722N 150Mbps Wireless USB Adapter

#### Describe the issue and the steps to reproduce it
I have tried evil twin captive portal attack on my own wifi to test but it shows wrong password attempts even after i entered right password in captive portal page which is "@d[\/]!n1992_1998" but it shows wrong attempt as "@d[\]!n1992_1998" in that control windows on top-right side of image. It's not reading forward slash "/". 

![capture_li](https://user-images.githubusercontent.com/33200521/40672993-0b4563ca-638e-11e8-9d50-4ef8ce1879e8.jpg)

**Comment by OscarAkaElvis** [comment]
I created a plugin exactly for this: https://github.com/OscarAkaElvis/airgeddon-plugins
