### ISSUE TITLE
Airgeddon doesnt detect my wifi adapter

### ISSUE THREAD

**Issue by AegrumPraesul** [v1s1t0r1sh3r3/airgeddon#145]
#### What is your airgeddon version?

Airgeddon v8.01

#### What is your Linux O.S. and which version?

Ubuntu 18.02

#### Which is the chipset of your wireless card?

rtl8723be

#### Describe the issue and the steps to reproduce it

Hi, I recently installed Airgeddon as a way to make usage of Reaver and Bully easier, however whenever I try to select the interface to work with, all it shows is my ethernet adapter and not my wifi adapter. I tried looking for answers but it seems like I'm a special case as I cant find anyone else with the same issue. I do launch Airgeddon with the bash command as is said to do in the tutorial.

Checklist Airgeddon
![image](https://user-images.githubusercontent.com/40279899/41441278-36589482-7032-11e8-9b74-55f0e1272a56.png)

Interface selection
![image](https://user-images.githubusercontent.com/40279899/41441292-49ac64be-7032-11e8-852e-632d138ed2ab.png)

Ifconfig output
![image](https://user-images.githubusercontent.com/40279899/41441339-7bbd3488-7032-11e8-8268-5f3136c6dbef.png)

**Comment by v1s1t0r1sh3r3** [comment]
ifconfig doesn't show wireless adapters. The command to show them is `iwconfig`, so this image shows nothing interesting.

Is your Ubuntu a virtual machine? because internal wireless cards on virtual machines are shown as ethernet cards. If that is your case you should use an external usb wireless card or use Linux as native.

**Comment by OscarAkaElvis** [comment]
If is a Windows subsystem that is not supported. As is documented in the wiki at compatibility section: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility
