### ISSUE TITLE
Unable to put Edimax EW-7822ULC into monitor mode using airgeddon.sh

### ISSUE THREAD

**Issue by codeNameMahi** [v1s1t0r1sh3r3/airgeddon#151]
#### What is your airgeddon version?

v8.10

#### What is your Linux O.S. and which version?

Re4son-v7+ 4.9.80

#### Which is the chipset of your wireless card?

Realtek (https://wikidevi.com/wiki/Edimax_EW-7822ULC)

#### Describe the issue and the steps to reproduce it

The issue is that when I try using the airgeddon.sh to put my wifi adaptor into monitor mode, it changes the interface name to "95" with mode "(Non wifi card)". When I attempt to  explore for targets I get the error message that "This interface 95 is not in monitor mode".

I am able to manually put the interface into monitor mode using iwconfig:

`sudo iwconfig wlan1 mode monitor`

**Comment by OscarAkaElvis** [comment]
It seems your card is not compatible with airmon. Check the documentation at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility

Maybe compatibility beyond airmon could be added in the future.

**Comment by OscarAkaElvis** [comment]
This finally was developed. Is going to be released on v8.11. Since this version, any card which is able to support monitor mode can be used, not only airmon compatible cards.
