### ISSUE TITLE
After playing with airgeddon, "Connection failed" popups keep appearing

### ISSUE THREAD

**Issue by Aaronik** [v1s1t0r1sh3r3/airgeddon#153]
#### What is your airgeddon version?

v8.10

#### What is your Linux O.S. and which version?

Ubuntu 18.04 running gnome shell 3.28.1

#### Which is the chipset of your wireless card?

Intel Corporation

#### Describe the issue and the steps to reproduce it

I played with airgeddon (using docker -- `sudo docker run --rm -it -e DISPLAY=unix:0 --net=host --privileged -p 3000:3000 v1s1t0r1sh3r3/airgeddon`) for about an hour, trying various things and enjoying its beauty. But now, even after I restart my system, I am faced with this error message popping up around once or twice a minute "Connection failed - Activation of network connection failed". Note it's more of a cosmetic annoyance because my internet is working just fine! Also, this may be of note or may not, I was also using a usb plug-in `Atheros Communications, Inc. AR9271 802.11n` wifi card for some of my playing.

I've tried reading through the code to find what may have done this, but it is a lot of code, heh, and I'm afraid it's going to take me forever to figure it out. I have to say though the code is really beautifully clean, well done!

Hoping you can help :) Let me know of any other information that I can supply.

![image](https://user-images.githubusercontent.com/1324601/42199171-cdd7dc24-7e41-11e8-99a8-c9341a91b319.png)

**Comment by OscarAkaElvis** [comment]
It may depend. Depend of your "playing". Probably you launched an Evil Twin attack. On that attack you'll see that when launched on a docker container there is a problem with the hostapd. It seems there is some kind of incompatibility with network-manager. Read this note: 

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker%20Linux#hostapd-possible-conflict-with-host-network-manager

Probably your network-manager is the problem. You can restart it to avoid problems once airgeddon is closed.

**Comment by Aaronik** [comment]
No, like I said, this maintains even after a system restart, although you are right in that I did play with an Evil Twin attack, among other things!

**Comment by Aaronik** [comment]
You know what - I was messing around with my settings trying to figure this out and noticed that the _bluetooth_ was switching on and then off right before this message appeared. I fiddled with it a bit just in the GUI settings menu and the error message has disappeared! I didn't realize any of this worked on Bluetooth... or does it? May be fairly system dependent, I dunno.

**Comment by v1s1t0r1sh3r3** [comment]
I don't know man... bluetooth shouldn't interfere here. Closing.
