### ISSUE TITLE
Evil Twin AP - Web Page Doesn't Load Correctly - Webserver Syntax Error

### ISSUE THREAD

**Issue by stormtrooper298** [v1s1t0r1sh3r3/airgeddon#154]
What is your Airgeddon version?
v8.10

What is your Linux O.S. and which version?
Debian 9 with KDE Plasma

Which is the chipset of your wireless card?
Alfa AWUS036NH Ralink3070 

Describe the issue and the steps to reproduce it

Launch Airgeddon, as you normally would. 

Select interface to the wireless card mentioned above.
Set interface into monitor mode.
Select Evil Twin attacks menu.
Select Evil Twin AP attach with captive portal.
Scan for and select target(s).
Select either Deauth / disassoc amok mdk3 attack or Death aireplay attack. (didn't make a difference)
Select No to DoS pursuit mode.
Select Yes, or No, for the internet access method. (didn't make a difference)
Select No to spoofing MAC address.
Select already captured, and verified, handshake file.
Confirm location for writing the potential password to.
Select English for the captive portal menu language. 

Allow a client to connect to your Evil Twin AP and open a browser.
The following is displayed and there is NO option to type in any password. It doesn't appear to render, even when viewing it from the source machine.

Screenshots below:

Webserver XTERM window from source machine - Syntax Errors:
![webserver syntaxerror](https://user-images.githubusercontent.com/23707132/42543094-cec0d792-846f-11e8-83e9-35c11f47f831.png)

Viewing from the source machine:
![indexhtm notloading](https://user-images.githubusercontent.com/23707132/42543105-edf8e2da-846f-11e8-8dde-001f67f322b4.png)

Android client view:
![client android eviltwin](https://user-images.githubusercontent.com/23707132/42543162-2d047aa2-8470-11e8-99b5-127a042006be.png)

Windows 7 Firefox view:
![client windows7firefox eviltwin](https://user-images.githubusercontent.com/23707132/42543197-4e6144dc-8470-11e8-832c-07463897b1bd.png)

Unless the webserver syntax errors are expected, my initial thought is that this is the source of the issue, or it at least lies in that direction.. :)

I'm willing to see this through to the end, so whatever we need to figure this out, let me know!

**Comment by stormtrooper298** [comment]
For kicks, I selected a different language, but the issue persists (as expected).

**Comment by stormtrooper298** [comment]
@OscarAkaElvis 

Hey, thanks for getting back to me! It is truly appreciated.

Sure, I can get a copy of those files from /tmp/www and post them here as well to be reviewed. 

I plan to get a VM running of Kali here shortly, so I will test on other distros as well.

**Comment by stormtrooper298** [comment]
[www.zip](https://github.com/v1s1t0r1sh3r3/airgeddon/files/2185943/www.zip)

Here are the files taken from /tmp/www/ during the issue.

**Comment by OscarAkaElvis** [comment]
This is very very strange... I reproduced it on Debian.... but the code seems ok. Maybe is some encoding problem or some change introduced on Debian... quite strange.

I need to investigate furter on this 🤔

**Comment by OscarAkaElvis** [comment]
What?? I tested again on Debian 9 and it's fully working.... my bad. Yesterday night maybe I was too tired. To be hones in my test I didn't checked the web page.... just looked for the code of the generated html files. Now I checked better and everything is fine!!!! This is the code of the generated index.htm:

```
#!/usr/bin/env bash
echo '<!DOCTYPE html>'
echo '<html>'
echo -e '	<head>'
echo -e '		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>'
echo -e '		<title>Portal de Internet</title>'
echo -e '		<link rel="stylesheet" type="text/css" href="portal.css"/>'
echo -e '		<script type="text/javascript" src="portal.js"></script>'
echo -e '	</head>'
echo -e '	<body>'
echo -e '		<div class="content">'
echo -e '			<form method="post" id="loginform" name="loginform" action="check.htm">'
echo -e '				<div class="title">'
echo -e '					<p>Red inalámbrica, ESSID:</p>'
echo -e '					<span class="bold">gmv_mob</span>'
echo -e '				</div>'
echo -e '				<p>Introduzca su contraseña de acceso a la red inalámbrica para poder acceder a internet</p>'
echo -e '				<label>'
echo -e '					<input id="password" type="password" name="password" maxlength="63" size="20" placeholder="Contraseña"/><br/>'
echo -e '				</label>'
echo -e '				<p>Mostrar contraseña <input type="checkbox" id="showpass"/></p>'
echo -e '				<input class="button" id="formbutton" type="button" value="Enviar"/>'
echo -e '			</form>'
echo -e '		</div>'
echo -e '	</body>'
echo '</html>'
exit 0
```

And it is ok... the page is displayed correctly!

So I did another test... I created the Evil twin and with the portal up, I replaced the index.htm file with the file you sent me and it doesn't work. The file seems the same, but something that can be seen is happening.

Anyway, it is working on Debian 9 and it is something related to your O.S. and it is not a problem of airgeddon. I'll close the issue but anyway you still can posting here to see if we can help you.

**Comment by OscarAkaElvis** [comment]
Ohhh I found your problem!!! it is related to the SSID of your network. It contains a single quote `Mac's Playground` and that single quote is breaking everything. I'll check if I can do something to escape it on the page.

**Comment by OscarAkaElvis** [comment]
I re-opened it to perform a fix on this.

**Comment by OscarAkaElvis** [comment]
Fixed. Closing! you can test it if you want downloading it from dev branch `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon.git`

Thanks and sorry for the inconvenience.

**Comment by stormtrooper298** [comment]
@OscarAkaElvis 

Dude, you're the sh*t! 

No no, thank you!!

I never would have thought that would have broken it....
