### ISSUE TITLE
Evil Twin AP Only Works Once Per Launch - Must Restart Airgeddon Each Time

### ISSUE THREAD

**Issue by stormtrooper298** [v1s1t0r1sh3r3/airgeddon#155]
What is your Airgeddon version?
v8.10

What is your Linux O.S. and which version?
Debian 9 with KDE Plasma

Which is the chipset of your wireless card?
Alfa AWUS036NH Ralink3070 

Describe the issue and the steps to reproduce it

Airgeddon's Evil Twin AP attach only seems to work once per launch. If I run Evil Twin AP, disable it, then come back to run the Evil Twin AP again, I receive errors with hostapd and it fails to launch properly. Consistently, if I restart Airgeddon, it works like a charm! So at least there's that work around.

Launch Airgeddon, as you normally would. 
Select interface to the wireless card mentioned above.
Set interface into monitor mode.
Select Evil Twin attacks menu.
Select Evil Twin AP attach with captive portal.
Scan for and select target(s).
Select either Deauth / disassoc amok mdk3 attack or Death aireplay attack. (didn't make a difference)
Select No to DoS pursuit mode.
Select Yes, or No, for the internet access method. (didn't make a difference)
Select No to spoofing MAC address.
Select already captured, and verified, handshake file.
Confirm location for writing the potential password to.
Select English for the captive portal menu language. 

When launching this, it appears the first window with hostapd throw an error.

When pressing enter to stop the Evil Twin AP, Airgeddon tells me that I do not have an interface selected.
An interface was definitely selected and Airgeddon confirmed this before lauching the attack, with the info at the top.
It shows: "Interface wlan0mon selected. Mode: Monitor. Supported bands: 2.4Ghz"

Screenshots Below:

![eviltwin wontlaunch hostapd](https://user-images.githubusercontent.com/23707132/42543680-888be4e4-8472-11e8-9ce6-65ed86e4d6ef.png)

**Comment by OscarAkaElvis** [comment]
I think this is related to your network manager. It's not an airgeddon issue. Closing.

**Comment by OscarAkaElvis** [comment]
I re-tested this and confirmed. It is something related to network manager.

If you launch this command between Evil twin attacks it will work!: `service network-manager restart`
