### ISSUE TITLE
Won't run on chromebook linux

### ISSUE THREAD

**Issue by Guardian3490** [v1s1t0r1sh3r3/airgeddon#158]
#### What is your airgeddon version?

8.10-1

#### What is your Linux O.S. and which version?

Ubuntu 16.04

#### Which is the chipset of your wireless card?

0

#### Describe the issue and the steps to reproduce it
I don't understand why it states dpkg: error processing archive airgeddon_x.x-x_all.deb (--install): cannot access archive: No such file or directory 
Errors were encountered while processing: 
airgeddon_x.x-x_all.deb
I did everything it said to do and it still came out this way.

**Comment by v1s1t0r1sh3r3** [comment]
Closing due lack of feedback.
