### ISSUE TITLE
airgeddon cannot connect to fake ap

### ISSUE THREAD

**Issue by joj97** [v1s1t0r1sh3r3/airgeddon#159]
I tried airgeddon evil twin attack(captive portal) with one Ralink 3070 wireless adapter recently. My problem is that there is no option to key in the password to the fake AP. It showing wireless essid but no place to key in the password. Please help me. Thank you

**Comment by v1s1t0r1sh3r3** [comment]
Closing due lack of detail. No screenshots, no data. The issue template wasn't filled up with the versions.

**Comment by FirstLast1010** [comment]
I also cannot connect to my fake ap.
It's saying 'Failed to set beacons' can anyone help me!
I am using airgeddon on Kali Linux with a Wifi Adapter that works for Monitor mode, AP mode, and Packet injection
Please help me!!!

**Comment by xpz3** [comment]
Join airgeddon discord and discuss your issue there. Commenting on an old issue won't help..
https://discord.gg/sQ9dgt9

**Comment by FirstLast1010** [comment]
Thank you for your concern
