### ISSUE TITLE
using airgeddon from headless kali client via ssh possible?

### ISSUE THREAD

**Issue by n1ete** [v1s1t0r1sh3r3/airgeddon#160]
#### What is your airgeddon version?
latest
#### What is your Linux O.S. and which version?
Kali Linux rolling

Thanks for one of the best Wifi-Pen Scripts so far!
probably an easy to answer question:
Is it possible to run the airgeddon script from an headless machine via ssh?

thanks for the support and help

greetz

**Comment by OscarAkaElvis** [comment]
No man, it is not possible at the moment. xterm with a running X window system is need to work with airgeddon. At least for now...
