### ISSUE TITLE
There is a problem with the selected interface

### ISSUE THREAD

**Issue by dnakruemel** [v1s1t0r1sh3r3/airgeddon#163]
hey, this will probably sound pretty noobish since i am a noob honestly, after a day of trial an error im finally here that the interface works for casual login into a AP...

#### What is your airgeddon version?
probably up to date, automatic update check finds nothing (downloaded a week ago from this repo)

#### What is your Linux O.S. and which version?
Manjaro Linux \r  (\n) (\l)

4.14.60-1-MANJARO

Accepted bash version (4.4.23(1)-release). Minimum required version: 4.2 

#### Which is the chipset of your wireless card?
Ralink Technology, Corp. MT7610U ("Archer T2U" 2.4G+5G WLAN Adapter

ra0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state DORMANT mode DORMANT group default qlen 1000

#### Describe the issue and the steps to reproduce it

.starting the script, waiting to get to the interface section

Select an interface to work with: 
--------- 
1.  enp3s0  // Chipset: Broadcom Limited NetXtreme BCM5764M
2.  wlp2s0 // 2.4Ghz, 5Ghz // Chipset: Broadcom Limited BCM4322 802.11a/b/g/n
3.  ra0 // 2.4Ghz // Chipset: Ralink Technology, Corp. MT7610U
4.  enp0s4f1u1  // Chipset: Samsung Electronics Co., Ltd GT-I9500
--------- 

aand there the journey ends 
(int 2. isnt capable of monitor mode, thats why i ordered the Archer)

thanks for the awsum script anyways!
im just getting started and have loads to learn but i hope ill get there :)

**Comment by dnakruemel** [comment]
update: why so ever it can no be selected, but if i try to put it in monitor mode:

Putting your interface in monitor mode... 

The interface changed its name while putting in monitor mode. Autoselected 

> 
> Monitor mode now is set on  
> Press [Enter] key to continue...
> 
> No interface selected. You'll be redirected to select one 

then the menu loads, i choose the int again and its back (did it even change?) to managed mode

**Comment by v1s1t0r1sh3r3** [comment]
You are not telling your airgeddon version. If you downloaded it some weeks ago I must guess that you downloaded it from the master branch, so your version is 8.10 . Anyway, the version is shown the first once the script is launched or can be shown on the `about & credits` section.

Why to ask the version? is very important. Until version 8.10, airgeddon is compatible only to airmon compatible cards. I mean, if you are not able to set up it on monitor mode using airmon (even out of airgeddon), your card is not going to work with airgeddon. You can test it out of airgeddon using the command `airmon-ng start <yourcardname>` and then you can check its mode using `iwconfig` command.

The version 8.11 is under development and is available on dev branch. On this version all the cards that support monitor mode can be used with airgeddon, even if they are not compatible to airmon.

So you can do different things:
1. Download airgeddon v8.11 from dev branch and test it.
2. Try to put in monitor mode your card out of airgeddon using airmon.

P.S. I don't want to sound rude, but, do you really think you can use this script? is not complicated but a minimum of knowledge is needed. At least you should be able to identify your version.

**Comment by v1s1t0r1sh3r3** [comment]
Closing due lack of information
