### ISSUE TITLE
Some error

### ISSUE THREAD

**Issue by iacsvrn** [v1s1t0r1sh3r3/airgeddon#166]
#### What is your airgeddon version?

The last version ( 8.11 )

#### What is your Linux O.S. and which version?

Kali Linux 2018.2

#### Which is the chipset of your wireless card?

Atheros

#### Describe the issue and the steps to reproduce it

WPS Atack --> Pixie Dust Atack --> ESSID, which contains symbol ` ( i.e. te`st ) I get error: 

/tmp/ag.wpsattack.sh: line 56: syntax error near unexpected token '}'
/tmp/ag.wpsattack.sh: line 56: '}'

**Comment by v1s1t0r1sh3r3** [comment]
I finally understood what you want to say and I was able to reproduce the problem. It was the backquote char present on SSID which was breaking the WPS attacks. This is solved in v8.12.

**Comment by EngrSalauddin** [comment]
I am facing error when using bully pixie dust attack on airgeddon
Right now i am using kali latest version 2019.2 & airgrdden version (airgeddon script v9.20)
Wlan Qualcomm Atheros AR9287.
Error Message

testing pixie dust attack 
cant't find package Expect
while executing
"packagr require Expect"
(file "/usr/bin/unbuffer" line 6)
Close the window

Waiting for your feedback sir. Thanks for the great tools.
Regards

**Comment by EngrSalauddin** [comment]
![Screenshot from 2019-07-23 10-25-54](https://user-images.githubusercontent.com/31707788/61682772-cf56fd00-ad34-11e9-9d80-960b0468d8ab.png)
![Screenshot from 2019-07-23 10-24-34](https://user-images.githubusercontent.com/31707788/61682774-cfef9380-ad34-11e9-85f6-5d80a21bdc7d.png)
![Screenshot from 2019-07-23 10-24-05](https://user-images.githubusercontent.com/31707788/61682775-cfef9380-ad34-11e9-8f76-37819e44a018.png)
![Screenshot from 2019-07-23 10-23-52](https://user-images.githubusercontent.com/31707788/61682776-d0882a00-ad34-11e9-9ba9-7ba041889444.png)
![Screenshot from 2019-07-23 10-23-42](https://user-images.githubusercontent.com/31707788/61682778-d0882a00-ad34-11e9-9a14-83b678d0278c.png)
![Screenshot from 2019-07-23 10-23-26](https://user-images.githubusercontent.com/31707788/61682779-d120c080-ad34-11e9-81ca-e35f82ef6072.png)
![Screenshot from 2019-07-23 10-23-12](https://user-images.githubusercontent.com/31707788/61682780-d120c080-ad34-11e9-8bff-8a5a5879e5f0.png)
![Screenshot from 2019-07-23 10-22-54](https://user-images.githubusercontent.com/31707788/61682781-d120c080-ad34-11e9-80b2-2112c4219a11.png)
![Screenshot from 2019-07-23 10-22-24](https://user-images.githubusercontent.com/31707788/61682782-d1b95700-ad34-11e9-86eb-28e114d88510.png)
![Screenshot from 2019-07-23 10-21-42](https://user-images.githubusercontent.com/31707788/61682783-d1b95700-ad34-11e9-80dc-3803693cd392.png)

**Comment by EngrSalauddin** [comment]
I am facing error when using bully pixie dust attack on airgeddon
Right now i am using kali latest version 2019.2 & airgrdden version (airgeddon script v9.20)
Wlan Qualcomm Atheros AR9287.
Error Message

testing pixie dust attack
cant't find package Expect
while executing
"packagr require Expect"
(file "/usr/bin/unbuffer" line 6)
Close the window

Waiting for your feedback sir. Thanks for the great tools.
Regards
![Screenshot from 2019-07-23 10-25-54](https://user-images.githubusercontent.com/31707788/61682985-a97e2800-ad35-11e9-857f-688466547a1b.png)
![Screenshot from 2019-07-23 10-24-34](https://user-images.githubusercontent.com/31707788/61682986-a97e2800-ad35-11e9-86ec-13cfd0feb8f3.png)
![Screenshot from 2019-07-23 10-24-05](https://user-images.githubusercontent.com/31707788/61682987-aa16be80-ad35-11e9-85bd-b39d394855c0.png)
![Screenshot from 2019-07-23 10-23-12](https://user-images.githubusercontent.com/31707788/61682988-aa16be80-ad35-11e9-8fe6-ca2c4d4cb282.png)
![Screenshot from 2019-07-23 10-22-54](https://user-images.githubusercontent.com/31707788/61682989-aaaf5500-ad35-11e9-9c57-3c43b6057c17.png)
![Screenshot from 2019-07-23 10-22-24](https://user-images.githubusercontent.com/31707788/61682990-aaaf5500-ad35-11e9-9478-c1a8f62b859b.png)
![Screenshot from 2019-07-23 10-21-42](https://user-images.githubusercontent.com/31707788/61682991-ab47eb80-ad35-11e9-9488-ea8a6db0eebb.png)

**Comment by EngrSalauddin** [comment]
Hi There,

I am facing error when using bully pixie dust attack on airgeddon
Right now i am using kali latest version 2019.2 & airgrdden version (airgeddon script v9.20)
Wlan Qualcomm Atheros AR9287.
Error Message

testing pixie dust attack
cant't find package Expect
while executing
"packagr require Expect"
(file "/usr/bin/unbuffer" line 6)
Close the window

Waiting for your feedback sir. Thanks for the great tools.
Regards
![Screenshot from 2019-07-23 10-39-45](https://user-images.githubusercontent.com/31707788/61683137-40e37b00-ad36-11e9-8378-6d49cc8fea76.png)
![Screenshot from 2019-07-23 10-25-54](https://user-images.githubusercontent.com/31707788/61683138-40e37b00-ad36-11e9-88ea-ebae8b14965a.png)
![Screenshot from 2019-07-23 10-24-34](https://user-images.githubusercontent.com/31707788/61683140-40e37b00-ad36-11e9-8ffa-8502a727ca07.png)
![Screenshot from 2019-07-23 10-23-12](https://user-images.githubusercontent.com/31707788/61683141-417c1180-ad36-11e9-98cc-c8bef011d7a2.png)
![Screenshot from 2019-07-23 10-22-54](https://user-images.githubusercontent.com/31707788/61683143-417c1180-ad36-11e9-9fae-09def3187c9c.png)
![Screenshot from 2019-07-23 10-22-24](https://user-images.githubusercontent.com/31707788/61683144-4214a800-ad36-11e9-8509-3b584de0abe4.png)
![Screenshot from 2019-07-23 10-21-42](https://user-images.githubusercontent.com/31707788/61683146-4214a800-ad36-11e9-88bb-5b35c6387b01.png)

**Comment by OscarAkaElvis** [comment]
What about initial dependencies checks? after the last screenshot you sent
me, airgeddon checks for all the tools. If you are missing some of them
like unbuffer command in your case, you should see something like
"unbuffer" ... Error (possible package name: expect).

So you need to install expect package:

apt install expect

Anyway, is weird... if you don't have unbuffer command because you are
missing expect package, the attack should appear in red at menu and it is
supossed that you can't launch it. Delete airgeddon and perform the git
clone again to test.

--
Oscar

OpenPGP Key: DA9C60E9 ||
https://pgp.mit.edu/pks/lookup?op=get&search=0x79B17260DA9C60E9
4F74 B302 354D 817D DE38 0A43 79B1 7260 DA9C 60E9
--

**Comment by OscarAkaElvis** [comment]
Anyway, this is not the way to ask stuff.... using an old issue which is talking about other different stuff. If you have more questions open your own issue. Locking.
