### ISSUE TITLE
Syntex Error

### ISSUE THREAD

**Issue by amzker** [v1s1t0r1sh3r3/airgeddon#169]
When I Run Script ( bash script )
It Say Unexpected Syntex Error "(" 

I Provided Full Info

**Comment by v1s1t0r1sh3r3** [comment]
Closing due lack of information. You must fill the issue template saying your versions, steps to reproduce, command used, etc. Follow the instructions on the wiki to launch airgeddon: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Installation%20&%20Usage
