### ISSUE TITLE
Airgeddon interface Selection didn't shows /.airgeddon.sh : line 2083: ip: command not found

### ISSUE THREAD

**Issue by shobri01** [v1s1t0r1sh3r3/airgeddon#170]
How to fix this problem? what must i select interface if the interface didn't shows.

iam Using Android 7.1.1 Nougat
Termux with Ubuntu

**** Here the Transcript :

Accepted bash version (4.4.19(1)-release). Minimum required version: 4.2

Root permissions successfully detected

Detecting resolution... Can't be detected!, using standard: 1024x768

If the xpdyinfo command works, the script will be able to calculate your screen resolution and display the windows in a better way. Depending of the system, the package name containing it could be x11-utils, xdpyinfo, xorg-xdpyinfo, etc.

Known compatible distros with this script:
"Arch" "Backbox" "BlackArch" "CentOS" "Cyborg" "Debian" "Fedora" "Gentoo" "Kali" "Kali arm" "OpenMandriva" "Parrot" "Parrot arm" "Raspbian" "Red Hat" "SuSE" "Ubuntu" "Wifislax"

Detecting system...
Arch Linux

Let's check if you have installed what script needs
Press [Enter] key to continue...

Essential tools: checking...
ifconfig .... Ok
iwconfig .... Ok
iw .... Ok
awk .... Ok
airmon-ng .... Ok
airodump-ng .... Ok
aircrack-ng .... Ok
xterm .... Ok

Optional tools: checking...
packetforge-ng .... Ok
dhcpd .... Ok
wash .... Ok
etterlog .... Ok
dnsspoof .... Ok
reaver .... Ok
hostapd .... Ok
iptables .... Ok
wpaclean .... Ok
bully .... Error (Possible package name : bully)
sslstrip .... Ok
aireplay-ng .... Ok
beef .... Error (Possible package name : beef-xss / beef-project)
unbuffer .... Ok
lighttpd .... Ok
crunch .... Ok
ettercap .... Ok
hashcat .... Error (Possible package name : hashcat)
mdk3 .... Ok
bettercap .... Error (Possible package name : bettercap)
pixiewps .... Ok

Update tools: checking...
curl .... Ok

[Press Enter]

***************************** Interface selection ******************************
Select an interface to work with:
---------                                        airgeddon.sh: line 2083: ip: command not found
---------
*Hint* Every time you see a text with the prefix [PoT] acronym for "Pending of Translation", means the translation has been automatically generated and is still pending of review
---------

**Comment by xtonousou** [comment]
Hello @shobri01,

I'm sorry that you couldn't run `airgeddon` on your Android device. Unfortunately `airgeddon` does not support this system, at least for now.

Personally I'm using `Termux`, it provides identical commands with native Linux operating systems, but they are different and inadequate.

Thank you for providing that info.
