### ISSUE TITLE
Network Scan Option Not Showing My Home Network 

### ISSUE THREAD

**Issue by mimran79** [v1s1t0r1sh3r3/airgeddon#172]
I have recently installed Airgeddon couple of days ago from Github. I have Kali 2018.03 64 bit installed on my PC and using ALFA AWUS36ACH WiFi Adapter. 

I am running into a small problem. While running Airgeddon and selecting Option 8 for WPS Attack, when I select Option 4 to scan all networks around me ,I see all network but do not see my Home Network (router) . Where as when I run airodump-ng, I can see my home network.

Any idea what I am doing wrong? or what should I do? 

Thank you for your suggestions.

**Comment by OscarAkaElvis** [comment]
Probably because you don't have WPS enabled on your router. Wash (the tool used for wps scanning) on airgeddon is configured to detect only APs with WPS enabled. Closing.

**Comment by mimran79** [comment]
Thank you for replying, I enabled the WPS Option on my AP and then re-run airgeddon but still I do not see my home network when I select the option 4 to scan network in WPS atttack. Any other guess?

**Comment by v1s1t0r1sh3r3** [comment]
Maybe your access point is configured in a high 5ghz channel and your card used to scan is 2.4ghz. Locking.
