### ISSUE TITLE
Airgeddon>Twin Evil not deauth connection

### ISSUE THREAD

**Issue by Axors** [v1s1t0r1sh3r3/airgeddon#173]
#### What is your airgeddon version?

8.11

#### What is your Linux O.S. and which version?

Kali Linux 2018.1

#### Which is the chipset of your wireless ?

Intel Corporation Centrino

#### Describe the issue and the steps to reproduce it

When i have Evil Twin AP attack with captive portal,  all work fine, but my deauth not work.. i not have any errors , all 3 options i check,
 1. deauth/disassoc amok mdk3 attack
 2. Deauth aireplay attack
 3. WIDS WIPS WDS Confusion atrack

When i run all, work, but I have still my connection and not disconnect. 
When i open new terminal, and when i make deauth aireplay-ng , my dhcp going down and open fake network disappears.
What must i make ? What i wrong make?

**Comment by v1s1t0r1sh3r3** [comment]
Sorry but we can't do anything here. There is no 100% working method. The DoS part is different for all attacks. It depends of a lot of factors. Not every DoS attack affect to all Access Points. Even on the same Access Point some clients could be affected and other clients not. The attack efectiveness may vary also depending of your chipset. So all what we can say is keep trying looking for a working combination on your scenario. Good luck!
