### ISSUE TITLE
Evil Twin with Captive Portal isn't saving correct passwords

### ISSUE THREAD

**Issue by zombillano** [v1s1t0r1sh3r3/airgeddon#174]
#### What is your airgeddon version?

Airgeddon v8.11

#### What is your Linux O.S. and which version?

Kali 2018.3

#### Which is the chipset of your wireless card?

I tried with bcm4331, RT2070, RTL8187, AR9271

#### Describe the issue and the steps to reproduce it

Evil Twin with Captive Portal isn't saving correct passwords. Open Airgeddon, set up your wireless card (select it, put it into monitor mode, etc, etc), select evil twin attack with any DoS method and select Captive Portal without internet connection. Do as usual, prove with both the correct password and some incorrect passwords then open the txt file generated by airgeddon. It'll fill just fine the incorrect ones, but keep a blank space on the correct one (even when one of the prompted windows shows the correct pass)

**Comment by zombillano** [comment]
I guess I found what breaks airgeddon. I'm ussing a ESSID with and space in its name. My network is called "Panther Network" and when I change it for "PantherNetwork" it works just fine

**Comment by OscarAkaElvis** [comment]
Hi, I did some tests... I was able to reproduce the problem. Yeah, you are right... ESSID containing spaces is causing error writing the password on the file as it is shown on this screenshot:

![error](https://user-images.githubusercontent.com/5803348/46109427-dc709180-c1e0-11e8-92a1-cfc7251615bf.png)


I fixed it. It was just a missing quotes on a path. Now it works as you can see on this other screenshot:

![good](https://user-images.githubusercontent.com/5803348/46109465-032ec800-c1e1-11e8-92a7-9527ab0ddd4a.png)

This fix will be available on next v8.12. Thanks for the report. Regards.

**Comment by zombillano** [comment]
Awesome man! Thanks for taking your time into fixing this little bug

Have a nice day!
