### ISSUE TITLE
Airgeddon not working on Raspbian Stretch with two different adapters/drivers: 8192cu and mt7610u_sta

### ISSUE THREAD

**Issue by gntook** [v1s1t0r1sh3r3/airgeddon#175]
Airgeddon Version: 8.11

OS: Raspian Stretch (testing) -- upgraded just yesterday to have Ruby 2.3 needed for beef (i.e. for full use of airgeddon).
uname -a
Linux device 4.14.70-v7+ #1144 SMP Tue Sep 18 17:34:46 BST 2018 armv7l GNU/Linux

Chipsets and issues follow.

    Airgeddon tried with wifi adapters individually and together.

lsusb
    shows,
wlan0:    0bda:8178 Realtek Semiconductor Corp. RTL8192CU 802.11n WLAN Adapter - driver 8192cu
ra0:     148f:761a Ralink Technology, Corp. - driver mt7610u_sta

lsmod |grep 8192
    gives (with both plugged in),
8192cu                589824  0
cfg80211              573440  3 8192cu,mt7610u_sta,brcmfmac

wlan1:
iwlist
    shows for phy0
    Supported interface modes:
         * IBSS
         * managed
         * AP
         * monitor
         * P2P-client
         * P2P-GO
    software interface modes (can always be added):
         * monitor
iwconfig wlan1 mode Monitor
    Error for wireless request "Set Mode" (8B06) :
iw phy phy0 interface add mon0 type monitor
ifconfig mon0 up
    airmaggedon shows mon0
    Main Menu --> WPS attacks --> Explore for targets yields "No networks found."
    11. (bully) Known PINs...
    Manually entering bssid of target, channel, and otherwise using defaults,
    Three times, bully gives the same error:
[!] ioctl (SIOCSIWFREQ) on 'mon0' failed with -1
[X] unable to set channel on 'mon0', exiting

ra0:
 iwlist
    shows for phy0
   Supported interface modes:
         * IBSS
         * managed
         * monitor
    software interface modes (can always be added):
	[nothing here]
iw phy phy1 interface add mon1 type monitor
    command failed: Operation not supported (-95)
iwconfig ra0 mode Monitor
iwconfig ra0
ra0       Ralink STA  ESSID:""  Nickname:"MT7610U_STA"
          Mode:Monitor  Frequency=2.412 GHz  Access Point: Not-Associated

    Whether ra0 is in Auto or Monitor Mode, airgeddon gives me
"There is a problem with selected interface. Redirecting you to script exit."

Any guidance or suggestings would be welcome.

**Comment by gntook** [comment]
1. I had done so already, hence the "individually" of "Airgeddon tried with wifi adapters individually and together."


2. With one installed at a time, I used airmon-ng on each and saw the following.
airmon-ng start wlan1 11
PHY	Interface	Driver		Chipset
phy0	wlan0		brcmfmac	Broadcom 43430
phy5	wlan1		rtl8192cu	Realtek Semiconductor Corp. RTL8192CU 802.11n WLAN Adapter
cat: /sys/class/ieee80211/phy5/device/net/wlan1mon/type: No such file or directory
Newly created monitor mode interface wlan1mon is *NOT* in monitor mode.
Removing non-monitor wlan1mon interface...
WARNING: unable to start monitor mode, please run "airmon-ng check kill"

airmon-ng start ra0 11
PHY	Interface	Driver		Chipset
Warn ON: USB
phy4	ra0		??????		Ralink Technology, Corp. 
ERROR adding monitor mode interface: command failed: Operation not supported (-95)

N.B. wlan0 is rpi's internal wifi adapter.

3. Done already (without the ;s) as I indicated with,
iwconfig wlan1 mode Monitor
Error for wireless request "Set Mode" (8B06) :
    and
iwconfig ra0 mode Monitor
iwconfig ra0
ra0 Ralink STA ESSID:"" Nickname:"MT7610U_STA"
Mode:Monitor Frequency=2.412 GHz Access Point: Not-Associated


Repeated just now for thoroughness.
ifconfig wlan1 down; iwconfig wlan1 mode monitor ; ifconfig wlan1 up
Error for wireless request "Set Mode" (8B06) :
    SET failed on device wlan1 ; Invalid argument.

ifconfig ra0 down; iwconfig ra0 mode monitor ; ifconfig ra0 up
Error for wireless request "Set Mode" (8B06) :
    SET failed on device ra0 ; Network is down.

Furthermore,
ifconfig ra0 up; iwconfig ra0 mode monitor ; iwconfig ra0 |head -n 2
ra0       Ralink STA  ESSID:""  Nickname:"MT7610U_STA"
          Mode:Monitor  Frequency=2.412 GHz  Access Point: Not-Associated

4. I do not see how to so. Help please.
I would gladly review further hardware, but I do not know what I am doing.
I have already tried close to a dozen different adapters (not kidding) to find both compatability and performance on the rpi.
Clearly, I could use some assistance here.
I am shooting in the dark.

5.  N/A


The script terminates when I select ra0, just prior to (or just at the start of) the initial loading of the main menu.
Select an interface to work with
1. eth0 // Standard Microsystems. Corp. SMSC9512/9514
2. wlan0 // Unknown.
3. ra0 // Chipset: Ralink Technology, Corp.
3<After typing the preceding digit, I pressed enter, and a new, mostly blank screen appeared.>
*************************************airgeddon main menu************************************
"There is a problem with selected interface. Redirecting you to script exit"
Press [enter] key to continue...

**Comment by gntook** [comment]
What do these details, from my original post, tell you?

wlan1:
iwlist
shows for phy0
Supported interface modes:
* IBSS
* managed
* AP
* monitor
* P2P-client
* P2P-GO
software interface modes (can always be added):
* monitor

ra0:
iwlist
shows for phy0
Supported interface modes:
* IBSS
* managed
* monitor
software interface modes (can always be added):
[nothing here]

**Comment by v1s1t0r1sh3r3** [comment]
Hi, I see that your wlan1 device is not able to be in monitor mode, neither using airmon nor using the other way. Maybe iwlist is showing to you that it supports monitor mode, and maybe it could be true, but I can't tell you anything about this. Try another driver and we can start to talk about it when you are able to put in monitor mode.

Let's talk about your other device which seems to be in monitor mode. I see it is not compatible to airmon. In first place I must say I recommend to buy adapters compatible to airmon, they are more stable and compatible to aircrack suite. I'm not sure to understand what is happening. You said that just selecting it on interface selection menu airgeddon is redirecting you to the exit saying that there is some kind of problem with the adapter... one question about this. Is this happening to you if you select the interface just plugged in? or the error comes if you did before launching airgeddon the trick to change it to monitor?

And another last set of questions, in the case you can select it flawlesly on menu just after plugging it without any early manipulation before launching airgeddon, what happens if you select the option to put it in monitor mode? is a crash happening? a controlled error? is it saying is ok in monitor mode and then is not working on scanning?

Some screenshots could help.

P.S. I'm working ok on rpi using Alfa compatible to airmon with a ralink chipset.

**Comment by gntook** [comment]
I am very sorry to hear about wlan1, as it gives far and away the best performance both for selecting APs and data throughput, albeit only on 2GHz. Not coincidentally, it is able to draw 500mA, whereas ra0 limits itself to 160mA.

For completeness, wlan1 is a Netis WF2116 and ra0 is a TP-Link Archer TU2H.

Forgive me, but I found your questions confusing. They seem to overlap and/or be redundant. I have attached three, sequential screenshots of an attempt using ra0.

file:///home/2018-09-21-112202_1360x768_scrot.png
file:///home/2018-09-21-112238_1360x768_scrot.png
file:///home/2018-09-21-112246_1360x768_scrot.png

Please, give them a look, and rephrase your queries.

**Comment by gntook** [comment]
I am very sorry to hear about wlan1, as it gives far and away the best performance both for selecting APs and data throughput, albeit only on 2GHz. Not coincidentally, it is able to draw 500mA, whereas ra0 limits itself to 160mA.

For completeness, wlan1 is a Netis WF2116 and ra0 is a TP-Link Archer TU2H.

Forgive me, but I found your questions confusing. They seem to overlap and/or be redundant. I have attached three, sequential screenshots of an attempt using ra0.


Please, give them a look, and rephrase your queries.

**Comment by gntook** [comment]
I am very sorry to hear about wlan1, as it gives far and away the best performance both for selecting APs and data throughput, albeit only on 2GHz. Not coincidentally, it is able to draw 500mA, whereas ra0 limits itself to 160mA.

For completeness, wlan1 is a Netis WF2116 and ra0 is a TP-Link Archer TU2H.

Forgive me, but I found your questions confusing. They seem to overlap and/or be redundant. I have posted links for three, sequential screenshots of an attempt using ra0.
https://ibb.co/d8WOsK
https://ibb.co/dfMdRe
https://ibb.co/cZ9Mez

Please, give them a look, and rephrase your queries. Also, let me know how I may determine the root cause of the problem with ra0. The error message is none too helpful.

**Comment by v1s1t0r1sh3r3** [comment]
Yeah about wlan1. If it is not possible to be set in monitor mode even out of airgeddon, that is not a airgeddon related problem, 😄 

About your other card... quite strange, I'm working on a rpi3 flawlesly using a ralink alpha card. Out of airgeddon, put here the output of these commands please:

While in managed mode:
`iwconfig ra0 2> /dev/null | grep Mode: | cut -d ':' -f 2 | cut -d ' ' -f 1`

The expected output is the string "Managed".

While in monitor mode:
`iwconfig ra0 2> /dev/null | grep Mode: | awk '{print $4}' | cut -d ':' -f 2`

The expected output is the string "Monitor".

If the output of both is not very helpful, put the entire output here before greping, cutting... I mean the output of a simple iwconfig command for both cases (Managed an monitor).

And last question... what is your wireless tools version? I guess is 30, just to confirm. You can see it launching `iwconfig --version`.

**Comment by gntook** [comment]
Here you go.

iwconfig ra0 2> /dev/null | grep Mode: | cut -d ':' -f 2 | cut -d ' ' -f 1
Auto
iwconfig ra0
ra0       Ralink STA  ESSID:"11n-AP"  Nickname:"MT7610U_STA"
          Mode:Auto  Frequency=2.412 GHz  Access Point: Not-Associated   
          Bit Rate:1 Mb/s   
          RTS thr:off   Fragment thr:off
          Encryption key:off
          Link Quality=10/100  Signal level:0 dBm  Noise level:0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0



iwconfig ra0 mode Monitor
iwconfig ra0 2> /dev/null | grep Mode: | awk '{print $4}' | cut -d ':' -f 2
Access
iwconfig ra0
ra0       Ralink STA  ESSID:""  Nickname:"MT7610U_STA"
          Mode:Monitor  Frequency=2.412 GHz  Access Point: Not-Associated   
          Bit Rate:1 Mb/s   
          RTS thr:off   Fragment thr:off
          Encryption key:off
          Link Quality=10/100  Signal level:0 dBm  Noise level:0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

iwconfig --version
iwconfig  Wireless-Tools version 30
          Compatible with Wireless Extension v11 to v22.

Kernel    Currently compiled with Wireless Extension v22.

ra0       Recommend Wireless Extension v14 or later,
          Currently compiled with Wireless Extension v22.

wlan0     Recommend Wireless Extension v21 or later,
          Currently compiled with Wireless Extension v22.

**Comment by v1s1t0r1sh3r3** [comment]
That is a problem of the driver... it should say "Managed" or "Monitor".

Auto is something custom they used and it is not standard. Try a different driver. Until you get "Managed" or "Monitor" on that commands airgeddon will not work for you. Sorry.

Closing.
