### ISSUE TITLE
Airgeddon puts wireless card back into normal mode automatically.

### ISSUE THREAD

**Issue by marvic2409** [v1s1t0r1sh3r3/airgeddon#177]
#### What is your airgeddon version?

8.11

#### What is your Linux O.S. and which version?

Ubuntu 18.04.1 LTS

#### Which is the chipset of your wireless card?

802.11 b/g/n Long-Range AWUS036NH

#### Describe the issue and the steps to reproduce it

Every time I try the evil twin attack (#9) it will capture the handshake fine but once it starts the actual attack it will put the wireless card back into normal mode and the whole things fails. I get this error "The interface changed its name while setting in managed mode. Autoselected 
wlan0: ERROR while getting interface flags: No such device"

Please Help!

**Comment by marvic2409** [comment]
If I try that I get the error :"This interface wlx00c0ca96dbd7 is not a wifi card. It doesn't support managed mode "

**Comment by marvic2409** [comment]
Name during monitor mode is wlan0mon

**Comment by v1s1t0r1sh3r3** [comment]
Seems like a non standard driver is used. Check this other use and follow the steps: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/175

Check the post on which iwconfig with grep and cut is used... launch it and put your output. It should say "Managed" or "Monitor". If you are receiving "Auto" or something like that, the driver is not standard. Tell to us the output of that commands.

**Comment by marvic2409** [comment]
Turns out I just needed to uninstall all packages and reboot and reinstall.

**Comment by v1s1t0r1sh3r3** [comment]
So... finally worked?
