### ISSUE TITLE
Captive Portal not displaying full passwords containing some symbols [Bug & Solution]

### ISSUE THREAD

**Issue by IsaiasWalton** [v1s1t0r1sh3r3/airgeddon#184]
#### What is your airgeddon version?

Airgeddon Script v8.11

#### What is your Linux O.S. and which version?

Linux 4.17.0-kali1-amd64

#### Which is the chipset of your wireless card?

Sagem XG-76NA 802.11bg ( zd1211b chip )

#### Describe the issue and the steps to reproduce it

Hi, here I'm going to present an issue and the solution I have found !

Evil Twin Attack:
1- Choose Interface Wlan0
2- Put interface in monitor mode
3- Evil Twin attacks menu
4- Evil Twin AP attack with captive portal (monitor mode needed)
5- Select Target
6- Deauth / disassoc amok mdk3 attack 
7- Select (No/N) for all further steps until you save the Handshake file.
8- Choose the language of captive portal : English
9- Launch the Attack !!!
10- In your device try to connect in the new open AP and insert a password containing these symbols *&\/?<> (Notice that the displayed password in the Control Window is missing all these symbols)

PROBLEM:
Captive Portal is not displaying some symbols after submiting password in the targeted device. (Example: testtest** > testtest ) the outputed password is missing the two stars.

SOLUTION:
After some investigations I found the solution and I'm suggesting if you can Fix this bug in the next version.
Check the attached screenshot of the highlighted lines to be fixed in the script "airgeddon.sh"

![captive portal password issue solution](https://user-images.githubusercontent.com/44380830/47323388-7813e700-d653-11e8-99f1-22c9f10bbe2d.png)

Cheers !!!

**Comment by OscarAkaElvis** [comment]
This is absolutelly intentional.

1. There are very few passwords containing these special chars. Most of the standard router/access point passwords doesn't contain this kind of chars. 
2. The reason to filter all of that special chars is to avoid being hacked while setting up the captive portal. In other way injections could be done on captive portal and the hacker could be hacked by some kind of command injection.

Closing.

**Comment by IsaiasWalton** [comment]
OK thanks for this clarification !

**Comment by KeyofBlueS** [comment]
Hi! Could I suggest to insert an option to not filter all of that special chars, at your own risk, with a big warning that You could be hacked?
Or even better, there is absolutely no way to temporarly block all commands (just inside the airgeddon's terminals) but those required to setting up the captive portal? For example creating a symlink to all of those required executables in, let's say, /tmp/airgeddon/bin/ and then setting the path with PATH=/tmp/airgeddon/bin (assuming that the attacker cannot change back PATH)
Do You think is it possible?

**Comment by OscarAkaElvis** [comment]
I created a plugin exactly for this: https://github.com/OscarAkaElvis/airgeddon-plugins
