### ISSUE TITLE
There is a problem with the selected interface. Redirecting you to script exit 

### ISSUE THREAD

**Issue by JeroenVBH** [v1s1t0r1sh3r3/airgeddon#185]
#### What is your airgeddon version?

v8.11
(bash version (4.4.23(1)-release) Minimum required is 4.2

#### What is your Linux O.S. and which version?

Kali Linux 2018.3

#### Which is the chipset of your wireless card?

Realtek RTL8812AU (Alfa AWUS036ACH)

#### Describe the issue and the steps to reproduce it

***************************** Interface selection ******************************
Select an interface to work with: 
1.  eth0  // Chipset: Intel Corporation 82540EM
2.  wlan0 // 2.4Ghz, 5Ghz // Chipset: Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter

***************************** airgeddon main menu ****************************** 
There is a problem with the selected interface. Redirecting you to script exit 
Press [Enter] key to continue...

*********************************** Exiting ************************************ 
Exiting airgeddon script v8.11 - See you soon! :) 

Checking if cleaning/restoring tasks are needed... 
No tasks to perform on exit 

root@kali:~/Downloads/airgeddon-master# 

Please help!

**Comment by JeroenVBH** [comment]
FYI, I did a clean install, used this video to get my AWUS036ACH working:
https://www.youtube.com/watch?v=zZG65GkWGdU
I passed all the tests and it shows me wireless lan`s etc.

**Comment by v1s1t0r1sh3r3** [comment]
First, I edited your message becase was a mess to view it. Second, this sounds like a non-related-to-airgeddon problem. I tried that card time ago and was working flawlessly on airgeddon. Since version v8.11 non compatible to airmon cards (like this) can be used. Check this other issue and perform some tests out of airgeddon: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/175

Check the post talking about this:

While in managed mode:
`iwconfig ra0 2> /dev/null | grep Mode: | cut -d ':' -f 2 | cut -d ' ' -f 1`

The expected output is the string "Managed".

While in monitor mode:
`iwconfig ra0 2> /dev/null | grep Mode: | awk '{print $4}' | cut -d ':' -f 2`

The expected output is the string "Monitor".

Of course you should replace ra0 by your network card name.

**Comment by v1s1t0r1sh3r3** [comment]
Ok is the same as the other issue:

That is a problem of the driver... it should say "Managed" or "Monitor".

Auto is something custom they used and it is not standard. Try a different driver. Until you get "Managed" or "Monitor" on that commands airgeddon will not work for you. Sorry.

Closing.

**Comment by JeroenVBH** [comment]
I installed my AWUS036ACH with this video and its links:
https://www.youtube.com/watch?v=zZG65GkWGdU

Do you rember the install process of your AWUS036ACH when you did the test?

**Comment by jarilaos** [comment]
Hi @JeroenVBH! 

I'm using the same adapter and airgeddon is working for me. I installed this official driver:
https://github.com/aircrack-ng/rtl8812au/tree/v5.2.20

Use this branch, 5.3.4 doesn't work.

As @v1s1t0r1sh3r3 says: "That is a problem of the driver... it should say "Managed" or "Monitor"."

**Comment by Dema323** [comment]
Having the same issue with WSU 1900 also getting Access instead of monitor. I used [https://aur.archlinux.org/packages/rtl88xxau-aircrack-dkms-git](url) as drivers. Any fix ?

**Comment by lornova** [comment]
I'm still getting the same error, on Kali 2019.2 x64. Used both v5.2.20 and v5.3.4 of rtl8812au.

**Comment by v1s1t0r1sh3r3** [comment]
Please, read the wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by Tejaswgupta** [comment]
as stated by @v1s1t0r1sh3r3 the command works for me. 
it outputs Monitor.
I'm on Airgeddon v10 and have also installed the official rtl8812au driver from airmon , airodump and other functions are working well , but when I open airgedddon and choose my interface , it says "There is a problem with the selected interface. Redirecting you to script exit"

Thank you.

**Comment by OscarAkaElvis** [comment]
Please, read this part of the Wiki. I created a plugin to work with these awful Realtek cards:

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Hall%20of%20Fame

**Comment by JellyWorld07** [comment]
hy everyone, i'm using airgeddon, but when i run "Explore for targets" i cant find any network.
I'm using a digitus dn-7045.
Kali linux is installed on a raspberry pi 4 model b 4gb of ram.
There are no errors in required and optional tools.
Is possible that my digitus dn-7045 is non compatible with kali?
In any case i bought from amazon an Alfa network adapter.

**Comment by OscarAkaElvis** [comment]
Hi @JellyWorld07 , if you want to ask something create your own issue. This thread is not related to what you are asking. I'm going to block this thread.

Better than ask on issues, join our Discord channel to discuss any problem there. You can find the invitation link on wiki contact section.
