### ISSUE TITLE
PMKID Attack with pcapng output

### ISSUE THREAD

**Issue by mrochaaa** [v1s1t0r1sh3r3/airgeddon#189]
Please add an option to capture PMKID in pcap or pcapng format, don't output 16800 as Wifite, because some persons use JTR to crack, then, with PMKID in pcap or pcapng, I can convert PMKID with wpapcap2john for instance, wpapcap2john dont support 16800 as input, but pcap or pcapng yes.

note: wpapcap2john now support pmkid

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, thank you for your suggestion. I'm very up to date about wifi news. I'm just run out of time to do all I want to do.

Probably this will be integrated using aircrack 1.4 which support directly all of this stuff. Still waiting until it reach the most of the repos. Closing
