### ISSUE TITLE
AP Mode Not Enabled

### ISSUE THREAD

**Issue by azamet90** [v1s1t0r1sh3r3/airgeddon#191]
#### What is your airgeddon version?
8.12

#### What is your Linux O.S. and which version?

Linux azamet 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux

#### Which is the chipset of your wireless card?

phy1	wlan1		88XXau		Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter

#### Describe the issue and the steps to reproduce it

everything is okay on my wlan0 which is intel wlan but on my alfa ACH model only the AP mode is not working what is the problem here? i love your app but i want to use it on my wifi adapter because of power of it can you pls help me about it? is this a bug or my fail?
sorry for posting again the other problem is like i said it is fully working on internal intel wifi which is i dont like because of the power but the script is kicking no one out from the target wifi so how will this attack succesfull then if no one is disconnected it is only disconnecting for few seconds on capturing handshake i did tryed to kick out users with my external usb wifi adapter but if i try it and give the target mac address the fake AP is automaticly destroyed too :D sorry for my bad english and noob questions sir

and before you said me maybe my wifi haves no vuln for ddos or something like that but it haves im sure about it because i dont want to say the name from apps i think it is forbidden but some github apps can deauth my wifi users and the aireplay-ng command is working too for deauthing users

i dont know what informations i need to give you but few of my files are looks like that:

/etc/dhcp/dhcpd.conf:
```
# dhcpd.conf
#
# Sample configuration file for ISC dhcpd
#

# option definitions common to all supported networks...
option domain-name "www.google.com";
option domain-name-servers 8.8.8.8, 8.8.4.4;

default-lease-time 600;
max-lease-time 7200;

# The ddns-updates-style parameter controls whether or not the server will
# attempt to do a DNS update when a lease is confirmed. We default to the
# behavior of the version 2 packages ('none', since DHCP v2 didn't
# have support for DDNS.)
ddns-update-style none;

# If this DHCP server is the official DHCP server for the local
# network, the authoritative directive should be uncommented.
#authoritative;

# Use this to send dhcp log messages to a different log file (you also
# have to hack syslog.conf to complete the redirection).
#log-facility local7;

# No service will be given on this subnet, but declaring it helps the 
# DHCP server to understand the network topology.

#subnet 10.152.187.0 netmask 255.255.255.0 {
#}

# This is a very basic subnet declaration.


    subnet 10.0.0.0 netmask 255.255.255.0 {
     range 10.0.0.100 10.0.0.150;
     option domain-name-servers 8.8.8.8 8.8.4.4;
     option subnet-mask 255.255.255.0;
     option routers 10.0.0.1;
     default-lease-time 43200;
     max-lease-time 86400;
    }

# This declaration allows BOOTP clients to get dynamic addresses,
# which we don't really recommend.

#subnet 10.254.239.32 netmask 255.255.255.224 {
#  range dynamic-bootp 10.254.239.40 10.254.239.60;
#  option broadcast-address 10.254.239.31;
#  option routers rtr-239-32-1.example.org;
#}

# A slightly different configuration for an internal subnet.
#subnet 10.5.5.0 netmask 255.255.255.224 {
#  range 10.5.5.26 10.5.5.30;
#  option domain-name-servers ns1.internal.example.org;
#  option domain-name "internal.example.org";
#  option routers 10.5.5.1;
#  option broadcast-address 10.5.5.31;
#  default-lease-time 600;
#  max-lease-time 7200;
#}

# Hosts which require special configuration options can be listed in
# host statements.   If no address is specified, the address will be
# allocated dynamically (if possible), but the host-specific information
# will still come from the host declaration.

#host passacaglia {
#  hardware ethernet 0:0:c0:5d:bd:95;
#  filename "vmunix.passacaglia";
#  server-name "toccata.example.com";
#}

# Fixed IP addresses can also be specified for hosts.   These addresses
# should not also be listed as being available for dynamic assignment.
# Hosts for which fixed IP addresses have been specified can boot using
# BOOTP or DHCP.   Hosts for which no fixed address is specified can only
# be booted with DHCP, unless there is an address range on the subnet
# to which a BOOTP client is connected which has the dynamic-bootp flag
# set.
#host fantasia {
#  hardware ethernet 08:00:07:26:c0:a5;
#  fixed-address fantasia.example.com;
#}

# You can declare a class of clients and then do address allocation
# based on that.   The example below shows a case where all clients
# in a certain class get addresses on the 10.17.224/24 subnet, and all
# other clients get addresses on the 10.0.29/24 subnet.

#class "foo" {
#  match if substring (option vendor-class-identifier, 0, 4) = "SUNW";
#}

#shared-network 224-29 {
#  subnet 10.17.224.0 netmask 255.255.255.0 {
#    option routers rtr-224.example.org;
#  }
#  subnet 10.0.29.0 netmask 255.255.255.0 {
#    option routers rtr-29.example.org;
#  }
#  pool {
#    allow members of "foo";
#    range 10.17.224.10 10.17.224.250;
#  }
#  pool {
#    deny members of "foo";
#    range 10.0.29.10 10.0.29.230;
#  }
#}
```

/etc/default/isc-dhcp-server:
```
# Defaults for isc-dhcp-server (sourced by /etc/init.d/isc-dhcp-server)

# Path to dhcpd's config file (default: /etc/dhcp/dhcpd.conf).
#DHCPDv4_CONF=/etc/dhcp/dhcpd.conf
#DHCPDv6_CONF=/etc/dhcp/dhcpd6.conf

# Path to dhcpd's PID file (default: /var/run/dhcpd.pid).
#DHCPDv4_PID=/var/run/dhcpd.pid
#DHCPDv6_PID=/var/run/dhcpd6.pid

# Additional options to start dhcpd with.
#	Don't use options -cf or -pf here; use DHCPD_CONF/ DHCPD_PID instead
#OPTIONS=""

# On what interfaces should the DHCP server (dhcpd) serve DHCP requests?
#	Separate multiple interfaces with spaces, e.g. "eth0 eth1".
INTERFACESv4="eth0"
INTERFACESv6=""
```

```
ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.3  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 xxxxxxxxxxxxxxxxxxxxxxxxx  prefixlen 64  scopeid 0x20<link>
        ether xxxxxxxxxxxxxxxxxx  txqueuelen 1000  (Ethernet)
        RX packets 423  bytes 512186 (500.1 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 315  bytes 31763 (31.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 19  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 20  bytes 1116 (1.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 20  bytes 1116 (1.0 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether fa:57:1a:d8:7d:2f  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        ether xxxxxxxxxxxxxxxxxxxx  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0


```

i tryed the wps attack too with pixie dust also the option 7 but it says unable to get beacon but it is catching beacons on 
airodump-ng wlan1 command :/ 
------------------------------------------------------------------------------------------------------------------------

sorry if i miss somethings again

**Comment by azamet90** [comment]
the wifi find mode and handshake mode only works if i click on right top corner to my usb wifi and open the interface for select join to wifi there is definitiv problem on the app maybe kali linux updated somethings

**Comment by OscarAkaElvis** [comment]
Oh my god... it seems you don't know how handshakes work... the handshake is captured if you are listening while a legitimate client connect to the network. So if you click as you say in the top corner and connect while capturing is going to work obviously. The handshake capturing is fully working. I tested it on Kali Linux even on last version and there is no problem there. It must be something on your side.

Maybe the DoS (not DDoS which is a different thing) is not working for you. As we said in the other closed issue you opened, there are a lot of factors. Clients, AP, chipsets, power, etc... maybe you are not capturing the handshake because the clients are not beig well disconnected because the DoS is not working well for your environment. What to do? as many hints said in airgeddon, just try another different attack, try another card and so on... but the DoS was the first thing implemented in airgeddon and it is fully working.

Regarding your failed Pixie Dust attack I must say that it is also working. Maybe not for you. To be successful on Pixie Dust attack is harder nowadays. Only some Access Points are vulnerable to this attack. It was the "boom" in 2012-2013 and now is difficult to find an AP vulnerable to Pixie Dust but I can assure to you that the implementation is ok and it's working.

And regarding your last problem related to the AP creation on your card I must say that is a known problem of compatibility between hostapd (what airgeddon uses to create AP) and that RTL8812AU chipset. So sorry, but it can't be fixed, at least in our side.

**Comment by azamet90** [comment]
i stil not know where the problem is with the AP intel chipset wifi is working with ap but not on alfa brand realtek chipset :/

**Comment by azamet90** [comment]
if i can change the mac address from the created AP will be much better for me because i cant send deauth attack to the orginal AP if mac is same with the name too

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, your english is not very good but anyway I think I understood you perfectly. You can't set up your AP using airgeddon on your Realtek Alfa card. And I repeat, that is out of our possibilities to help you. The problem is a known compatibility problem between hostapd program and the driver of your card. We can't do anything to help you, sorry.

I found for you this: https://github.com/igorpecovnik/hostapd/issues/1
It seems somebody compiled a special hostapd with support for your card. So maybe you can install that modified and customized hostapd instead of the standard installed by apt. Maybe in this way you can get it working I don't know. Good luck on that! :smile:

Regarding your created AP and the DoS, if you create exactly the same AP (BSSID, ESSID and channel), the DoS will affect to your fake created AP too. That's the reason airgeddon is clonning the BSSID except for one of the middle digits which is different. In order to avoid that kind of problems.

**Comment by azamet90** [comment]
sorry for opening topic again and again i did not see that you post a link i will try it thank you for your patience i hope u dont hate me

**Comment by v1s1t0r1sh3r3** [comment]
No problem, airgeddon comes from the space... Hates all human beings equally 😛

**Comment by mianYaseen** [comment]
> No problem, airgeddon comes from the space... Hates all human beings equally stuck_out_tongue

Sir respectfully I am using your tool in kali linux 2020.3 and having some trouble in evil twin attack. attacks runs smoothly but airgeddon is not creating second fake ap for victim to connect and give me the password please help!!!

**Comment by xpz3** [comment]
> > No problem, airgeddon comes from the space... Hates all human beings equally stuck_out_tongue
> 
> Sir respectfully I am using your tool in kali linux 2020.3 and having some trouble in evil twin attack. attacks runs smoothly but airgeddon is not creating second fake ap for victim to connect and give me the password please help!!!

You have not provided details regarding your setup like your wifi chipset, screenshot of error etc. So unable to help you. Join airgeddon discord channel for quick help. Click on the link below
https://discord.gg/sQ9dgt9

**Comment by mianYaseen** [comment]
Sir actually it does not show any kind of error and I am using alfa RTL8187 Wireless Adapter

**Comment by xpz3** [comment]
Rtl8187 required patched driver to work with airgeddon. It's an old adapter and doesn't support ap mode. A driver patch can make it work. But it requires some work to compile the specific driver with patches. The best way is to purchase a compatible adapter. https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
The above link has some compatible cards and chipset listed. Either buy one of them or try patching your driver for 8187. For instructions to patch the driver join discord channel. This will be my last comment regarding this here.

**Comment by mianYaseen** [comment]
> > > No problem, airgeddon comes from the space... Hates all human beings equally stuck_out_tongue
> > 
> > 
> > Sir respectfully I am using your tool in kali linux 2020.3 and having some trouble in evil twin attack. attacks runs smoothly but airgeddon is not creating second fake ap for victim to connect and give me the password please help!!!
> 
> You have not provided details regarding your setup like your wifi chipset, screenshot of error etc. So unable to help you. Join airgeddon discord channel for quick help. Click on the link below
> https://discord.gg/sQ9dgt9

I tried many time but does not show any kind of error 
everything looks perfectly working but there is no fake AP for victim to connect
deauthentication is even working perfectly

**Comment by mianYaseen** [comment]
i am in discord where are you???

> Rtl8187 requires patched driver to work with airgeddon. It's an old adapter and doesn't support ap mode. A driver patch can make it work. But it requires some work to compile the specific driver with patches. The best way is to purchase a compatible adapter. https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
> The above link has some compatible cards and chipset listed. Either buy one of them or try patching your driver for 8187. For instructions to patch the driver join discord channel. This will be my last comment regarding this here.
