### ISSUE TITLE
Check for IP command

### ISSUE THREAD

**Issue by WowMuchName** [v1s1t0r1sh3r3/airgeddon#205]
#### Describe the feature or compatibility enhancement and involved versions if apply

If **net-tools** is installed but **iproute2** is not, the script does not warn that prerequisits are missing. Instead when trying to selecting an interface, the list is empty with an error message that the **ip** command was not found.
I encountered this when creating a docker image based on debian:buster-slim.

#### What are the benefits of adding this?
The script should be consistent when checking for dependencies. In particular since you can't do anything without selecting an interface. This makes **iproute2** an required tool.

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, net-tools is required for ifconfig command.... do you mean that `ip` command is not available until iproute2 package is installed? I'll check for that and if is true I'll add it as "essential tool" dependency, no problem on that and easy to do. The point is that I thought that `ip` command was added "by default" in any Linux as grep, sed and many other tools in core-utils package. If it is not I'll fix this.

You must admit that this is happening only in "strange" environments. Usually by default all Linux have `ip` command. Anyway can be right. And building a Docker image from the scratch it may be required. Let me some hours to check this and thank you for the report.

**Comment by v1s1t0r1sh3r3** [comment]
omg you are right. `ip` command is included in iproute2 package so I'll add it as essential tool dependency for the next v9.0 version. Thanks for the report. Closing.

**Comment by v1s1t0r1sh3r3** [comment]
Added as essential tool on this commit: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/919b53d4e523fb920cf52283240823a5bce80a42
Added in Dockerfile: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/89aeab4260350ecef0410878c0bdcfeac709797e
Updated Wiki documentation regarding dependencies: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Essential-Tools
