### ISSUE TITLE
Evil Twin Attack error

### ISSUE THREAD

**Issue by shakim24** [v1s1t0r1sh3r3/airgeddon#209]
#### What is your airgeddon version?

8.12
#### What is your Linux O.S. and which version?

Kali Linux 2017.3 running on VirtualBox
#### Which is the chipset of your wireless card?
TP LINK WN722N v1

#### Describe the issue and the steps to reproduce it
Sorry guys for closing out issue #208 & #207, my issue wasnt uploading properly. Anyway Do you need 2 WiFi adapters to perform this attack. I tried doing this on my own network and I get a interface error when I selected my "Deauth" option. It says "on this screen, it's supposed an additional WiFi interface is chosen, but you don't have one at this moment". What is that from?

![img_20181228_190346](https://user-images.githubusercontent.com/8216564/50531131-527fdf80-0ad3-11e9-918f-11cf5fce7f65.jpg)

**Comment by Luan7805** [comment]
Do you have 2 wifi interfaces? Remember that in a virtual machine your integrated network card is recognized as ethernet.

**Comment by shakim24** [comment]
@Luan7805 I just have one which is the TP LINK that I mentioned. My virtual machine network is set to NAT so it picks up my host network.

**Comment by Luan7805** [comment]
It is not a error. With the options you have chosen it is necessary to have 2 wifi interfaces but you do not have it.

Read all tips: _If you want to integrate "DoS pursuit mode" on an Evil Twin attack, **another additional wifi interface in monitor mode will be needed to be able to perform it**_

**Comment by achrafloe** [comment]
Did you fix this problem because me too i have this problem

**Comment by JBalanza** [comment]
What do we have to fix? as mi partner @Luan7805 said before, this behaviour is not an issue. To perform a "DoS pursuit mode" you must have 2 wifi external cards. If you only have one then you can't do the pursuit mode. Just continue the attack without selecting pursuit mode and no error will be raised.

**Comment by Yuvansh22** [comment]
i have a external wifi adapter but still it shows this message pls gide me how can i fix it

**Comment by OscarAkaElvis** [comment]
@Yuvansh22 , did you read the thread entirely? DoS pursuit mode requires an additional external wifi adapter to be performed. So two cards are needed. Why did you pressed "y" when asked about DoS pursuit mode without knowing what is? the default option there is "no", so you forced it intentionally. Please, read about what you are doing: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-dos-pursuit-mode-exactly
