### ISSUE TITLE
Deauth issue

### ISSUE THREAD

**Issue by shakim24** [v1s1t0r1sh3r3/airgeddon#211]
#### What is your airgeddon version?

8.12
#### What is your Linux O.S. and which version?

Kali Linux 2017.3 running in VirtualBox
#### Which is the chipset of your wireless card?
TP LINK WN722N v1

#### Describe the issue and the steps to reproduce it
When testing the Evil Twin attack on my network it kicks me off my network to get a handshake but to deauth to get the WiFi password, it doesn't kick me off. So I have no portal screen to re-enter my password and connect to my WiFi. Need help!!!!!!!

**Comment by OscarAkaElvis** [comment]
This is a recurrent kind of issue (not really an issue), a duplicated one. All can I say for you is the same as this other issue: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/173

Try harder! closing.
