### ISSUE TITLE
beacon flood attack window stays blank with no output

### ISSUE THREAD

**Issue by saintofinternet** [v1s1t0r1sh3r3/airgeddon#212]
Beacon flood attack is failing to initiate as the window created for the attack stays blank with no data output.

**Comment by OscarAkaElvis** [comment]
Sorry but I must close this due lack of information. Read the issue creation policy before opening an issue.

https://github.com/v1s1t0r1sh3r3/airgeddon/blob/dev/CONTRIBUTING.md
