### ISSUE TITLE
Terminal mac support? 

### ISSUE THREAD

**Issue by LulzsecHackz** [v1s1t0r1sh3r3/airgeddon#215]
Does the tool work on mac HIgh Sierra without docker? i mean... on terminal? i didn't try it yet

**Comment by OscarAkaElvis** [comment]
This as asked before as you can see here: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/150

Sorry, it is not working for mac. There is no iwconfig on OSX. There is airport command which generates a very different output as explained here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Known-Incompatibilities

Even Docker stuff is in alpha phase for OSX and the same for Windows. Docker airgeddon image is working only for Linux for now...

The unique solution to work with airgeddon on OSX is installing a Linux virtual machine using virtualbox, vmware, parallels or similar. Closing.
