### ISSUE TITLE
not able to install airgeddon in mac

### ISSUE THREAD

**Issue by mrshadowfac3** [v1s1t0r1sh3r3/airgeddon#223]

**Comment by Luan7805** [comment]
Mac is not compatible. Maybe in the future with [docker.](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker%20Mac%20OSX)

Please read the compatibility section:
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility
