### ISSUE TITLE
Dumb-Down for Enterprise attacks (Help-Wanted)

### ISSUE THREAD

**Issue by OscarAkaElvis** [v1s1t0r1sh3r3/airgeddon#224]
Hi, at this moment we are researching in order to try to implement Dumb-Down attack for Enterprise attacks and we need some support from anybody who have experience with this. We'll leave this issue open here for some time. It will be closed if finally we are not able to make it work.

 - __What we have now__

At this moment (v9.01), if a client is connecting to the fake airgeddon Enterprise Evil Twin network, using default configuration (for example in an Android device it is PEAP / MSCHAPV2), only hashes are captured (JTR and hashcat format). If you set manually TTLS / PAP , then the credentials are captured in plain. This is a screenshot of both cases:

![enterprise](https://user-images.githubusercontent.com/5803348/53074571-6fd99480-34eb-11e9-887b-601202c561d3.png)

 - __What we want__

What we want to do is to try to "trick" to clients in order to force them to use that insegure configuration to negotiate the auth. Doing this, plain passwords will be captured. That's the theory of a Dumb-Down attack.

 - __History__

It seems that this Dumb-Down attack is an "old" stuff. It was discovered in 2012 and the "boom" was during 2013 and 2014. We've read that only "old" clients are affected and only them are able to be forced to use the insecure configuration. Probably iOS 5, 6 or 7 as maximum... and on Android not sure... maybe Android 3 or maybe 4. Probably most modern clients are patched to avoid this.

 - __Current investigations__

At this moment, we are reading some papers about how to implement the Dumb-Down attack using `freeradius-wpe` and `hostapd-wpe`. Just testing (out of airgeddon) in order to make it working. But for now we weren't able to make it to work.... connecting using different Android clients using default configuration (PEAP / MSCHAPV2) but it seems we are not able to force clients to use the insecure configuration... only hashes captured, no plain text passwords. We searched through web looking for freeradius example config files to do this but no luck yet. All we've found is demos or papers not showing the needed config.

 - __Needed help__

If is only affecting to a very old clients, maybe it doesn't worth the time to implement it, but to be sure about this, we need feedback from people who did this before and who saw this working. We'll need `freeradius` or `freeradius-wpe` configuration and we need to know on which kind of clients it worked (O.S. and version). Any help is welcome. Thanks.

**Comment by alk99-abderrahman** [comment]
The simplest  idea i can think of is to show a message says only pap is supported ... s
Chose  it from the second section

**Comment by paiwankhonkaeng2525** [comment]
Paiwankhonkaeng

**Comment by v1s1t0r1sh3r3** [comment]
Closing this due lack of help.
