### ISSUE TITLE
Add MDK4 deauth mode

### ISSUE THREAD

**Issue by underscrew** [v1s1t0r1sh3r3/airgeddon#226]
#### Describe the feature or compatibility enhancement and involved versions if apply

MDK4, the new version of MDK3

#### What are the benefits of adding this?

All the new features (interesting ones) are listed here: https://github.com/aircrack-ng/mdk4/

I already tested the deauth on my RTL8812AU and it is working flawlessly (and faster) on 5Ghz channels.

**Comment by OscarAkaElvis** [comment]
It is already implemented on "dev" branch. Ready to be released for the next 9.10 version. Closing.
