### ISSUE TITLE
Expand 5GHz channels to include US capability beyond channel 112, please.

### ISSUE THREAD

**Issue by rick-wifi-guy** [v1s1t0r1sh3r3/airgeddon#230]

**Comment by rick-wifi-guy** [comment]
Your latest version doesn't account for the US expanded frequencies in the UNII-2 Extended and UNII-3 bands.  This will allow for use of your tool within the US for testing and educational purposes.  Perhaps a way to identify frequencies or channels available based on the regulatory domain found by "iw reg get"?

**Comment by OscarAkaElvis** [comment]
Not planned yet man, sorry. We'll take it in consideration. Anyway, we accept pull requests. Thanks for the suggestion. Closing.
