### ISSUE TITLE
5g wifi evil twin attack 

### ISSUE THREAD

**Issue by yesman1214322** [v1s1t0r1sh3r3/airgeddon#232]
hi am trying to use the evil twin attack on the 5g but it does seem to work ,would you have any idea why it would be doing this and would you recommend an 5g wifi card which you have test it with thanks

**Comment by v1s1t0r1sh3r3** [comment]
Closing this due to many reasons. This issue doesn't meet the issue creation policy.

No info about versions, O.S., chipset. No template filled up. No details, no screenshots, just a "does seem to work" which means that is working. So no issue here.

**Comment by JBalanza** [comment]
Probably your external wifi card does not support 5GHz bands, there only a few that support it and that works OK with aircrack-ng suite. In my opinion one of these cards is "ALFA Network AWUS051NH V2" but it is very hard to find available to buy.
