### ISSUE TITLE
A windows based attack !

### ISSUE THREAD

**Issue by minanagehsalalma** [v1s1t0r1sh3r3/airgeddon#235]
https://null-byte.wonderhowto.com/how-to/android-for-hackers-exfiltrate-wpa2-wi-fi-passwords-using-android-powershell-0192242/

Just like what is in the tutorial ... But we will our local server in rouge ap to receive the passwords ...we need this to be only activated in case the connected device is windows .

just remove the Ngrok part from the tutorial ... and all what's left is a rogue ap with php server and fake page that asks for the password by downloading/auto downloading the powershell or the good designed exe file only when a windows device is detected ...

how else you can send the wifi passwords to the local php server without using Ngrok/making it public....
the answer is using a rogue ap.

like

1- we start the rouge AP+ the local php server
2- the a device connects to the rouge AP after he's being disconnected from his ap
3- we detect that is a windows device using user agent .etc
4- the captive portal page that shows up asks the user to download the wifi password
5- after he opens the file and the passwords are sent . we show him the password in text file (optional )
6- done

**Comment by minanagehsalalma** [comment]
@OscarAkaElvis

**Comment by v1s1t0r1sh3r3** [comment]
This is not the point of airgeddon. You didn't filled the issue template. Closing.
