### ISSUE TITLE
Scenario asks user to push the WPS button if it is available 

### ISSUE THREAD

**Issue by minanagehsalalma** [v1s1t0r1sh3r3/airgeddon#236]
I Have already feedbacked this to wifiphisher and they added it in great way ..... but i also love to see it in your tool.... as i get more satisfaction with ........... and it's more stable and has more success ratio than it
https://github.com/wifiphisher/wifiphisher/issues/494
can we see it in your tool ?

tbw
@OscarAkaElvis

**Comment by v1s1t0r1sh3r3** [comment]
Another issue violating the issue creation policy. Last warning before ban.

Sorry but we don't really care about other scripts. We can plan our own features. I read the first 4 posts and I must say that we will never develop anything on which a custom development for vendor should be added. We like generic stuff.
