### ISSUE TITLE
Would a EAP GTC ... Downgrade be useful ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [v1s1t0r1sh3r3/airgeddon#238]
Look
https://github.com/sensepost/mana/issues/104
I think

It would be use to get rid of the captive portal and hsts / DNS headache !!

a tweet that may help you 
https://twitter.com/W00Tock/status/1019251419310972930

BTW i am not planing to attack wpa Enterprise .... but just wpa/wpa2.
and or 
 i have found this [script ](https://github.com/Tylous/SniffAir) that 

> [+] Evil Twin - Creates a Fake Access Point, Clients Connect to Divulging MSCHAP Hashes or Cleartext Passwords

i hope you add the feautre

**Comment by v1s1t0r1sh3r3** [comment]
Please stop opening too much issues or you'll be banned.

You are not following the issue creation policy. And regarding this... it is duplicated. We are already working on this. Please, read before opening issues: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/224

Closing.
