### ISSUE TITLE
captive portal

### ISSUE THREAD

**Issue by jeretc** [v1s1t0r1sh3r3/airgeddon#241]
#### Describe the feature or compatibility enhancement and involved versions if apply

is it possible to add a custom captive portal with the evil twin AP.

#### What are the benefits of adding this?

custom templates/portals with username/login captive portal will be good if can be selected during the Evil AP, so clients connected to this evil ap will be redirected to this portal.

**Comment by v1s1t0r1sh3r3** [comment]
This was already asked before. Duplicated issue:

https://github.com/v1s1t0r1sh3r3/airgeddon/issues/74
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/132

Sorry but if it is custom... how can we know how to custom it? to show what? airgeddon captive portal is a generic one. If you want to perform tailored attacks you must do it manually. On that links you'll find the info about where and how to modify captive portal files. Closing.
