### ISSUE TITLE
RTL8812AU AWUS036ACH / Alfa AC1200

### ISSUE THREAD

**Issue by chic01taliano** [v1s1t0r1sh3r3/airgeddon#242]
#### What is your airgeddon version?

9.01

#### What is your Linux O.S. and which version?

Kali 2019.1a

#### Which is the chipset of your wireless card?

RTL8812AU
latest drivers installed via realtek-rtl88xxau-dkms

#### Describe the issue and the steps to reproduce it

Hi, i've encountered 2 issues using airgeddon evil twin module toolset.
-After exploring i get to the capturing handshake window and after a while the WPA handshake appears to be successful and yet the window runs forever; ctrl+c on the window is the only way to get rid of it but the .cap doesn't seem to have been saved anywhere and airgeddon freezes forcing me to restart it.
I can do it via airodump/aireplay without any issues so i assume it's some other process/command executed by airegeddon that causes troubles.
-Skipping ahead, once i have the cap i got to the last (6 windows) evil twin step which should start the deauth but the attacks don't seem to have any effect despite the fact that the AP is right beside the adapter so i tried to re-run the evil twin module but this time when the exploring was supposed to start i'm presented with an empty window that doesn't even quit via ctrl+c.

![Screenshot from 2019-03-23 22-21-31](https://user-images.githubusercontent.com/15007338/54871850-29fa3f80-4dbb-11e9-98cd-49ba52020cb5.png)

I forcibly closed all the windows, run airgeddon but when it comes to selecting the adapter i'm presented with this window without being able to do anything

![Screenshot from 2019-03-23 18-51-17](https://user-images.githubusercontent.com/15007338/54871881-a2610080-4dbb-11e9-9ee4-514bab4e241e.png)

I'm a noob but i've done some probing and i'm posting them hoping they will come in handy.
Thank you in advance

![Screenshot from 2019-03-23 18-03-27](https://user-images.githubusercontent.com/15007338/54871923-5febf380-4dbc-11e9-8903-dcd2f95a5701.png)

![Screenshot from 2019-03-23 18-06-53](https://user-images.githubusercontent.com/15007338/54871928-6a0df200-4dbc-11e9-886c-c08edc32bdfb.png)

![Screenshot from 2019-03-23 18-09-38](https://user-images.githubusercontent.com/15007338/54871932-75611d80-4dbc-11e9-8285-942e494f0385.png)

**Comment by OscarAkaElvis** [comment]
Hi, that is because your driver is not the best for this... that card is always causing problems. The best driver for that card in order to work with airgeddon is the available on repos that can be installed by apt `apt install realtek-rtl88xxau-dkms`

Duplicated:
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/233
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/185
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/233
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/203

Closing.

**Comment by chic01taliano** [comment]
Sorry i did not know that. Can you recommend an adapter as performant as this one with 5GHz capabilities that is known to be working?

**Comment by OscarAkaElvis** [comment]
AWUS052NHS has a Ralink RT3572 chipset and is working flawlessly for me. It supports 5ghz and is airmon compatible.

**Comment by chic01taliano** [comment]
Cannot find it on any major retailer. Any tips?

**Comment by OscarAkaElvis** [comment]
AWUS051NH also works fine. It also has 5ghz support. Same chipset.
