### ISSUE TITLE
what's the problem???

### ISSUE THREAD

**Issue by huitc** [v1s1t0r1sh3r3/airgeddon#246]
```
***************************** airgeddon main menu ****************************** 
There is a problem with the selected interface. Redirecting you to script exit 
Press [Enter] key to continue...

*********************************** Exiting ************************************ 
Exiting airgeddon script v9.10 - See you soon! :) 

Checking if cleaning/restoring tasks are needed... 
No tasks to perform on exit 


```

**Comment by xpz3** [comment]
Possible driver issue. Your interface is neither in managed nor in monitor mode. Thats why the script is exiting. Paste output of `iwconfig`
You can manually put your interface in monitor mode before running airgeddon and possibly it will work

**Comment by OscarAkaElvis** [comment]
You didn't filled the needed questions on the issue creation template. We need a lot of data like your chipset, O.S, etc... all that info we need in order to try to understand your problem should be provided directly. So, closing due issue creation policy violation.

**Comment by huitc** [comment]
ok sorry
