### ISSUE TITLE
certificates

### ISSUE THREAD

**Issue by stridjj** [v1s1t0r1sh3r3/airgeddon#247]
#### Describe the feature or compatibility enhancement and involved versions if apply

My question is like #171 BUT differ.
Is it possible to create new certificate with LetsEncrypt every time after  E.T. captive portal attack was launched? I mean airgeddon with LetsEncrypt assistance creates certificate when the ET captive portal started and when attack is completed the certificate will be removed

**Comment by stridjj** [comment]
and if it's possible, would this feature be added to airgeddon?

**Comment by v1s1t0r1sh3r3** [comment]
Yes it's possible but that is not going to be added due the maintenance it needs. LetsEncrypt are providing for free certificates valid only for 90 days. This was already discussed in the thread you referenced and probably in some more. Too demanding maintenance for us, Sorry.

We are open if a donor want to contribute to the project buying a certificate or donating the needed amounth to buy the domain and the certificate needed (for at least 3 years). In that case we can add it.

Closing.

**Comment by stridjj** [comment]
How many does it cost for 3 years?

**Comment by v1s1t0r1sh3r3** [comment]
Not sure... prices should be checked... first a domain is needed. The cert is issued to a domain and the cert issuer needs to check that you are the real owner of the domain. After getting the cert, the domain is not going to be used anymore on internet... just registered. The domain is what is going to be used on Evil Twin on captive portal with a dns redirection... so it needs to be something like "networkconnectioncheck.net" or "internetaccesschecking.net" or any similar which could be unregistered and free to register. The Evil Twin could make the "dns black hole" to captive portal showing the right domain with its cert matching the domain and the cert and issued by a trusted cert issuer... so it wil be shown in "green" by the browser.

Maybe it could be some kind of offer including the domain and the cert for at least 3 years (I think they are offers for 1, 3 and 5 years, not sure), but 1 year is too few. What we need is to try to maintain this as less as possible, so 3 years as minimum in my opinion. We can check on some providers like DigiCert, GoDaddy or similar.
