### ISSUE TITLE
wlp3s0 -- monitor mode support?

### ISSUE THREAD

**Issue by DrPhilosophus** [v1s1t0r1sh3r3/airgeddon#257]
![Screenshot from 2019-05-23 17-15-15](https://user-images.githubusercontent.com/45126275/58250230-8c9d9680-7d7e-11e9-90b7-e0ea2fdf5e0b.png)

ifconfig wlp3s0 down
iwconfig wlp3s0 mode monitor
ifconfig wlp3s0 up

I'm in monitor mode and after a while it changes to managed mode.
I tried changing to monitor mode via the airgeddon script. But WiFi settings disappears as I enable monitor mode.

$ lspci | grep -i wireless
03:00.0 Network controller: Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter (rev 31)

**Comment by OscarAkaElvis** [comment]
Sorry but I'm going to close this issue due violation of the issue creation policy. All questions must be filled up to avoid the lose of time now asking to you your versions, OS, etc.

Closing.
