### ISSUE TITLE
free wifi honeypot

### ISSUE THREAD

**Issue by AdamChehade** [v1s1t0r1sh3r3/airgeddon#262]
can you add a very simple feature being the ability to have a fake open public WiFi hotspot that requires google credentials to access and the credentials will be stored. I will be happy to help

**Comment by JBalanza** [comment]
This Issue does not accomplish with the issue creation policy. Furthermore, Airgeddon does implement this. It is an "Evil Twin Captive Portal" with a customized captive portal. You can find captive portal HTML files on /tmp/www, feel free to customize your way. Closing
