### ISSUE TITLE
How much time it takes to brute force wps pin using airgeddon? 

### ISSUE THREAD

**Issue by MohammadBinAftab** [v1s1t0r1sh3r3/airgeddon#265]
Sir I have a question for you. The question is that how much time it takes to brute force wps pin using airgeddon.

**Comment by JBalanza** [comment]
It depends on so many factors we cannot answer. Airgeddon uses reaver and bully repositories for WPS attack so you can take a look at them. WPS PIN has over 100.000.000 different combinations and they must be bruteforced online against the AP so...a lot of time would be required. Closing.
