### ISSUE TITLE
Pixie Dust

### ISSUE THREAD

**Issue by iDream3r** [v1s1t0r1sh3r3/airgeddon#266]
#### What is your airgeddon version?

Airgeddon v9.20

#### What is your Linux O.S. and which version?

Kali Linux 2019.1a - Running on Oracle VM VitualBox

#### Which is the chipset of your wireless card?

Alfa Network AWUS036ACH - RTL8812AU

#### Describe the issue and the steps to reproduce it

Every Pixie Dust attack launched stopped unsuccesfully at the particular PIN value 27728253. 
On all the networks I tested (5) I get this looped until the attack timeout :

[!] Received disassociation/deauthentification from the AP
[+] Tx( ID ) = 'NoAssoc' Next pin '27728253'
[+] Rx( Auth ) = 'Timeout' Next pin '27728253'
[+] Rx( ID ) = 'Timeout' Next pin '27728253'

Or:

[+] Last State = 'NoAssoc' Next pin '27728253'
\< Block of data bellow \>

The custom PIN association obviously didn't work. I hope you can help me, thank you for your time.

**Comment by v1s1t0r1sh3r3** [comment]
In first place you didn't specified if you are using bully or reaver. In second case I must say you have one of the worst chipsets ever. In third place... I can say Pixie Dust attacks are working, the hard part is to find an AP vulnerable to it... so probably that AP is not vulnerable. Even with a vulnerable AP the distance, the signal, all factors are important. Not an airgeddon issue. Closing.
