### ISSUE TITLE
captive portal https

### ISSUE THREAD

**Issue by stridjj** [v1s1t0r1sh3r3/airgeddon#267]
#### Describe the feature or compatibility enhancement and involved versions if apply

I'm not understand in coding at all. So please check and answer my question. if I'm not misstaken airgeddon is able to redirect  to captive portal when victim is using http connection only at that moment. Am I right? Could we use ngrok to make airgeddon able to work with https too? It seems ngrok is able to do it. For example  "$service apache2 start && ngrok http 80" gives us opportunity to use apache2 over WAN. What do you think?

**Comment by stridjj** [comment]
and ofcourse there is https connection with apache2 in this example

**Comment by OscarAkaElvis** [comment]
Hi, the https was removed from the captive portal just for a simple reason: we have not a valid certificate to use it in the captive portal. We prefer to not use https which is better than using a fake or self signed certificate which will alert the user saying this is insecure!

I think you are "mixing" some stuff. To launch a Captive portal it's not needed to have internet access. ngrok is a service to expose on internet local stuff. What about the scenario on which you don't have internet access? for example using a laptop inside a car on the parking of the company on which you are performing the wifi pentest. 

This was already discussed before. Please, read this: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/171
