### ISSUE TITLE
airgeddon do not stop mdk4 dos purity attack if wpa key is correctly entered in web page

### ISSUE THREAD

**Issue by thieulam** [v1s1t0r1sh3r3/airgeddon#270]

**Comment by thieulam** [comment]
kali linux 2017.1
airgeddon 9.20
phy1	wlan1               rtl8187		Realtek Semiconductor Corp. RTL8187
phy2	wlan2		rt2800usb	Ralink Technology, Corp. RT2870/RT3070

the sript works fine, but if i use evil portal with etho internet access and mdk4 DoS puirti mode for channel change, it do not stop the mdk4 attacK if the wpa key is entered correctly.
![20190629_172235](https://user-images.githubusercontent.com/51470165/60386370-4d0c4d80-9a94-11e9-8a33-cb621f496513.jpg)

**Comment by v1s1t0r1sh3r3** [comment]
DoS puirti mode = DoS pursuit mode , I guess... quite weird, all the processes should be killed. I'll do some tests.

Are you able to reproduce it? I mean, sometimes it could be a circunstancial or temporary error. Is it always doing this if you try again?

**Comment by thieulam** [comment]
Yes, Dos pursuit mode..
The problem is always present only with this mode.
With aireplay-ng deauth mode no problem

**Comment by v1s1t0r1sh3r3** [comment]
I was able to reproduce it. You are right, using mdk4 in DoS pursuit mode, after right pass capture on evil twin, the process is not killed. Using same attack on airgeplay it works flawlessly. I'll check this when I have time to get deeper on this. Is not critical, so no rush. Thanks for reporting.

**Comment by v1s1t0r1sh3r3** [comment]
This is fixed now. It will be released on next version 9.21. Can you @thieulam download and give it a try? I already did a lot of tests but it could be nice to have your feedback.

The fix is in a temporary branch called "hotfix", so you can do `git clone -b hotfix https://github.com/v1s1t0r1sh3r3/airgeddon` to test it. Thanks.

**Comment by thieulam** [comment]
Yes, i can. Tomorrow i can send the result of test.
Regards..

**Comment by thieulam** [comment]
Ok perfect!
The kill is working now!
great work!
Is it possible to insert a function that turns off the fake ap if the line under attack disappears for about 15 seconds?
And as soon as it returns is the fake line reopened?
It often happens that those who are under attack switch off the power to the modem to restore it, and it is strange that the fake line remains present

**Comment by v1s1t0r1sh3r3** [comment]
Sorry man, thanks for the suggestion but not for now. Closing.
