### ISSUE TITLE
Evil Twin Attack-weakness in code

### ISSUE THREAD

**Issue by millionhz** [v1s1t0r1sh3r3/airgeddon#273]
I was testing Airgeddon today and found a problem that weakens the attack.
There is a slight problem when the victim connects to the fake AP

On mobile phones, if the victim connected and ignores the 'sign in to use internet' notification he's just stuck with a broken wifi connection. If he visits a website, all it would say is unable to make a connection.

The same issue persists on Desktop devices along with the problem that the victim is not prompted to sign in as he connects. 

#### Describe the feature or compatibility enhancement and involved versions if apply

Make the script redirect all kinds of requests to the login page so the victim has no other option but to enter the password.
The website used to steak credentials should have a fake ssl certificate attached thus https and hsts sites are also affected.

This will make the attack more effective.

**Comment by OscarAkaElvis** [comment]
Hi, I edited the last phrase of your question. We don't talk here about other tools.

Regarding what you say is not true. If the victim closes the automatic "sign to use internet" notification, the captive portal can be reached just opening any other http website. I tested it, it works. Probably what is happening to you is that you are trying to open a https site.

As it was discusse many and many and many times... we prefer an error to an insecure web page warning due the self-signed certificate. Check these:

https://github.com/v1s1t0r1sh3r3/airgeddon/issues/267
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/171

Closing.
