### ISSUE TITLE
tmux+ Evil Twin AP attack with sniffing and bettercap-sslstrip2/BeEF

### ISSUE THREAD

**Issue by alexl83** [v1s1t0r1sh3r3/airgeddon#283]
#### What is your airgeddon version?

9.20

#### What is your Linux O.S. and which version?

Kali Linux 2019.2 - Raspberry Pi 3 B+

#### Which is the chipset of your wireless card?

 Ralink Technology, Corp. RT5370

#### Describe the issue and the steps to reproduce it

Whenever 'AIRGEDDON_WINDOWS_HANDLING=tmux' , Evil Twin attack (beetercap/sslstrip2/Beef) won't stop; pressing 'ENTER' in the main window doesn't have any effect.
IT seems that with this specific attack, 'Control' windows is not created in tmux session

Everything works as supposed when  'AIRGEDDON_WINDOWS_HANDLING=xterm' , but headless capability is somewhat lost.

Could you support please? I'm available to test and experiment if needed

Thank you!

**Comment by alexl83** [comment]
solved by changing line 10005 to

`get_tmux_process_id "beef -c \"${beef_file}\""`

**Comment by OscarAkaElvis** [comment]
Thanks for the report anyway. It seems this is a bug. Already fixed.
