### ISSUE TITLE
Can't explore for targets (Unexpected Error)

### ISSUE THREAD

**Issue by thiggy01** [v1s1t0r1sh3r3/airgeddon#285]
### What is your airgeddon version?

9.21

#### What is your Linux O.S. and which version?

Ubuntu 18.04.1 on an external HDD (no Virtual Machine used)

#### Which is the chipset of your wireless card?

ralink technology corp. mt7601u 

#### Describe the issue and the steps to reproduce it

As i run `sudo ./airgeddon` inside airgeddon folder, the script detects my system as Ubuntu Linux, as expected.

![Screenshot from 2019-08-12 21-57-05](https://user-images.githubusercontent.com/20028082/62908010-37a16900-bd4c-11e9-8ab9-5eadf34ea2d4.png)

Then, after every tool checked being ok, the script says it is updated

![Screenshot from 2019-08-12 22-02-06](https://user-images.githubusercontent.com/20028082/62908145-e645a980-bd4c-11e9-9ed8-3a4d72f04174.png)

Next, I'm asked to select my wifi card with chipset Chipset: Ralink Technology, Corp. MT7601U

![Screenshot from 2019-08-12 22-04-40](https://user-images.githubusercontent.com/20028082/62908207-3290e980-bd4d-11e9-87ff-d2de1e9cdc6b.png)

Here's when i set it to monitor mode

![Screenshot from 2019-08-12 22-07-01](https://user-images.githubusercontent.com/20028082/62908270-8996be80-bd4d-11e9-8b63-507a66ae2fc1.png)

Then i select the WPS attacks option from menu

![Screenshot from 2019-08-12 22-10-50](https://user-images.githubusercontent.com/20028082/62908375-1772a980-bd4e-11e9-9e27-644129543fc2.png)

Finally, when i select to explore for targets i get this error message "An unexpected error occurred, redirecting to the menu " and i'm redirected to the menu.

![Screenshot from 2019-08-12 22-12-08](https://user-images.githubusercontent.com/20028082/62908439-720c0580-bd4e-11e9-844b-f3bf8794491a.png)

After reviewing syslog, i see the following messages after this error:
__<info>  [1565658412.7571] modem-manager: ModemManager now available_
<info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-12': not supported by any plugin
<info>  Couldn't check support for device '/sys/devices/pci0000:00/0000:00:14.0/usb1/1-12': not supported by any plugin_

Maybe it has something to do with the problem of "explore the targets" not working.

**Comment by OscarAkaElvis** [comment]
This is because you are using the new interface names style. Read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility

Follow the steps from the __important compatibility notes__ to change the interface names to old style. Closing.

**Comment by c7b3rx** [comment]
> This is because you are using the new interface names style. Read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Compatibility
> 
> Follow the steps from the **important compatibility notes** to change the interface names to old style. Closing.

whats the solution of this ? i'm also getting same error message when selecting to explore targets
An unexpected error occurred, redirecting to the menu

**Comment by dengbds** [comment]
i have the same problem   did u get urs fixed?

**Comment by OscarAkaElvis** [comment]
read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

**Comment by dengbds** [comment]
I think that is it.   How do get to the grub can’t find it
Thanks

**Comment by OscarAkaElvis** [comment]
If you don't know how to do that, probably you'll need a lot of help. Join to discord channel to discuss further. Invitation link: https://discord.gg/sQ9dgt9

**Comment by dengbds** [comment]
Thanks I am in it in nano. Just have to learn nano.  Lol

**Comment by dengbds** [comment]
Well I did that but get error when I try to update-grub

**Comment by OscarAkaElvis** [comment]
This is not the place to talk about this. As I said, if you want support, join discord. Locking thread.
