### ISSUE TITLE
How to create a really cool Wi-Fi map of your neighborhood

### ISSUE THREAD

**Issue by krll-k** [v1s1t0r1sh3r3/airgeddon#29]
<img src="https://cdn1.tnwcdn.com/wp-content/blogs.dir/1/files/2016/10/Screen-Shot-2016-10-12-at-11.37.13-796x427.png"></img>
Have you ever heard of wardriving? It’s the act of searching for and mapping Wi-Fi networks from a moving vehicle. It’s a really cool way to create a map of the wireless signals in a certain location.

Scott Helme shows us it’s not that hard to do. He equipped his car with the right tools, drove around his town and mapped a total of 10,442 access points. He then proceeded to put all of their coordinates together in Google Maps, resulting in the following alternative view of his neighborhood:

http://thenextweb.com/shareables/2016/10/12/wi-fi-wardriving-easy/

**Comment by v1s1t0r1sh3r3** [comment]
@krll-k please, this section is to create and discusse about issues on the project. Please, don't use this as a forum for offtopics. Thank you.
