### ISSUE TITLE
No interface selected on "Kali arm Linux"

### ISSUE THREAD

**Issue by patrickteivas** [v1s1t0r1sh3r3/airgeddon#292]
#### What is your airgeddon version?

9.21

#### What is your Linux O.S. and which version?

Kali Linux RaspberryPi 2019.2a 32bit

#### Which is the chipset of your wireless card?

Ralink Technology, Corp. RT2070/RT3070

#### Describe the issue and the steps to reproduce it

After airgeddon performs necessary scripts and new version check, it gives interface selection.
I'm selecting my wireless card, trying to put it to monitor mode and get the message
```
The interface changed its name while in monitor mode. Autoselected

Monitor mode now is set on
```
after I press Enter I get `No interface selected. You'll be redirected to select one`. Even if I try to select my wireless card again, it gives me the same error.
Tested same wireless card in preinstalled airgeddon (v9.11) on live Parrot OS Home 4.6 amd64 build, it also gave me the message about `Name changed`, but worked normally.
Tested a built-in wireless card and it worked normally.
The only dependency I have not installed is `hashcat` (Maybe it depends).

![Oj3web3](https://user-images.githubusercontent.com/29047825/63646810-4ced9e80-c721-11e9-97df-ca3ce8d0c5e6.png)
![7g7gs0h](https://user-images.githubusercontent.com/29047825/63646815-61ca3200-c721-11e9-91e1-ddbc4fbfe31c.png)
![oPzjQPl](https://user-images.githubusercontent.com/29047825/63646816-6393f580-c721-11e9-96d2-230d62b3052a.png)

**Comment by patrickteivas** [comment]
Hm, monitor mode with a built-in wireless card was successful.

**Comment by OscarAkaElvis** [comment]
Pretty weird man... I also have an Alfa card with same chipset and it works fine for me... some questions:

 - Is your card plugged by usb, right?
 - Is the problem on your wlan0 which is the RT3070 chipset, isn't it?
 - Confirm that wlan1 is your internal Raspberry wifi card
 - Which model of Raspberry pi do you have? I think internal wifi card can't be in monitor mode (not sure about the new Raspberry Pi model 4, I don't have yet one of them).

**Comment by patrickteivas** [comment]
> * Is your card plugged by usb, right?
Yep.
> * Is the problem on your wlan0 which is the RT3070 chipset, isn't it?
Yep, the problem is with the wireless card on wlan0.
> * Confirm that wlan1 is your internal Raspberry wifi card
It sees only 2 networks (My home networks), wlan0 see 10+ networks. Is this method accurate enough? 
> * Which model of Raspberry pi do you have? I think internal wifi card can't be in monitor mode (not sure about the new Raspberry Pi model 4, I don't have yet one of them).
Raspberry Pi 4 B.

**Comment by OscarAkaElvis** [comment]
Ok, that confirms that on new Raspberry pi 4, internal card can be set in monitor mode, that's good.

So... It works for you flawlessly using wlan1 internal card, right? you can set monitor mode, scan, etc without any problem. Can you confirm it?

Regarding you RT3070 card... is an Alfa card? is a TP-Link card? Which brand and model is?

Can you do these tests?
1. Completely out of airgeddon, send a screenshot of the output of a iwconfig command.
2. Launch `airmon-ng start wlan1` and let's check what happens and which name it is renamed to. A screenshot could be nice.

**Comment by patrickteivas** [comment]
> So... It works for you flawlessly using wlan1 internal card, right? you can set monitor mode, scan, etc without any problem. Can you confirm it?

Yep, it`s working fine with internal card (Tried to scan networks in monitor mode).
> Regarding you RT3070 card... is an Alfa card? is a TP-Link card? Which brand and model is?

Alfa, model is AWUS036NH
> Can you do these tests?
> 
> 1. Completely out of airgeddon, send a screenshot of the output of a iwconfig command.

![MnDf0SV](https://user-images.githubusercontent.com/29047825/63647765-d788ca80-c72e-11e9-9610-e69195152e89.png)
> 2. Launch `airmon-ng start wlan1` and let's check what happens and which name it is renamed to. A screenshot could be nice.

Hm, something wrong with `airmon-ng start wlan1` (Screenshots provided).
![xpz3Sgf](https://user-images.githubusercontent.com/29047825/63647766-d9eb2480-c72e-11e9-86bb-c9a66ab83ff0.png)

**Comment by OscarAkaElvis** [comment]
Did you installed lspci command??? `apt install pciutils` could be enough for that. Do that and try again.

**Comment by patrickteivas** [comment]
> So... It works for you flawlessly using wlan1 internal card, right? you can set monitor mode, scan, etc without any problem. Can you confirm it?

Check now. Nope, it's not working fine. I put it in monitor mode and airgeddon shows no errors and also showing on top `Mode: Monitor`, but when I try to explore for targets (For example I took `Handshake tools menu`), it gives me `This interface wlan1 is not in monitor mode`

**Comment by patrickteivas** [comment]
`apt-get install pciutils` did the trick. Now all working fine. My bad.

**Comment by patrickteivas** [comment]
`apt-get install pciutils` did the trick. Now all working fine. My bad.

**Comment by OscarAkaElvis** [comment]
Awesome if it works! Can you help doing a last test? I saw the chipset is not printed ok on interface selection menu for the internal card. Two questions:

 - Is now printed ok since you installed pciutils package?
 - If answer is no to the last question, can you install ethtools package and try again? `apt install ethtools`, then try again and check again to see if chipset is well detected now.
 - It could be nice to have a screenshot of the interface selection menu with the card correctly detected in order to check how is printed to support that Raspbi 4 card too.

Thanks.

**Comment by patrickteivas** [comment]
Yes, of course! I'm glad to help you :).
After I installed `pciutils` package nothing changed, still `Chipset: Unknown`.
![6QQfFWA](https://user-images.githubusercontent.com/29047825/63653858-29efd880-c77b-11e9-8f99-7be0eb608d63.png)
Tried to install `ethtools` (`sudo apt update && sudo apt install ethtools`), but got `Unable to locate package ethtools`.
![D0F6kyF](https://user-images.githubusercontent.com/29047825/63653860-35430400-c77b-11e9-86d1-a823f3988a70.png)

**Comment by OscarAkaElvis** [comment]
sorry, ethtool without the final "s"

**Comment by patrickteivas** [comment]
`ethtool is already the newest version (1:4.19-1).`

**Comment by OscarAkaElvis** [comment]
wtf? ok... do you have installed package called usbutils? the command lsusb should be available. If you dont' have it, install it and try again.

If you already have the three packages pciutils, usbutils and ethtool installed... the chipset should be shown... if not, please, launch these commands and put the output:

`cat "/sys/class/net/wlan1/device/vendor"`
`cat "/sys/class/net/wlan1/device/device"`

Then, with that data, launch more stuff:

`lspci -d "${vendor_and_device}" | head -n 1` where ${vendor_and_device} should be replaced by the resulting values of the last commands separated by a colon ":". Something like "0x8086:0x100f" or similar. Please, put the outputs, thanks.

**Comment by patrickteivas** [comment]
> wtf? ok... do you have installed package called usbutils? the command lsusb should be available. If you dont' have it, install it and try again.

Nope, installed, does not helped.
> cat "/sys/class/net/wlan1/device/vendor"

`0x02d0`
> cat "/sys/class/net/wlan1/device/device"

`0xa9a6`
>lspci -d "0x02d0:0xa9a6" | head -n 1

Nothing.
![QQ63ymD](https://user-images.githubusercontent.com/29047825/63654840-5fe78980-c788-11e9-84ce-bf8be57ad29e.png)
![hT7kntm](https://user-images.githubusercontent.com/29047825/63654851-b654c800-c788-11e9-856a-29343eb6b9bc.png)

**Comment by OscarAkaElvis** [comment]
quite weird man... probably I'll need to buy a Raspberry Pi 4 to address this stuff 🙄 Thanks anyway for your help.

What is going to be done is to set lspci command (pciutils package) as essential tool to be validated at the initial checks to avoid issues like this again.

**Comment by patrickteivas** [comment]
No problem, I hope I did it right.

**Comment by OscarAkaElvis** [comment]
Don't worry, you did well. This is now fixed. For the next v9.22 lspci command will be checked as essential tool and it will be mandatory. Cheers! 🦁
