### ISSUE TITLE
handshake brute force option uppercase+lowercase+numbers

### ISSUE THREAD

**Issue by carlosnewmusic** [v1s1t0r1sh3r3/airgeddon#293]
#### Describe the feature or compatibility enhancement and involved versions if apply

What is the point in the brute force menu of handshake decryption there is no option of uppercase + lowercase + numbers when most of the default passwords on the routers carry passwords with that type of characters, and not with special characters or symbols
[![https://imgur.com/Rg9owAu.png](https://imgur.com/Rg9owAu.png)](https://imgur.com/Rg9owAu.png)

#### What are the benefits of adding this?

drastic reduction of time to decrypt handshake

**Comment by OscarAkaElvis** [comment]
Thanks for the suggestion, we'll take it in consideration for the future.

**Comment by OscarAkaElvis** [comment]
It seems future is going to be near future 😄

**Comment by v1s1t0r1sh3r3** [comment]
Done!

Closing. This enhancement will be released on v9.22
