### ISSUE TITLE
Need Tool UNBUFFER but cant find the too to install

### ISSUE THREAD

**Issue by Mikewins1** [v1s1t0r1sh3r3/airgeddon#294]
#### Is your question related to any concrete technology?

NO

#### Describe your question as detailed as possible

Everytime I run Airgeddon it searches for the tool UNBUFFER.  I can not find the tool anywhere to install so I can use all of airgeddons features.

**Comment by v1s1t0r1sh3r3** [comment]
It is indicated in the error message as "possible package name". Read carefully. It is included usually in expect package depending of your Linux distribution which you didn't indicated.

Anyway I can say that on new pretty close to release versuin 9.22 , that dependency will be removed.
