### ISSUE TITLE
ALFA Network AWUS036ACH not working

### ISSUE THREAD

**Issue by lornova** [v1s1t0r1sh3r3/airgeddon#296]
#### What is your airgeddon version?

9.21

#### What is your Linux O.S. and which version?

Kali Linux 2019.2 x64

#### Which is the chipset of your wireless card?

Realtek RTL8812AU (ALFA Network AWUS036ACH)

#### Describe the issue and the steps to reproduce it

```
**************************** Interface selection ****************************** 
Select an interface to work with: 
--------- 
1.  eth0  // Chipset: Intel Corporation 82545EM
2.  wlan0 // 2.4Ghz, 5Ghz // Chipset: Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter
--------- 
***************************** airgeddon main menu ****************************** 
There is a problem with the selected interface. Redirecting you to script exit 
Press [Enter] key to continue...

*********************************** Exiting ************************************ 
Exiting airgeddon script v9.21 - See you soon! :) 

Checking if cleaning/restoring tasks are needed... 
No tasks to perform on exit 

```
$ iwconfig
wlan0     IEEE 802.11b  ESSID:""  Nickname:"<WIFI@REALTEK>"
          Mode:Monitor  Frequency:2.437 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality=0/100  Signal level=-100 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

I've used both v5.2.20 and v5.3.4 of rtl8812au with the same results.

**Comment by v1s1t0r1sh3r3** [comment]
Closing due constant duplicate. Read the wiki. That card is always generating problems.

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by OscarAkaElvis** [comment]
Ding ding ding!!! your dreams come true: https://github.com/OscarAkaElvis/airgeddon_realtek_chipset_fixer
