### ISSUE TITLE
xterm not an essential tool if tmux is used

### ISSUE THREAD

**Issue by Zamanry** [v1s1t0r1sh3r3/airgeddon#297]
#### Describe the feature or compatibility enhancement and involved versions if apply

xterm is not a necessary package installation if tmux is used for window handling. This is under the assumption that xterm is not used at all if tmux is used for window handling. I would check for xterm or tmux to be installed and cross-checked in the .airgeddonrc for what package wants to be used for the window handling.

#### What are the benefits of adding this?

One less package is necessary for user installation. Less installation requirements, more system security as one less package is installed. Additionally, this would also inform more users of the option to use tmux over xterm for window handling.

**Comment by OscarAkaElvis** [comment]
What the hell are you talking about? It is exactly as airgeddon is working now. You can set either xterm or tmux in .airgeddonrc file and depending of what you select, the validation check is done only over it. I mean, if you set tmux at .airgeddonrc file setting it at `AIRGEDDON_WINDOWS_HANDLING` option, only tmux is checked and xterm is not needed and viceversa... so what you are proposing is already done. Closing.

**Comment by Zamanry** [comment]
![airgeddonrc](https://user-images.githubusercontent.com/28152647/64132328-148f3580-cd9d-11e9-8cbd-8f23fee57b87.png)
![Installed-Packages](https://user-images.githubusercontent.com/28152647/64132329-148f3580-cd9d-11e9-8842-02bf265adc7a.png)
![Not-Able-To-Continue](https://user-images.githubusercontent.com/28152647/64132330-1527cc00-cd9d-11e9-85df-fda0ae5feb41.png)

The function that searches for essential tools only searches for xterm. Even if you have tmux selected. As you can see in Installed-Packages.png, I do not have xterm installed, but I do have tmux installed. Then in airgeddonrc.png, I have tmux selected for window handling. Then when I run airgeddon (Not-Able-To-Continue.png), I cannot continue as the script requires xterm even though tmux is selected and installed. Yes, if I install xterm, it will work, but it is not used as tmux is.

I am not disputing the ability to change between xterm and tmux; I am merely pointing out the essential tool function does not check for tmux over xterm even if tmux is being used. I hope this clarifies my enhancement idea.

**Comment by OscarAkaElvis** [comment]
Really? omg I thought I've seen all... but this....

Check carefully your own screenshot. I'll put there for you a little sign to mark what is wrong:

![image](https://user-images.githubusercontent.com/5803348/64134244-7de26900-cddc-11e9-8341-4116b26f8dcd.png)

If airgeddon is not finding a variable (like in your case because with that strange chars there, the var name is different), it uses the default... so xterm.

Locking.
