### ISSUE TITLE
(Evil Twin attack) Captive portal bug

### ISSUE THREAD

**Issue by alari73512** [v1s1t0r1sh3r3/airgeddon#298]
Hei guys! the problem is that when i use the evil twin attack with captive portal, the captive portal pops up on my phone when im connecting to the wifi, but....... when i connect to the same  network with my pc, it doesnt pop up.

any fixes?
im sorry if this issue has already been solved.

**Comment by OscarAkaElvis** [comment]
It depends of your browser, the configuration, etc. You didn't filled up the issue template, so the issue is closed because of it.
