### ISSUE TITLE
shuf: invalid input range '-1'

### ISSUE THREAD

**Issue by patrickteivas** [v1s1t0r1sh3r3/airgeddon#302]
#### What is your airgeddon version?

9.22

#### What is your Linux O.S. and which version?

Kali Linux RaspberryPi 2019.2a 32bit

#### Which is the chipset of your wireless card?

Ralink Technology, Corp. RT2070/RT3070

#### Describe the issue and the steps to reproduce it

`shuf: invalid input range '-1'` error when target selected in `Attack for Handshake` menu.
![2019-09-09-185805_1824x984_scrot](https://user-images.githubusercontent.com/29047825/64712041-4140fc80-d4c3-11e9-82aa-0f8a3cba7887.png)

**Comment by OscarAkaElvis** [comment]
Silly error... is a little bug due a var name refactor. Thanks for reporting.

**Comment by OscarAkaElvis** [comment]
Fixed now! the patch will be available for next v9.23 . If you want to test it, just download the version from dev branch in this way: `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon.git`

Closing.
