### ISSUE TITLE
There is a problem with the selected interface. Redirecting you to script exit 

### ISSUE THREAD

**Issue by ghostmarktim** [v1s1t0r1sh3r3/airgeddon#305]
#### What is your airgeddon version?

Version 9.22

#### What is your Linux O.S. and which version?

Parrot security 4.7

#### Which is the chipset of your wireless card?

Alfa AWUS036ACH

#### Describe the issue and the steps to reproduce it

When runing airgeddon script, after choosing the interface it show this error:
`There is a problem with the selected interface. Redirecting you to script exit `
Then airgeddon exit after clicking [Enter]

The interface is working fine, and I can connect to the internet while using it in managed mode.
Also while I use it for `airodumb-ng` and `aircrack-ng`... it works with no problems in monitor mode. 

iwconfig output for the concerened interface:

`wlan1    IEEE 802.11b  ESSID:""  Nickname:"<WIFI@REALTEK>"
               Mode:Monitor  Frequency:2.457 GHz  Access Point: Not-Associated
               Sensitivity:0/0
               Retry:off   RTS thr:off   Fragment thr:off
               Power Management:off
               Link Quality=0/100  Signal level=-100 dBm  Noise level=0 dBm
               Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
               Tx excessive retries:0  Invalid misc:0   Missed beacon:0
`

Please Advise ASAP
Thank you..

**Comment by OscarAkaElvis** [comment]
Always the same problem with this damn chipset... please, search through issues before opening an issue. This is a duplicated issue:
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/304
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/296
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/100

Also you could read the Wiki about the compatible cards: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
