### ISSUE TITLE
dhcpd: error: no such option: -d

### ISSUE THREAD

**Issue by carlospolop** [v1s1t0r1sh3r3/airgeddon#315]
#### What is your airgeddon version?

airgeddon script v9.23

#### What is your Linux O.S. and which version?

Linux kali 5.2.0-kali2-amd64 #1 SMP Debian 5.2.9-2kali1 (2019-08-22) x86_64 GNU/Linux

Kali-Linux-2019.3-vmware-amd64

#### Describe the issue and the steps to reproduce it

It seems that there is a problem with the dhcpd packet inside kali.

If you try to create an Evil Twin, the dhcpd command will fail with the following message:
*"dhcpd: error: no such options: -d"*

![image](https://user-images.githubusercontent.com/17181413/67165895-63f7e800-f382-11e9-96bb-690438f39e04.png)

**Comment by OscarAkaElvis** [comment]
Are you sure you are using the correct dhcpd command? I updated my Kali to the latest right now (`apt update && apt dist-upgrade`) and it worked like a charm for me. Probably is something wrong on your side.

Remember that dhcpd command is from isc-dhcp-server package for Kali, and is not from dhcpd package or from any other. Uninstall dhcp related packages and install it `apt install isc-dhcp-server`. Tell us if worked for you, and remember that you can join Discord channel to get helped faster next time. Invitation link is on Contact section at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Contact

Anyway, here is the link: https://discord.gg/sQ9dgt9

**Comment by carlospolop** [comment]
Thank you, I needed to:
```

**Comment by carlospolop** [comment]
Thank you, 
I needed to:
```bash
mv /usr/local/bin/dhcpd /usr/local/bin/dhcpd.old
apt install isc-dhcp-server
```
And now it is working properly.
Thanks also for the tool, it is great.
