### ISSUE TITLE
Multiple Simultaneous Rogue APs

### ISSUE THREAD

**Issue by zero77** [v1s1t0r1sh3r3/airgeddon#318]
#### Describe the feature or compatibility enhancement and involved versions if apply

Can you please add support to create more than one rogue ap at once.

#### What are the benefits of adding this?

When you are working with more than one ap it would be much quicker to have multiple rogue APs at once instead of testing one after the other.
Particularly the captive portal as it can take time.

**Comment by OscarAkaElvis** [comment]
Thanks for your suggestion. For now the rogue APs are created one by one. Bear in mind that to do something like that, more wireless adapters will be needed. One per channel to create AP. Closing.
