### ISSUE TITLE
'Graphical X window system has not been detected' in SSH

### ISSUE THREAD

**Issue by LucaSkywaIker** [v1s1t0r1sh3r3/airgeddon#319]
#### What is your airgeddon version?
9.23
#### What is your Linux O.S. and which version?
Kali Linux for RPi
#### Which is the chipset of your wireless card?
AR9271
#### Describe the issue and the steps to reproduce it
I am trying to install airgeddon on my pi via SSH, however I am met with the error "A graphical X window system has not been detected." How should I go forward? I saw some said I should install x11 utils but I already have them

**Comment by OscarAkaElvis** [comment]
That's the completely normal behavior. You can't access to X Windows system from a remote ssh session. But this is not only for airgeddon, it's for anything.

Anyway, airgeddon has the workaround you need. In order to work on remote ssh sessions or on headless systems, you can change the `AIRGEDDON_WINDOWS_HANDLING` option to use "tmux" instead of xterm. You can do it from the options menu or editing the options file. More info here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

**Comment by deadman101** [comment]
hi I'm getting  the same error and I'm using VNC on a raspberry pie its say  basically say that the graphical x window hasn't being detected  plz help

**Comment by OscarAkaElvis** [comment]
You have here the answer, enable tmux instead of xterm, or maybe you just need to launch `xhost +` command before launching airgeddon.

**Comment by deadman101** [comment]
Tried using tmux still getting the error message let me show the error
message im some what of a newbie plz help

**Comment by xpz3** [comment]
Tmux doesn't need xwindow system. You might be doing it wrong. Please join the airgeddon discord channel for help on how to run airgeddon via tmux
https://discord.gg/sQ9dgt9

**Comment by fate182** [comment]
You need to pass enviroment DISPLAY to root for xhost. If you are root, make

`xhost +SI:localuser:root`

or just use -E flag with sudo:

`sudo -E ./airgeddon.sh`

**Comment by devblaze** [comment]
> You have here the answer, enable tmux instead of xterm, or maybe you just need to launch `xhost +` command before launching airgeddon.

What's the default dir for airgeddon on Kali?

**Comment by v1s1t0r1sh3r3** [comment]
If you installed it by apt. It is /usr/share/airgeddon

Please, don't ask questions in non-related old issues. Join discord to ask stuff. Check invitation link above.
