### ISSUE TITLE
Unable to detect handhsake in non default path

### ISSUE THREAD

**Issue by kcdtv** [v1s1t0r1sh3r3/airgeddon#32]
I am using the new menue "evil twin"
To grab the handshake i use airgeddon itself
The handshake is correctly captured
I indicate a path in a non root directory and the handshake is correctly saved (handshake-01.cap) 
Unfortunately airegeddon does not detect it properly at this stage.
![seleccion_550](https://cloud.githubusercontent.com/assets/7338484/19397670/18fce578-9249-11e6-94da-f4468237bb3a.png)
As it named it by itself i deduce that airgeddon should be able to handle it and that entering the path and not the absolute path is enough.
Cheers

**Comment by v1s1t0r1sh3r3** [comment]
It seems airgeddon is searching for /home/kcdtv/handshake/handshake-00:C0:CA:78:B1:37.cap

I will check. Thanks for the report.

**Comment by kcdtv** [comment]
so fast--- 
okay, i got the answer, airgeddon is looking for the path without the file. 
It didn't grab the name it generated: 
![seleccion_551](https://cloud.githubusercontent.com/assets/7338484/19398035/e84ea130-924a-11e6-9f84-e83fdcb0693c.png)
you may want to stronger this or you can precise that the path is absolute...
cheers

**Comment by v1s1t0r1sh3r3** [comment]
Fixed. 4.31 version has de fix for this (commit fd45b94385187fae7a73ecf4eae09d2d9565a59e). I left the issue open, it will be closed automatically when the commit arrive to master.

**Comment by faridd1** [comment]
help

![IMG_9722](https://github.com/user-attachments/assets/5e757bb3-f7bc-49a6-8043-203043a0a522)

**Comment by OscarAkaElvis** [comment]
Please, don't use old issues to put your queries. If you want support, the best option is to join discord. You can find invitation link on our Wiki (contact section).

Anyway, you didn't put any data... that way is really hard to help somebody. airgeddon version would help. I think there is a bug fixed about paths on the last v11.31 (not released yet, probably next week). So you can get dev version and test `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon`. But watching the screenshot, the most probably thing that is happening is that the file is not existing or you don't have permissions to read it. Try to use tab key to auto complete dirs while typing the path, that helps to be sure that the file is exsisting and is not mistyped. So sumarizing:

- Be sure that the file exist, try using tab key
- Try v11.31 dev version. Maybe the fixed bug related to some paths is affecting to you, not sure.
- If your problem still persist, join discord. And please, after joining, provide there as much data as possible! OS, airgeddon version and so on.
