### ISSUE TITLE
Automatic connection to captive portal on devices

### ISSUE THREAD

**Issue by Hunter310** [v1s1t0r1sh3r3/airgeddon#322]
Good morning, it is for a doubt about the captive portal it is usually created and works but I have seen that the devices does not connect to automatically as in open public network does although its connection is manual to enter the captive portal which method used so that be automatic connection to the open network created.

**Comment by OscarAkaElvis** [comment]
Please, follow the instructions to create an issue. Read the contributing policy. Thanks.
