### ISSUE TITLE
Evil Twin attacks with airbase-ng instead of hostapd

### ISSUE THREAD

**Issue by katzurki** [v1s1t0r1sh3r3/airgeddon#323]
Hostapd won't work on WiFi adapters without AP capability, but it's still possible to host an evil twin AP on those using airbase-ng. 

I tried to run airbase-ng concurrently with airgeddon, and the solution works after a fashion (I see dhcpd handing out IP addresses, but no routing / ip forwarding takes place; and I had to butcher airgeddon's safety checks).

**Comment by OscarAkaElvis** [comment]
Please, follow the instructions to create an issue. Read the contributing policy. Thanks.
