### ISSUE TITLE
graphical X windows system not detected

### ISSUE THREAD

**Issue by MohammadBinAftab** [v1s1t0r1sh3r3/airgeddon#325]
What is your airgeddon version?

v10.0
What is your Linux O.S. ?

 Kali Linux WSL.

Describe the issue and the steps to reproduce it

I execute the file and Airgeddon loads up smoothly. I typed sudo bash airgeddon.sh and then it shows me Not detected Graphical X windows system. I already tried xhost + bash airgeddon.sh.
then it shows unable to open display.

I recorded a video for your help: https://youtu.be/PJXpMgqv--Q

**Comment by OscarAkaElvis** [comment]
Sorry, but Windows Subsystems are not supported as you can see at our Wiki on "Known imcompatibilitiies" section:

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Known-Incompatibilities

Check last line. Closing.
