### ISSUE TITLE
"/" Is not recognized.

### ISSUE THREAD

**Issue by BlueBird-BH** [v1s1t0r1sh3r3/airgeddon#326]
**What is your airgeddon version?** 

10.0

**What is your Linux O.S. and which version?** 

Kali Linux 2019.4

**Which is the chipset of your wireless card?** 

7265NGN.NVW

**Describe the issue and the steps to reproduce it**

I was using the Airgeddon Evil Twin option to get the password of a WiFi network.

Everything worked correctly until the moment when the victim (which was me but on another device) had to enter the network password. 

At the time of receiving the password, it seemed that the tool didn't recognize the "/" sign, so it gave the password incorrect. 

I would like to know how to solve this to avoid problems in the future.

**Comment by OscarAkaElvis** [comment]
Hi, this is absolutelly intentional. Duplicated:
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/184
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/143

Closing.

**Comment by BlueBird-BH** [comment]
@OscarAkaElvis Oh, sorry for being a duplicate. By the way, thanks for answering.

**Comment by KeyofBlueS** [comment]
Hi! Could i suggest to insert an option to not filter all of that special chars, at your own risk, with a big warning that You could be hacked?
Or even better, there is absolutely no way to temporarly block all commands (just inside the airgeddon's terminals) but those required to setting up the captive portal? For example creating a symlink to all of those required executables in, let's say, /tmp/airgeddon/bin/ and then setting the path with PATH=/tmp/airgeddon/bin (assuming that the attacker cannot change back PATH)
Do You think is it possible?

**Comment by OscarAkaElvis** [comment]
This sounds to me like a customization to be done as a plugin. Did you know about the new plugins system feature? It's exactly for this kind of things. Check it out: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20System

That could be really easy to do, just modifying a function to remove the special chars filtering.
