### ISSUE TITLE
MiTM attack primary AP disable facility

### ISSUE THREAD

**Issue by saintofinternet** [v1s1t0r1sh3r3/airgeddon#329]
#### Describe the feature or compatibility enhancement and involved versions if apply

when carrying out the MiTM attack using Evil Twin the primary AP which is being targeted stays up during the entire period. 

due to which there are 2 identical AP's visible with one having a lock symbol and the other (created by Airgeddon) showing the same name but open (without key)

this causes the clients to be wary of something being wrong when there are 2 AP with same name showing up 

are there any ways we can block the original AP name for the moment of the attack period and make it disappear from the connection list of available wireless AP till the client connects to the MiTM AP and tries enters the password ultimately capturing the password.

#### What are the benefits of adding this?

It will make the attack look genuine when there is only one AP visible with the name that is being targeted.

**Comment by OscarAkaElvis** [comment]
Hahaha, sorry buddy, but I think that you want is not possible. The deauth packets can bring down clients from a network but there is no way to make a network to dissapear, at least with standard wifi hardware. Probably that could be done with some kind of jamming and special hardware which is completely out of airgeddons scope. You can't avoid a device to cast its airwaves.

Evil Twin has a "social engineering" component and the user needs to be "tricked".

Please, before ask this kind of stuff I suggest to you to read a little bit about how wifi works. Try to not ask for impossible things.

**Comment by saintofinternet** [comment]
:-) thanks for the reply.
