### ISSUE TITLE
wait_for_process

### ISSUE THREAD

**Issue by jepunband** [v1s1t0r1sh3r3/airgeddon#330]
![20191214_145538](https://user-images.githubusercontent.com/46950575/70844968-02d12a00-1e84-11ea-9edb-5367d8c096d5.jpg)

**Comment by OscarAkaElvis** [comment]
On screenshot I can see debug mode enabled and the name of the functions... ok, and what that means? should we divinate what is happening?

Closing due lack of information, templated wasn't filled correctly.

**Comment by jepunband** [comment]
Sorry, not sure y the template i filled not shown.. secondly i did not run it in debug mode.

**Comment by OscarAkaElvis** [comment]
You are running debug mode. That is the reason of the lines and the name of the functions shown. Please, read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

**Comment by jepunband** [comment]
This is my first install , i did not edit any files to begin with.
![20191214_164740](https://user-images.githubusercontent.com/46950575/70846187-be4c8b00-1e91-11ea-8dd0-9a9ca09a02ec.jpg)

**Comment by OscarAkaElvis** [comment]
Now I should ask, what is your Linux? what is your airgeddon version? how did you installed airgeddon? git clone? .deb package? how are you launching it? etc etc... This is exactly the kind of things I want to avoid and the reason of the template existence. Please, join the [Discord channel](https://discord.gg/sQ9dgt9) and ask there, I'm going to lock this.
