### ISSUE TITLE
Hello sir please help me, everything is working fine  the airgeddon but when i start the "evil twin capative portal" all tabs works fine but the ap tab shows error like this :-configuration file: /tmp/ag.hostapd.conf   nl80211: could not configure driver mode nl80211: deinit ifname=wlan0 disabled_11b_rates=0 nl80211 driver initialization failed . wlan0:interface state  uninitialized->disabled wlan0:AP-disabled wlan0:CTL-EVENT-TERMINATING, hostapd_free_hapd_data: interface wlan0 wasn't'started .please help me i am using it in kali linux installed in desktop wiyh only one wireless adapter no internal adapters. 

### ISSUE THREAD

**Issue by supertinku** [v1s1t0r1sh3r3/airgeddon#331]

**Comment by OscarAkaElvis** [comment]
Bad format of issue... not filled up the template. Contact on Discord for this. Closing.

**Comment by Aditya50854** [comment]
, everything is working fine the airgeddon but when i start the "evil twin capative portal" all tabs works fine but the ap tab shows error like this :-configuration file: /tmp/ag.hostapd.conf nl80211: could not configure driver mode nl80211: deinit ifname=wlan0 disabled_11b_rates=0 nl80211 driver initialization failed . wlan0:interface state uninitialized->disabled wlan0:AP-disabled wlan0:CTL-EVENT-TERMINATING, hostapd_free_hapd_data: interface wlan0 wasn't'started .please help me i am using it in kali linux installed in desktop wiyh only one wireless adapter no internal adapters. 
 #331
                                                                           *     SAME PROBLEM      *   (AshutoshVohra)

**Comment by OscarAkaElvis** [comment]
You need to learn first how to ask.

You can't write on an old already closed issue. A new one should be opened.

You shouldn't white long text on title. Title must be a summary. Locking.
