### ISSUE TITLE
airgeddon wont scan for wifi APs even though the card is in monitor mode

### ISSUE THREAD

**Issue by frequencypy** [v1s1t0r1sh3r3/airgeddon#335]
Hello community.I am on the 4.19.0 kali linux kernel and using a TL-WN722N V2 adapter.I got the adapter to work and packet injection works just fine. I  can set it to monitor mode and scan for wifi networks etc.I also have installed the plugin you released in the script's folder because there was an error using the adapter in the first place in the script.After that,the script can see that my card  is in monitor mode but it will not continue to scan for APs.I will paste the output bellow

<pre><font color="#4E9A06">**************************** Exploring for targets ***************************** </font>
<font color="#8AE234"><b>Exploring for targets option chosen (monitor mode needed) </b></font>

<font color="#FCE94F"><b>Selected interface wlan0 is in monitor mode. Exploration can be performed </b></font>

<font color="#729FCF"><b>It seems this interface was parametrized before. It&apos;s not necessary to check again </b></font>

<font color="#FCE94F"><b>WPS filter enabled in scan. When started, press [Ctrl+C] to stop... </b></font>
Press [Enter] key to continue...

<font color="#EF2929"><b>An unexpected error occurred, redirecting to the menu</b></font></pre>
``

Any ideas? Thanks!

**Comment by OscarAkaElvis** [comment]
I'm going to close this due an issue creation policy violation. You didn't fill the issue template with all the needed info. We need more data, airgeddon version, chipset (not only the card model), etc etc... Two recommendations anyway:

1. Try the new 10.01 version which is on dev branch. It no needs the plugin anymore
2. Join discord channel to discuss deeply any issue. Invitation link is in wiki contact section.
