### ISSUE TITLE
AIRGEDDON TARGETS

### ISSUE THREAD

**Issue by JellyWorld07** [v1s1t0r1sh3r3/airgeddon#336]
hy everyone, i'm using airgeddon, but when i run "Explore for targets" i cant find any network.
I'm using a digitus dn-7045.
Kali linux is installed on a raspberry pi 4 model b 4gb of ram.
There are no errors in required and optional tools.
Is possible that my digitus dn-7045 is non compatible with kali?
In any case i bought from amazon an Alfa network adapter.

**Comment by OscarAkaElvis** [comment]
Hi, I saw and I've already answered to you on the other issue. Please, don't spam us. In addition, you didn't fill the issue template with all the needed data (chipset is not there, airgeddon version is not there, etc).  Closing due issue creation policy violation. Contact us on Discord.
