### ISSUE TITLE
deauthentification not working

### ISSUE THREAD

**Issue by dragos-olaru** [v1s1t0r1sh3r3/airgeddon#338]
Waiting for beacon frame (BSSID: ...................) on channel X

What to do?

**Comment by OscarAkaElvis** [comment]
Maybe you can start opening an issue in the correct way. Filling the issue template correctly, giving to us needed data (airgeddon version, O.S. chipset of your card, adding a screenshot, telling which options are you using on menus, etc). Closing due lack of information.

Please consider to join Discord channel to discuss any problem. Invitation link is on contact wiki section.
