### ISSUE TITLE
Ok, this isn't a issue report. It's more like a help request.

### ISSUE THREAD

**Issue by tiagojpavan** [v1s1t0r1sh3r3/airgeddon#340]
#### Is your question related to any concrete technology?
Android Termux terminal emulator with Kali Nethunter

#### Describe your question as detailed as possible

Ok, I've been trying to make Airgeddon works on termux for some days without success (lots of requirements are almost impossible to fill with termux repos) so I start to try using Kali Nethunter, and almost get there, but I find a few problems that I don't get ways to manage. 

One: trying run Airgeddon with tmux give me a error about proc. The message says that proc isn't loaded at startup, and a command are given to try to start proc mount manually, but don't work.
Two: without install xterm I manage to run Airgeddon, but it close itself because there's no xterm 😅. When I install xterm, I get a error massage that says there's no graphical interface installed, or it isn't running, and I don't get it to run manually.
Three: script ask me to install hashcat, but on Nethunter repos there's only hashcat-data to install, so I've installed it but Airgeddon still says there's no hashcat installed. 

Ok,I know some of this isn't directly related to Airgeddon itself, but I think "Who is the best one to give me some tips about what can I possibly try to do to solve all this? Airgeddon Creator, of course."

So here I am.😅

If needed I make some screenshots of the errors to update this 'issue'.😅

**Comment by tiagojpavan** [comment]
![Capture+_2020-02-02-09-47-34](https://user-images.githubusercontent.com/70831/73609160-5537e880-45a1-11ea-8bdd-13504dcfd4be.png)
This one is with tmux

![Capture+_2020-02-02-09-49-09](https://user-images.githubusercontent.com/70831/73609171-6bde3f80-45a1-11ea-9f91-5df9271eeeb1.png)
And this one is with xterm

**Comment by OscarAkaElvis** [comment]
Yeah, did you read the wiki about Nethunter? https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Kali%20Nethunter

After install tmux you need to set it on the options file (.airgeddonrc) as a default AIRGEDDON_WINDOWS_HANDLING

I'm not sure yet if somebody installed hashcat on an arm system. I think is not an easy task to do. At least, I didn't achieve it. Anyway, it makes no sense... no cpu power there to work with hashcat.

Please, for community support join to Discord channel: https://discord.gg/sQ9dgt9

**Comment by tiagojpavan** [comment]
> Yeah, did you read the wiki about Nethunter? https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Kali%20Nethunter

Yup, I read ALL the wiki. 😅
> 
> After install tmux you need to set it on the options file (.airgeddonrc) as a default AIRGEDDON_WINDOWS_HANDLING

Yup again. I do this and get a error about proc mounting anyway. 
> 
> I'm not sure yet if somebody installed hashcat on an arm system. I think is not an easy task to do. At least, I didn't achieve it. Anyway, it makes no sense... no cpu power there to work with hashcat.

Well, I try it because my phone has a Mediatek processor with 8 cores at 2ghz each, so I think maybe it get sufficient power to run hashcat. The problem in this case is that on the Nethunter repo there's no 'hashcat' package, only a package named 'hashcat-data', and this one isn't recognized by Airgeddon. 
> 
> Please, for community support join to Discord channel: https://discord.gg/sQ9dgt9

Well, I'm a little stubborn, so I'll keep trying. Thanks for the answer. 😉👍

**Comment by OscarAkaElvis** [comment]
As I said, for hashcat probably you'll need to compile it because there is no precompiled hashcat package for ARM. Try asking to hashcat staff.

**Comment by tiagojpavan** [comment]
> As I said, for hashcat probably you'll need to compile it because there is no precompiled hashcat package for ARM. Try asking to hashcat staff.

Ahh, ok! Now I get it. 😅
Thanks for the tip. 😉👍

**Comment by xpz3** [comment]
If your sole purpose is to get airgeddon running on android, then try linux deploy app and install kali. I'm using it on my phone. Airgeddon works with xterm (vnc) and tmux. 

You should have a supported custom kernel with usb wifi drivers though..
