### ISSUE TITLE
Add Support Manjaro

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [v1s1t0r1sh3r3/airgeddon#341]
#### What are the benefits of adding this?
**Manjaro** is a awesome distro based on **Arch Linux**. Besides others distros this should be also added

**Comment by OscarAkaElvis** [comment]
If it is arch based, it should work. Is not working for you?

Or do you mean just to add the "Manjaro" and the detection as a separated OS? but anyway I think it should work.

Ok, we'll take it into consideration. Thanks. Closing.

**Comment by OscarAkaElvis** [comment]
Downloaded Manjaro iso and testing it in a VM.

**Comment by OscarAkaElvis** [comment]
Added for the next release: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/a23ac16ee037ca949b3ab103bced1503291fb120

**Comment by BL4CKH47H4CK3R** [comment]
> Downloaded Manjaro iso and testing it in a VM.
It was unable to start the monitor mode because of the unknown

**Comment by OscarAkaElvis** [comment]
Not sure to understand what you mean... the difference of being detected as Manjaro or "Unknown Linux" is not relevant. Even in "Unknown Linux" it should work. If it doesn't work for you, it has nothing to mess with the Linux OS detection. Probably you have other kind of problem related to your card, or your driver. It worked for me using a standard Alfa with Atheros chipset in "Unknown Linux" and after the commit (you can test it git cloning the dev branch) it also worked for me with Manjaro detected.
