### ISSUE TITLE
exploring for targets "an unexpected error occurred"

### ISSUE THREAD

**Issue by sabittan** [v1s1t0r1sh3r3/airgeddon#342]
So I downloaded all the necessary packages, everything is up to date. My chipset is RealkTek 8812au. When I go to WPS attack, I put my wlan0 in monitor mode and then try to explore for targets and gives "unexpected error occurred, redirecting to the menu" screenshot below. Everything is on the latest version. 
![Screen Shot 2020-02-07 at 02 37 28](https://user-images.githubusercontent.com/60765304/73996254-07c9cb80-4953-11ea-8029-f6e9cfdbf493.png)

**Comment by OscarAkaElvis** [comment]
Bad news for you... this is not related to airgeddon. That is a problem of the driver for your kernel. You can try to use an older kernel with an older driver version. If I remember well, kernels 4.x with driver 5.2.2.0 worked well on WPS but after that, problems all the time. Try to ask to the driver developers.

Closing.

Closing.
