### ISSUE TITLE
Add 3WiFi Database Analysis

### ISSUE THREAD

**Issue by BL4CKH47H4CK3R** [v1s1t0r1sh3r3/airgeddon#343]
#### What are the benefits of adding this?

3WiFi is great database for finding a massive list of already compromised routers.

A project of RouterScan stabilised by my Friend Slanislav Motylkov
Here you go  [3WiFi Database](https://3wifi.stascorp.com)

You can add **3WiFi Database Analysis** options for fetching using various parameters like MAC.

Greetings, **BL4CKH47H4CK3R** :v:

**Comment by OscarAkaElvis** [comment]
Sorry but in many countries that is not legal in many countries, at least in mine is not legal. airgeddon is for use on whitehat purposes and we can't add support for that. To show personal data like passwords and other kind of similar stuff of compromised is not a good idea unless you want to have nice holidays in jail.

If you don't mind about this, you can develop a plugin to do that 😄
