### ISSUE TITLE
When starting search for WPS, "Unexpected Error..."

### ISSUE THREAD

**Issue by Sqxxe** [v1s1t0r1sh3r3/airgeddon#344]
#### What is your airgeddon version?

10.01 (Latest)

#### What is your Linux O.S. and which version?

Kali Linux 2020.1 Kernel 5.4.0

#### Which is the chipset of your wireless card?

I have a TL-WN722N and the chipset is rtl8188eus

#### Describe the issue and the steps to reproduce it

So card is in monitor mode and it is working in monitor mode, even Airgeddon says it is in monitor mode however when I want to search for WPS targets it simply starts to search for 5 ms then crashes. Then I am left with Airgeddon saying "An unexpected error occurred, redirecting to the menu."

**Comment by xpz3** [comment]
Unfortunately your chipset isn't compatible with airgeddon. TP Link TL-WN722N V1 having ar721 chipset is the compatible one. For more compatible cards see the following wiki page.
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by OscarAkaElvis** [comment]
Yeah, read this other issue: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/342
