### ISSUE TITLE
Airgeddon wps attacks menu; exploring for wps targets empty

### ISSUE THREAD

**Issue by Staylejkxd** [v1s1t0r1sh3r3/airgeddon#350]
Hello, i have an issue with Airgeddon, the installation seem's fine i dont have any optional tools missing or something like that, the only thing which bug is on the " Wps attacks menu " more precise when i use the option (4) to explore for wps targets, the window that pop-up don't find anything, but i remember previously i used Kali linux(Live) not installed with the VirtualMachine, it was working fine.( And if i go into the option to capture handshake, and then explore for targets, the explorer for targets works. )
![Screenshot_2020-03-14_18-13-25](https://user-images.githubusercontent.com/62189950/76691287-b8e11700-661f-11ea-8b0c-4526845879cd.png)

**Comment by xpz3** [comment]
Without filling in the issue template, we hardly know your setup like kali version, wifi chipset etc. Join discord channel and ask there with all relevant information regarding this.
https://discord.gg/sQ9dgt9
