### ISSUE TITLE
language_strings: command not found

### ISSUE THREAD

**Issue by Kduhh** [v1s1t0r1sh3r3/airgeddon#354]
I try change language in options but not work
![IMG_20200321_121437](https://user-images.githubusercontent.com/22018476/77230903-04d71300-6b6e-11ea-82c8-9f11aac12d99.jpg)

**Comment by OscarAkaElvis** [comment]
Closing due the lack of information. Please, read the issue creation policy. You must fill all the needed data... version, etc.... in any case. Clone the repo entirely again, it seems you messed up something.
