### ISSUE TITLE
Portal page in arabic

### ISSUE THREAD

**Issue by mohamedmorsi1993** [v1s1t0r1sh3r3/airgeddon#356]
And i can help with translation
If you send me the portal page source cod iwill translate it

**Comment by OscarAkaElvis** [comment]
Sorry but bash has no official support for RTL (Right to Left) languages, so for now arabic is discarded as a possible language to translate airgeddon. Thanks anyway. Closing.

**Comment by OscarAkaElvis** [comment]
This was reopened because finally, arabic language will be added even in LTR instead of RTL. It will be available for the next v10.30.

**Comment by mohamedmorsi1993** [comment]
Good.

**Comment by OscarAkaElvis** [comment]
If you want to check the progress (not finished yet), you can download from arabic branch `git clone -b arabic https://github.com/v1s1t0r1sh3r3/airgeddon`.

Cheers!

**Comment by OscarAkaElvis** [comment]
v10.30 released. Closing.
