### ISSUE TITLE
Sslstrip

### ISSUE THREAD

**Issue by Misko2468** [v1s1t0r1sh3r3/airgeddon#357]
I got all of the requirements installed easilly but cant get sslstrip,
apt-get install doesn't work, what should I do?

**Comment by OscarAkaElvis** [comment]
In first place, you didn't fill the issue creation template on which your operating system, your airgeddon version, etc must be written down. What do you expect now? our team asking you that basic questions that you should put directly? please, don't waste our time.

Read documentation, read wiki, join discord.

Closing due issue creation policy violation.
