### ISSUE TITLE
Erro Desconhecido

### ISSUE THREAD

**Issue by luiscpmotta** [v1s1t0r1sh3r3/airgeddon#360]
#### What is your airgeddon version?
v10.01

#### What is your Linux O.S. and which version?
Parrot 4.8

#### Which is the chipset of your wireless card?

Chipset: Qualcomm Atheros Communications AR9271 802.11n

#### Describe the issue and the steps to reproduce it

Após colocar a plana no modo monitor e buscar os alvos dá esse erro. Já havia testado no KALI e roda bem....

Selecione uma opção de busca para encontrar objetivos (modo monitor obrigatório) 

A interface selecionada wlan1mon está no modo monitor. A verificação pode ser realizada 

Esta interface já foi configurada anteriormente. Não é necessário verificar novamente 

Filtro WPS ativo na busca de redes wifi. Uma vez iniciado, pressione [Ctrl+C] para pará-lo... 
Pressione a tecla [Enter] para continuar...

Ocorreu um erro inesperado, retornando ao menu

**Comment by OscarAkaElvis** [comment]
Sorry but we only accept issues written in english as the issue creation policy said. Closing.
