### ISSUE TITLE
could you incorporate key reinstallation attack in airgeddon

### ISSUE THREAD

**Issue by RadhaKrishn4** [v1s1t0r1sh3r3/airgeddon#364]
#### Describe the feature or compatibility enhancement and involved versions if apply

Krack or key reinstallation attack for wpa2 would be great
#### What are the benefits of adding this?

a lot of people who can't use krack attack manually with terminal commands would benefit from it.

**Comment by OscarAkaElvis** [comment]
Hi, the problem to add this kind of attack is the lack of solid tools to perform it. All airgeddon dependencies are solid tools which are included in the repositories of the almost the most common pentest Linux distributions. In the case of KRACK attack, there are only some dirty pythons in the author-discoverer github repo.

So, as far as I know, there is no a solid tool to perform this. I mean a tool which reached repos to be installed by apt on Debian based or by pacman on Arch based distros, etc. Maybe this could be reviewed in the future. Thanks for the suggestion.

**Comment by ChillVibesMushroom** [comment]
I just had to do a system re install because I thought running vanhoefm script in a venv and breaking system packages I would be able to get things working I forgot how I did it last time but anyways long story short I ended up here to see if airgeddon had a krack method

**Comment by OscarAkaElvis** [comment]
Now, plugins system exist. So if you want to integrate some dirty pythong stuff to airgeddon, now you can. Nowadays in 2023, there is still a lack of solid tools to perform this attack. So I think que only way is to do a plugin to integrate it. But it is something for now that you should do.
