### ISSUE TITLE
how can we add/edit captive portal login pages in evil twin attack of airgeddon?

### ISSUE THREAD

**Issue by RadhaKrishn4** [v1s1t0r1sh3r3/airgeddon#365]
#### Is your question related to any concrete technology?

its related to evil twin captive portal attack in airgeddon
#### Describe your question as detailed as possible

is there any way to add & edit more captive portal pages in airgeddon's evil twin attack

**Comment by OscarAkaElvis** [comment]
Please, before asking check our wiki. This was asked many times in different issues... and the answer is here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting

**Comment by its0x08** [comment]
Actually would be good to have bootstrap or something to make it match the screen size and orientation to show more trusted password asking portal than the one it shows..
in my phone the password input is microscopic so most of my victims dont even bother to zoom in to read it ..
Auto resizeable would be nice!!!!

**Comment by OscarAkaElvis** [comment]
I tested it in may devices and in almost all it is shown correctly. It is in fact autoresizable. Maybe you have one device on which this is not happening. Anyway, to create something that work 100% in all devices, all pcs, all browsers around the world is almost impossible.

**Comment by its0x08** [comment]
well sorry to say but last time i tried is almost 2 years ago and didnt try anymore because of that !!
maybe over time u fixed it ...!

**Comment by OscarAkaElvis** [comment]
Not sure what you want. Anyway, you can edit the portal on your own. Check this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#can-be-the-evil-twin-captive-portal-page-be-customized-how

**Comment by its0x08** [comment]
Thank you @OscarAkaElvis
