### ISSUE TITLE
make airgeddon automatically save wpa handshakes & pmkid shakes found in target searching window in airgeddon handshake capture attack as well as evil twin captive portal attack.

### ISSUE THREAD

**Issue by RadhaKrishn4** [v1s1t0r1sh3r3/airgeddon#366]
#### Describe the feature or compatibility enhancement and involved versions if apply

when we search for target ap's in search window usually some handshakes & pmkid shakes are found while probing why cant we make the airgeddon automatically save them coz it'll save time for that ap next time if we want to target it!!
#### What are the benefits of adding this?

we can save time removing the need to separately capture handshake hence the overall time will be reduced when we target that ap next time

**Comment by OscarAkaElvis** [comment]
No, they are different features. Scan is scan. To capture a handshake is to capture a handshake. Due privacy violation, maybe while you scan, you can capture handshakes of networks which you don't want to audit. Remember that airgeddon is a pentest focused tool.

I saw you opened 3 issues the same day. Please, stop doing this. You can contact us on Discord channel if you want to discuss anything. More info on wiki contact section.

Closing.
