### ISSUE TITLE
Can't scan for any network in  monitor mode.

### ISSUE THREAD

**Issue by IstieakAhmed** [v1s1t0r1sh3r3/airgeddon#367]
#### What is your airgeddon version?

<I have downloaded it just now. I think my is the latest version. >

#### What is your Linux O.S. and which version?

<Kali Linux 2020.1>

#### Which is the chipset of your wireless card?

<Qualcomm Atheros QCA9377 802.11ac Wireless Network Adapter>

#### Describe the issue and the steps to reproduce it

<I have sslstrip missing in airgeddon. I have tried to install it by "apt-get install sslstrip" command. But It says unable  to locate the file. So, I started airgeddon without this tool. Then I tried a evil twin attack. Then I put my Wireless card into monitor mode. But I can't scan for any network. The new window opens but I have waited more than 10 minute but no wifi network shows. Please help me with this issue.I have also tried the automatic installation but that could not solve the issue.
![Screenshot 2020-04-24 04:28:44](https://user-images.githubusercontent.com/54891541/80168825-e8395b00-85b1-11ea-9125-19fdb83eb001.png)

![Screenshot 2020-04-24 04:08:46](https://user-images.githubusercontent.com/54891541/80168545-1f5b3c80-85b1-11ea-8cca-9942fccdf268.png)
![Screenshot 2020-04-24 04:09:32](https://user-images.githubusercontent.com/54891541/80168552-22eec380-85b1-11ea-9c95-8ebb8425ebcf.png)

>

**Comment by xpz3** [comment]
Join discord server for further communication. Most probably the issue could be related to your wireless card chipset.
https://discord.gg/sQ9dgt9
You can also try the following
Restart your pc
Run `airmon-ng check kill` command after restart
Manually put your card into monitor mode
Then manually run `airodump-ng monitor_interface_name`
And see if networks show up.

You did not also mention your airgeddon version

**Comment by IstieakAhmed** [comment]
I have already tried these steps but I couldn't solve this issue. Also, my airgeddon is the latest version. Please help me!!

**Comment by xpz3** [comment]
I found online that this chipset is known to have problems. You are out of luck. You should buy a usb wifi card which is fully compatible with airgeddon if you want to perform wireless auditing. See below the list of some working as well as non working cards. Do some research if you plan to buy one. Don't even think of getting rtl88xx or rtl81xx chipset cards as they won't ever work.

Some supported and blacklisted cards and chipsets
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards-and-Chipsets

**Comment by OscarAkaElvis** [comment]
Regarding the lack of the sslstrip package... it seems that Debian retired it from repos, so Kali and other Debian based also retired it too... check this: https://github.com/v1s1t0r1sh3r3/airgeddon_deb_packages

You can find the packages you need there. Just install them using dpkg. Packages are:

python-twisted-bin
python-twisted-core
python-twisted-web
sslstrip

If you install them in this order, you'll be fine.

But please, next time, read the wiki before asking. This answer is already there: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#i-am-missing-some-dependencies-what-can-i-do
