### ISSUE TITLE
Realktek RTL8812BU Cant be placed into monitor mode?

### ISSUE THREAD

**Issue by Beazor** [v1s1t0r1sh3r3/airgeddon#371]
#### What is your airgeddon version?
10.11v

#### What is your Linux O.S. and which version?
Kali linux 2020.1

#### Which is the chipset of your wireless card?
RTL8812BU

#### Describe the issue and the steps to reproduce it
Press option 2 to enable monitor mode. It says not supported but it is supported.  Monitor mode does work on 8812BU. I installed the realtek fix but still not working. monitor mode works with everything else.

![see](https://user-images.githubusercontent.com/64564446/80659725-1eed0500-8acd-11ea-9fca-4a16138d3bae.JPG)

**Comment by OscarAkaElvis** [comment]
Sorry but you have one of the blacklisted chipsets. Check this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

That cards have weird behaviour and we are not supporting them. You'll need to get another one to work flawlessly with airgeddon.

Regarding he realtek chipset fixer plugin, if you have airgeddon v10.01 or higher, it is not needed as it is explained here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Hall%20of%20Fame

Anyway, you could try to join to our Discord channel. Will see there if we can help you further.
