### ISSUE TITLE
(bully) pixie dust attack not working

### ISSUE THREAD

**Issue by carmonkeylab** [v1s1t0r1sh3r3/airgeddon#372]
#### Is your question related to any concrete technology?

Linux
#### Describe your question as detailed as possible

i am trying to do a bully pixie dust attack with no luck. i am unable to get my routers pin. what might i be doing wrong because i bought a wifi adapter for just this purpose

**Comment by OscarAkaElvis** [comment]
That could be a completely normal behavior. Only few APs are vulnerable to Pixie Dust attack. Read this:

http://archive.hack.lu/2014/Hacklu2014_offline_bruteforce_attack_on_wps.pdf
