### ISSUE TITLE
Dnsspoof doesn't work anymore 

### ISSUE THREAD

**Issue by bvdx199** [v1s1t0r1sh3r3/airgeddon#373]
#### What is your airgeddon version?

Latest version of parrot 4.6

#### What is your Linux O.S. and which version?

parrotsecurity os 4.6

#### Which is the chipset of your wireless card?

Ralink (the green alfa) 

#### Describe the issue and the steps to reproduce it

I was working with kali nethunter lately to get mana working but it won't dnsspoof. So I tried on all Linux distributions, then I realize airgeddon also uses dnsspoof. And yes airgeddon doesn't work anymore because of dnsspoofing. 
When I try to connect my device I get a wifi logo with an "!" mark and I won't be redirected to the router login page. 

Is there any way to fix this?

**Comment by bvdx199** [comment]
![15884295750684185847282169489020](https://user-images.githubusercontent.com/35387233/80866921-ad11e880-8c91-11ea-9e63-44b4b2e1d740.jpg)

**Comment by xpz3** [comment]
From the dns window i can say for sure that you aren't running a latest version of airgeddon

**Comment by bvdx199** [comment]
Well I use an older version of parrot but if I open airgeddon on my up to date linux system, it still doesn't dnsspoof

**Comment by xpz3** [comment]
On your parrot 
1. Open a terminal
2. Type `sudo git clone https://github.com/v1s1t0r1sh3r3/airgeddon airgeddonmaster`
3. Type `cd airgeddonmaster`
4. Type `bash airgeddon.sh`
See if dnsspoof works by running evil twin

**Comment by OscarAkaElvis** [comment]
Why do you say is not working? I have parrot updated to the latest (airgeddon v10.11 is the latest that can be get by apt) and it works like a charm for me... so please, don't say "dnsspoof doesn't work anymore". Better say "is not working for me" or "i'm not able to get it working" or any other.

You don't have latest airgeddon. your dnsspoof windows is still print on green. On latest airgeddon versions dnsspoof window is printed on blue.

What is supposed that we should see on your poor quality photo? (use better screenshots next time). I think that is showing ok the redirections... ¿? I tested it right now and it works very well. My client device once connected to the  fake network is well redirected to the captive portal.

Closing and please, don't make us to lose our precious time agan. And if you have more questions join to Discord channel and maybe there they can be answered.

I must confess that I hate people taking time to write complex and fake stuff but that they don't take time to perform one click to star the repo on which is complaining.
