### ISSUE TITLE
AP DOESENT WORK

### ISSUE THREAD

**Issue by johnjohn3x** [v1s1t0r1sh3r3/airgeddon#376]
#### Describe your question as detailed as possible

![airgeddon hostapd](https://user-images.githubusercontent.com/66141884/85237174-663ca580-b42d-11ea-9ab1-e0de1d91f683.JPG)

PLEASE HELP!!! I CANT FIGURE IT OUT

**Comment by OscarAkaElvis** [comment]
You didn't filled the correct template with all the needed data. In order to be able to help you, we'll need more data. Operating system, airgeddon version, wireless card, chipset, etc. Please, join Discord channel to discuss this deeply: https://discord.gg/sQ9dgt9
