### ISSUE TITLE
Exploring for targets shows no result

### ISSUE THREAD

**Issue by Parv-B** [v1s1t0r1sh3r3/airgeddon#377]
#### What is your airgeddon version?

 v10.21

#### What is your Linux O.S. and which version?

 Kali Linux 2020.2

#### Which is the chipset of your wireless card?

 It has Broadcom BCM2711, a 64-bit quad-core Arm Cortex-A72 and Cypress CYW43455 chip

#### Describe the issue and the steps to reproduce it

 
I select Evil twin attack and it opens the menu
![eviltwinmenu](https://user-images.githubusercontent.com/65509734/85608620-c22d4700-b644-11ea-9103-363f06e71e40.png)

I select Explore for targets
![exploremenu](https://user-images.githubusercontent.com/65509734/85609418-92cb0a00-b645-11ea-96ef-bca5f98ef727.png)

I have waited for 30 min without getting any target in the other window.
I think this is a bug becuase I have seen youtube videos of people getting targets within a minute.

Thanks for your help :)

**Comment by OscarAkaElvis** [comment]
Yeah, maybe is a problem of your card. Is an external usb card? or is the Rpi4 internal card? I don't recommend to use the internal card. I think that is the problem. Maybe there is a problem with the drivers...

I don't have a Rpi4 to test... i worked with rpi3 and rpi1 fine but always using an external Alfa usb card. The internal cards of the rpi are always messing around.

Please, join discord channel to further discussion (Invitation link: https://discord.gg/sQ9dgt9).

Check the wiki for more info:
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting

**Comment by OscarAkaElvis** [comment]
You don't need to wait 30 min... if in some seconds there are no networks... something bad is happening.

You should check out of airgeddon to test. I guess you'll have the same problem. `airmon-ng check kill && airmon-ng start wlan0 && airodump-ng wlan0mon`

**Comment by Parv-B** [comment]
Thanks for that. I tried the command and - it showed 3 networks within 5 seconds.

Do you suggest I should delete and reinstall Airgeddon?

**Comment by xpz3** [comment]
Broadcom chipsets are not good for wifi auditing. Even if you succeed exploring for targets, you may find trouble running evil twin attack. 
The first image you posted where you selected option 7 shows the message "Setting your interface in managed mode" seems invalid behaviour. 
I recommend you to do the following steps to explore for targets properly.
1. Restart your rpi
2. Open terminal and run airmon-ng check kill
3. Run airgeddon using bash airgeddon.sh
4. Select your wifi interface
5. Use menu option 2 to put the card into monitor mode
6. Goto evil twin menu 7
8. Then explore for targets

**Comment by OscarAkaElvis** [comment]
hmmm.... weird. If it works for you out of airgeddon, it should work using airgeddon because in the end, airgeddon is doing the same commands. I don't think that reinstalling airgeddon could help here.

Anyway, i can see something weird on your screenshots... it seems that your card is called mon0. Usually it should be wlan0 in managed mode and after setting it to monitor (using airgeddon) it should be called wlan0mon ... but in your case it is mon0. Maybe there is something you are not telling to us. Are you setting it to monitor using airgeddon or are you doing something outside airgeddon to set it to monitor mode?

Can you put the output of your `lsusb` , `lspci` and ìwconfig`commands? screenshots if possible. Thanks

**Comment by Parv-B** [comment]
I just tried it again and it seems to work perfectly. Yaayyy. Thanks for the help. Im new to Internet security and you guys are very welcoming.

Thanks for the help :)

**Comment by OscarAkaElvis** [comment]
Yeah, sometimes the adapters could hang, that's all. Just reboot or unplug and plug again if is an external card and that kind of things. Great if worked for you! don't forget to support us starring our repo! and join Discord channel to be updated about changes and features! there is a great community of people asking and helping them each other. Give it a try!

**Comment by rahulagraharilko-netizen** [comment]
What is your Linux O.S. and which version?
Kali Linux 2025.4 vm machine 
Which is the chipset of your wireless card?
TP-Link WN725N 150Mbps Wireless N Nano USB Adapter 
Describe the issue and the steps to reproduce it
I selected exploring the target using monitor mode but ssid are not been captured even tried multiple times
 

<img width="1912" height="982" alt="Image" src="https://github.com/user-attachments/assets/35e2dd0a-8352-4c7e-bc72-30e47af772df" />

**Comment by OscarAkaElvis** [comment]
please @rahulagraharilko-netizen , don't hijack other issues. Open a new one if needed, but as I can see on your screenshot, you are using Virtualbox. This is a common problem on Virtualbox: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#when-i-scan-for-wireless-networks-no-networks-are-found

Read the link carefully. On the other hand, you didn't put your chipset, just the model of the adapter, but that is not the chipset. What it matters is the chipset. You can check it launching `airmon-ng --verbose` or `lsusb`. Remember, don't open an issue before reading first the link. And remember that you can also get help on Discord server.

Locking this and good luck!
