### ISSUE TITLE
airgeddon doesn't start because xterm isn't getting installed 

### ISSUE THREAD

**Issue by KedarJoshi11** [v1s1t0r1sh3r3/airgeddon#379]
![image](https://user-images.githubusercontent.com/43803843/86343412-8f073b00-bc76-11ea-8e7e-a98deb35bc71.png)

This is the image of the error, I have tried installing xterm by first installing npm, but it is not working. 

Please help.

**Comment by OscarAkaElvis** [comment]
I can't believe this kind of questions. Did you read the FAQ on wiki?

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting

If you are not able to figure what to do, probably airgeddon is not for you. No offense. I'm just telling that after fixing this you'll find much more things harder to fix or to handle.

**Comment by KedarJoshi11** [comment]
Yes, I know it was a very silly question. I am sorry. I got it resolved.
Thanks again for your help.
