### ISSUE TITLE
WPS attack not working in Kali linux from 2019.1 new update

### ISSUE THREAD

**Issue by Zombii80** [v1s1t0r1sh3r3/airgeddon#380]
When i install airgeddon in kali linux 2019.3 it work fine with WPS Attack its Crack almost any WPS disble wifi in a min or less but after updating kali linux to 2019.1 or in higher version WPS attack is not working its not even giving a WPS pin to help me what shoud i do ?

**Comment by OscarAkaElvis** [comment]
if nothing changed on airgeddon side, the most probably thing is that something changed on driver. The drivers are directly relates to kernel. After updating kernel, the drivers are directly affected.

For further help. join discord channel.
