### ISSUE TITLE
Bettercap Fix

### ISSUE THREAD

**Issue by 5l1v3r1** [v1s1t0r1sh3r3/airgeddon#382]
Well you don't have to downgrade your bettercap to 1.62. You can just download the provided bettercap (https://github.com/v1s1t0r1sh3r3/airgeddon_deb_packages/blob/master/amd64/bettercap_1.6.2-0parrot1_all.deb) and extract it to airgeddon folder. You should adjust airgeddon.sh script according to the new bettercap environment path and that's it. Now airgeddon won't search for default system bettercap and it will load the bettercap from the predefined path.
Secondly if you just upgraded kali to 2020 rolling, your ruby version is now 2.7, in any case to solve the sqlite3 problem with beef you can always do "gem install sqlite3" to be sure it is installed.

**Comment by OscarAkaElvis** [comment]
Not sure to understand the point of this.... is this a bug report? a suggestion? a question? In anycase... we have plans for bettercap. We have a branch created for more than a year and we were discussing the bettercap 2.x compatibility with the bettercap staff. It seems recently they changed some stuff and probably we'll be able to integrate it so maybe in the near future there will not be needed of doing anything of this. Be patient and stay tuned. Closing.
