### ISSUE TITLE
Tmux on airgeddon

### ISSUE THREAD

**Issue by ronnjoshua** [v1s1t0r1sh3r3/airgeddon#383]
How can I fix this? help please...
![Screenshot_20200803_224314_com termux](https://user-images.githubusercontent.com/53202469/89195025-bedd9180-d5da-11ea-9756-e9103c76bcc2.jpg)

**Comment by ronnjoshua** [comment]
I changed xterm to tmux
![Screenshot_20200803_224411_com termux](https://user-images.githubusercontent.com/53202469/89195116-df0d5080-d5da-11ea-88cf-bdf897c42617.jpg)

**Comment by OscarAkaElvis** [comment]
Impossible to help you if you don't put all the details we need. That is the reason why an issue template exist, but you didn't fill it. So closing due issue creation policy violation. Anyway, connect to Discord channel for further help. You can find invitation link on contact section at wiki.

**Comment by ronnjoshua** [comment]
Okay I am sorry and thanks for replying

**Comment by OscarAkaElvis** [comment]
No problem, connect to Discord, we can check it there.

**Comment by ronnjoshua** [comment]
Can I get discord channel I cant find it thank  youu

**Comment by ronnjoshua** [comment]
I got it already hehe thanks
