### ISSUE TITLE
Option for default save path

### ISSUE THREAD

**Issue by orthoron** [v1s1t0r1sh3r3/airgeddon#384]
#### Describe the feature or compatibility enhancement and involved versions if apply
Title says it all, would be nice to be able to change to a new default save path (currently /root/)

#### What are the benefits of adding this?
Time savings

**Comment by KeyofBlueS** [comment]
Hi @orthoron,

this can be easily achieved with a plugin, I've made one exactly for this, You can find it in my [airgeddon-plugins repository](https://github.com/KeyofBlueS/airgeddon-plugins).
