### ISSUE TITLE
TL-WN722N v2 

### ISSUE THREAD

**Issue by RocXelL** [v1s1t0r1sh3r3/airgeddon#385]
#### Describe the issue and the steps to reproduce it

![IMG_20200818_012731](https://user-images.githubusercontent.com/67182420/90478039-14915e00-e0f2-11ea-984a-f610ef30f419.jpg)
![IMG_20200818_012749](https://user-images.githubusercontent.com/67182420/90478050-18bd7b80-e0f2-11ea-8dfd-5edabebcc313.jpg)
Ok so what happens is that im trying to do a evil twin attack and basically it does create the evil twin AP and I can capture the handshake.
But when doing the last part of the attack which is deauthing the "victim" ap and creating a fake AP to phish the password; what happens is that the window which is supposed to deauth the victim ap just stays stuck in "Waiting for beacon frame".
And I tried manually deauthing with aireplay-ng but the fake AP dissapears.
So basically it's either I deauth or I make a fake AP.
I would appreciate the help!

**Comment by OscarAkaElvis** [comment]
You didn't filled the needed fields to help you. The questions on the issue creation template are there for a reason, not to ignore them.

Anyway, it sounds like your card is not supporting VIF to perform DoS at the same time as fake AP.

For further discussion or help, join discord channel. Find the invitation link on the wiki contact section. Closing.
