### ISSUE TITLE
Exploring targets not picking up 5GHz routers

### ISSUE THREAD

**Issue by Lightning-blade** [v1s1t0r1sh3r3/airgeddon#388]
What is your airgeddon version?

**version 10.21**

What is your Linux O.S. and which version?

**Kali Linux 2020.3**

Which is the chipset of your wireless card?

**rtl8811au**

Describe the issue and the steps to reproduce it
**My issue is that my Alfa AWUSO36ACS (which is dual band) is not picking up my routers in the 5GHz but only those in the 2.4GHz. I have already updated and upgraded my distro several days ago. I have already installed the driver for this network card. Here are the EXACT steps taken below:

Step one---Start up airgeddon(No problem here)

Step two---Select interface card and then put it in monitor mode(No problem here)

Step three---select option 8 for WPS attacks menu(No problem here)

Step four---select option 4 to explore for target(Problem begins here. After pressing enter to start the scan, some networks show up-those that are only 2.4GHz. My router does not show up. If however I use a tool  that rhymes with fairmon-ng (lol) and put it monitor mode not using anything of airgeddon and scan for networks my router together with other routers in the 5GHz range show.)

Some extra info that may be useful: I did not have sslstrip installed as reading by your other issue threads it has been depreciated? so I saw no need for it...unless you recommend I do install it. If you do recommend please give the commands for installing it.

Thanks in advance for all your help, great tool!**

**Comment by OscarAkaElvis** [comment]
Hi, yeah, RTL chipsets have known problems. Check this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Almost all RTL8x cards have problems... some for the WPS, some for the VIF (virtualization multiple interface) needed for evil twin attack.

Anyway, here is the command airgeddon is running: `wash -i wlan0mon` and adding the extra `-5` to the command to get 5ghz channels if supported. Is your card showing 5ghz support on the menu? a screenshot could be nice.

Anyway, connect to Discord channel for further discussion.

**Comment by Lightning-blade** [comment]
Thank you for the speed response!
My card does show up support for 5GHz in the main menu. Please see screenshot of it attached
![selectingcardinterface](https://user-images.githubusercontent.com/69900903/90756933-3d297b80-e2dd-11ea-9d36-5e9cc3385cfb.png)

**Comment by OscarAkaElvis** [comment]
What is your wash version? Is included in reaver package. You can check it just launching `wash -h` and the version is shown.

Anyway, put your card in monitor mode and try out of airgeddon these commands, from a standard shell as root:

`wash -i wlan0mon -2` <- this should show only 2.4ghz networks

`wash -i wlan0mon -5` <- this should show only 5ghz networks

If you get fcs errors add `-F` to the command.

To show both launch this: `wash -i wlan0mon -2 -5`

The dual scan `-2 -5` is only available from certain wash version... so please, as I requested, put your wash version here.

This last command is what airgeddon is launching if it detects taht your card is supporting 5ghz and as I can see on the screenshot, that part is well detected, so it should work. Try out of airgeddon to see the results... if it doesn't work even out of airgeddon, then is not airgeddon related problem.

Let us know the results! and remember that on Discord you'll get faster help, more people involved, there are a community there to help!

**Comment by Lightning-blade** [comment]
Yeah I tried the commands in your order and no networks show up! I waited for several minutes and nothing shows up. The same thing happened when I tried 5GHz command and the 2.4 and 5GHz command together. 

Wash version===1.6.6

Screenshot is attached
![Screenshot_2020-08-20_10-58-20](https://user-images.githubusercontent.com/69900903/90762633-a44b2e00-e2e5-11ea-8a1b-eaa3731e272a.png)

Just downloaded the Discord app now, total beginner at it, so let me know what's the code or name of the channel I should join

**Comment by OscarAkaElvis** [comment]
I received your screenshot by mail, but for some reason is not here...

anyway. Version 1.6.6 is ok, it supports both options at the same time.

Regarding Discord, you can find the invitation link on Contact section of our wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Contact

The invitation link is this: https://discord.gg/sQ9dgt9

Join and we can continue investigation there. But at first sight, sound like a problem due problematic chipset as I told you. Try to unplug the card, plug it again, reboot, etc... did you perform the commands with the card on monitor mode?

**Comment by Lightning-blade** [comment]
Thank you for the invite link, we will chat on Discord
