### ISSUE TITLE
Integrate Besside-ng

### ISSUE THREAD

**Issue by zero77** [v1s1t0r1sh3r3/airgeddon#392]
## Describe the feature or compatibility enhancement and involved versions if apply

Can you please add support for Besside-ng which is part of the Aircrack-ng suite.
Ideally alongside the evil twin attack if not then as a separate option.

#### What are the benefits of adding this?

Besside-ng is a very powerful tool and if used alongside the captive portal attack it could completely automate the hole process.
Also, it can target multiple AP at once which improves efficiency and success.

https://www.aircrack-ng.org/doku.php?id=besside-ng

**Comment by OscarAkaElvis** [comment]
Thanks for the suggestion. Right now we are focused in other stuff, but we'll take it into consideration.
