### ISSUE TITLE
raspberry pi4 4GB on-board monitor/manage mode issue

### ISSUE THREAD

**Issue by vaniaamad** [v1s1t0r1sh3r3/airgeddon#393]
i have raspberry pi 4 4GB , having built in wifi chip ,downloaded kali linux 2020.3a nexmon 64 bit image from www.kali.org . downloaded tool airgeddon from github.com for evil twin attack & when i try to put the wifi in monitor/manage mode, it says chip unknown , although i have checked that the on board chip supports monitor & managed mode with packed injection. as tools like fern wifi cracker , aircrack they are good to go in both modes.

any help will be highly appreciated as i couldn't find the solution after 3 days of googling & pasting my issue on the official kali community support & got no luck.

i even posted the issue on unix&linux but they say to contact the tool authors.

please help to resolve this issue as why isn't monitor/managed mode working in airgeddon for the onboard wifi chip on raspberry pi4 4GB. I have used this tool for many years & never had issue with it on laptop.

**Comment by cjb900** [comment]
The built in wifi chip in the Raspberry pie 4 as it may support monitor mode is a Broadcom chipset. Broadcom chipsets are notorious for not working properly for wifi hacking. This isn't anything in the code for airgeddon or kali and there isn't anything anyone can do other than recommend that you get a properly supported USB wifi adapter. You can find a list of card that are knows to work with airgeddon here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by vaniaamad** [comment]
thank u for ur reply but if thats the case , correct me if i m wrong then why is it working perfectly with fern wifi , aircrack-ng etc ...they dont have any issues in either mode , but tools as fluxion airgeddon are causing problem , if the problem would have been with the on board broadcom chip then it should have had issues with the pre-installed tools (fern & aircrack)...
i m looking for solution other than changing my wifi adapter ..is there a way to fix this issue with the on board chip to fiwork with airgeddon, it says when i put it to monitor mode , chip unknown ...

**Comment by cjb900** [comment]
I also have a Raspberry Pi 4 4GB and the reason it works with fern wifi and aircrack-ng is because those tools only use monitor mode. Tools like Fluxion and Airgeddon need an adapter that support running more then one mode at a time (monitor mode and AP mode). So they need to be able to create a fake AP and deauth at the same time. The built in wifi adapter in the pi does not support AP mode or VIF to be able to use tools like fluxion and airgeddon properly. The only solution would be to get a known adapter/chipset rather then wast the time trying to get the built in wifi chipse to work only to find out that it will not work in the end.

**Comment by vaniaamad** [comment]
oops thats disappointing , any other tool that u can suggest that will work for me without changing the wifi adapter , for evil twin attack...
appreciate ur reply mate..thanks

**Comment by xpz3** [comment]
Evil twin works with only a few wifi chipsets and unfortunately yours is not among them. So the only possible way to get evil twin working is to buy a compatible adapter that supports vif.
