### ISSUE TITLE
Portal page 

### ISSUE THREAD

**Issue by Ferjani97** [v1s1t0r1sh3r3/airgeddon#400]
Is it possible to link another custom landing page index or URL after clicking submit password button.

**Comment by OscarAkaElvis** [comment]
Hello, yes, you can customize the portal captive page. There are a lot issues already asking the same thing. You also have some notes about it. Check this:

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#can-be-the-evil-twin-captive-portal-page-be-customized-how

If you have more doubts, you can also join to our discord channel for further discussion. Here is the link: https://discord.gg/sQ9dgt9
