### ISSUE TITLE
A graphical X window system has not been detected. If you already have one, check it's working properly. It's essential for airgeddon. The script can't continue 

### ISSUE THREAD

**Issue by gurkirat816** [v1s1t0r1sh3r3/airgeddon#405]
A graphical X window system has not been detected. If you already have one, check it's working properly. It's essential for airgeddon. The script can't continue

**Comment by xpz3** [comment]
You have not filled the issue template properly and hence its impossible to help you on your issue. Join airgeddon discord channel for easier resolution of issues.
Closing...
https://discord.gg/sQ9dgt9

**Comment by fate182** [comment]
You need to pass enviroment DISPLAY to root for xhost. If you are root, make

`xhost +SI:localuser:root`

or just use -E flag with sudo:

`sudo -E ./airgeddon.sh`
