### ISSUE TITLE
insert data manually for WPS test (hidden network)

### ISSUE THREAD

**Issue by lucasTam** [v1s1t0r1sh3r3/airgeddon#406]
#### Is your question related to any concrete technology?
Airgeddon v10.21

Wifislack64 2.2

#### Describe your question as detailed as possible

How can I manually enter in the script the data required to test the WPS of my router (which has a hidden network), and then make the attack?

Thank you very much for your help

**Comment by OscarAkaElvis** [comment]
Really? is as simple as open airgeddon, select card, put it in monitor mode, select wps menu and select any attack without perform any scan.... simple. You'll be prompted to continue inserting data manually.

![image](https://user-images.githubusercontent.com/5803348/96678498-1f76a200-1372-11eb-9ddc-6f4d43454cb2.png)

Answer "y" to the question, that's all. Then you can enter the BSSID and the channel to perform the attack over the hidden network if you already have that data.

Please, to ask questions join Discord channel. Invitation link: https://discord.gg/sQ9dgt9
