### ISSUE TITLE
hcxpcaptool deprecated, removed and replaced by hcxpcapngtool

### ISSUE THREAD

**Issue by ZerBea** [v1s1t0r1sh3r3/airgeddon#407]
hcxpcaptool is removed and replaced by hcxpcapngtool.
Now, default format is pcapng, but cap and pcap are supported, too.
Default hash format is WPA-PBKDF2-PMKID+EAPOL, according to latest hashcat.
```
$ hashcat --help
  22000 | WPA-PBKDF2-PMKID+EAPOL                           | Network Protocols
  22001 | WPA-PMK-PMKID+EAPOL                              | Network Protocols
```
Old hash formats 1680x and 250x are deprecated, too.

Running airgeddon in combination with latest hcxtools will cause an error:
https://forum.hashkiller.io/index.php?threads/noob-to-hashcat-question-s-to-found-pmkid-kali-linux.42849/page-2#post-267928

**Comment by OscarAkaElvis** [comment]
This was already solved for the next version v10.31 which is not released yet. It is available on dev branch. We migrated to use new hashcat formats 22000 as you can see on this commit: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/379afedb619701ef96b51b921e8d249b5dcd4d86

Regarding the replacement, also already done here https://github.com/v1s1t0r1sh3r3/airgeddon/commit/6592ba848095f76b576e9ecdee996250a433dece and here https://github.com/v1s1t0r1sh3r3/airgeddon/commit/43c03ac5a3d424fc697b424242c1fbc46e308f2a

Try it yourself cloning dev branch.

**Comment by ZerBea** [comment]
Glad to hear that. Thanks for the info. I haven't notice that KALI still using the old version. So it's more a KALI related issue tha an airgeddon issue.
Cheers
Mike

**Comment by ZerBea** [comment]
BTW:
I noticed that most of the reported issues are related to KALI. Either a broken package system, missing or old dependencies or unexperienced users. Unfortunately I often fall into this (KALI) trap. Nearly 99% of all issues reported to hcxtools/hcxdumptool are related to KALI. So please forgive me reporting this issue again.
Cheers
Mike

**Comment by OscarAkaElvis** [comment]
haha, no problem! thanks for your interest 😄
