### ISSUE TITLE
AP cannot be connected, and 5g wifi cannot be de-authenticated

### ISSUE THREAD

**Issue by LuckyFishGeek** [v1s1t0r1sh3r3/airgeddon#408]
Did you read the FAQ & Troubleshooting wiki section before asking? Maybe the answer is there: 

I've read it and didn't find the answer

#### What is your airgeddon version?

v10.30 

#### What is your Linux O.S. and which version?

 Kali Linux 2020.4  kernel:5.9.0-kali1-amd64

#### Which is the chipset of your wireless card?

rtl8812au 

#### Describe the issue and the steps to reproduce it

First I ran three commands to turn off any interference that might cause airgeddon

sudo airmon check kill

sudo systemctl disable systemd-resolved.service

sudo systemctl stop systemd-resolved

I executed the 7th function: 

Evil Twin attacks menu-Evil Twin AP attack with captive portal

When scanning APs and attacking packets, they work normally without any problems.

But after the AP is simulated successfully, the AP cannot be connected

![Snipaste_2020-11-30_09-37-34](https://user-images.githubusercontent.com/29472751/100560847-16261100-32f2-11eb-9e0f-d8cad70cb16c.png)

**Comment by cjb900** [comment]
If you look at the list of the list of [Cards and chipsets ](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets) you will see that the card you are using is known to have issues and is not recommended. That could be the whole problem you are having.

**Comment by LuckyFishGeek** [comment]
@cjb900 
Thank you for your answer, brother, I have read these documents before use, there is a document saying that someone has fixed the 8812AU problem through the plug-in method, and integrated it into the latest version of airgeddo

**Comment by cjb900** [comment]
Yes that fix made another issue with that card work with airgeddon but it did not fix that fact that it does not support VIF which is needed for the evil twin attack.

**Comment by LuckyFishGeek** [comment]
> Yes that fix made another issue with that card work with airgeddon but it did not fix that fact that it does not support VIF which is needed for the evil twin attack.

Thank you brothers for your patience to answer! Looking forward to having friends who can handle this problem, it will be perfect, and they can phisher under 5G.

**Comment by cjb900** [comment]
if you look at the list of adapters and chipsets https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets there are many that support 5ghz that are known to work with airgeddon

**Comment by OscarAkaElvis** [comment]
Extracted from the wiki on the link that @cjb900 put here:

![image](https://user-images.githubusercontent.com/5803348/100578572-dd327000-32e2-11eb-9eed-497c570b2f87.png)
