### ISSUE TITLE
auto redirect

### ISSUE THREAD

**Issue by Dylan433447** [v1s1t0r1sh3r3/airgeddon#410]
is it possible  to redirect devices in the network im attacking automatically to the fake ap ???  in the old versions there was an attack using internet acess it was working before i connect my phone and do USB tethering and share internet and it automatically redirect devices to the FAKE AP when they get disconnected  why its not working now ??!

**Comment by OscarAkaElvis** [comment]
No. Is not possible. The real network has password and the fake network is an open network. Is not possible to force the victim to connect to the fake network. The configuration is different between the networks. Always there will be a social engineering factor.
