### ISSUE TITLE
Airgeddon don't generate password file

### ISSUE THREAD

**Issue by ArtPes** [v1s1t0r1sh3r3/airgeddon#412]
#### Is your question related to any concrete technology?

Kali Linux, airgeddon v10.31

#### Describe your question as detailed as possible

I've airgeddon v10.31. It works fine, but I've some problems with the password file. The tool correctly captures passwords but does not save to the file. I can see the pass in xterm console but none file is generated.

**Comment by OscarAkaElvis** [comment]
What attack are you talking about? Do you have permission s over the target for? Can you paste any screenshots?

**Comment by Justxd22** [comment]
it asks for save path before any attack if you left it as default it will be /root/ATTACKNAME_password-NETWORKNAME.txt 
you should check there for any saved files see pic for an example
![Screenshot_20201227_103150(1)](https://user-images.githubusercontent.com/66136622/103166149-44830780-4830-11eb-968d-12312f821aed.png)

**Comment by ArtPes** [comment]
Evil Twin --> Deauth aireplay attack. 
I've permission on that dir.
As you can see from the screenshots, I'm able to create handshake and save it but not the password file.
![Istantanea_2020-12-27_09-37-55](https://user-images.githubusercontent.com/20612854/103168085-97f55580-4830-11eb-8d67-eb31db3283cc.png)
![pass](https://user-images.githubusercontent.com/20612854/103168086-99bf1900-4830-11eb-912a-426f10854012.png)

**Comment by Justxd22** [comment]
Maybe enter your documents path instead idk it always work for me , also try running from different user

**Comment by OscarAkaElvis** [comment]
It makes no sense for me. I'm not able to reproduce it. airgeddon checks the write permissions on the given path and it also checks that the path exist. I did many attacks on many different Linux and it worked fine on each one.

Remember that on evil twin it saves file only if the right pass is get. On the screenshots I can't see a final right password, only attempts.

**Comment by ArtPes** [comment]
I reinstalled airgeddon and now the pass file is created too. Thanks for the tips!
