### ISSUE TITLE
fake ap attack problem

### ISSUE THREAD

**Issue by kissmorning** [v1s1t0r1sh3r3/airgeddon#414]
Hello again. There is a small problem. i am using dual usb wifi card. dos follow mode is active. mdk4 or aireplay Attack is terminated within minutes after initiating twin (fake ap), what could be the problem.

**Comment by xpz3** [comment]
> Hello again. There is a small problem. i am using dual usb wifi card. dos follow mode is active. mdk4 or aireplay Attack is terminated within minutes after initiating twin (fake ap), what could be the problem.

Try running `airmon-ng check kill` before running airgeddon

**Comment by kissmorning** [comment]
![2021-01-07_11-27-25](https://user-images.githubusercontent.com/68402414/103869456-5f306880-50db-11eb-9bbc-7d5c93d35806.png)

**Comment by xpz3** [comment]
Run airgeddon after running that command

**Comment by kissmorning** [comment]
I'm testing now

**Comment by kissmorning** [comment]
![2021-01-07_12-28-30](https://user-images.githubusercontent.com/68402414/103875962-1c26c300-50e4-11eb-8f2b-0e7488799da0.png)

what does this error mean

**Comment by xpz3** [comment]
It's not an error. The window size is small. Just increase the window size horizontally a bit and the multiple lines will be gone and will be shown correctly. This control window shows info about any clients connecting to fake AP and any password attempts.
As i said earlier, join discord for further discussion. There are many others in discord who can help. Closing...
