### ISSUE TITLE
Please help me regarding the fake page not appearing

### ISSUE THREAD

**Issue by mohamedmzeka1** [v1s1t0r1sh3r3/airgeddon#419]
#### Describe the issue and the steps to reproduce it
I registered on the platform you sent me this invitation link
https://discord.gg/Hkuq4NHv

**Comment by mohamedmzeka1** [comment]
![Screenshot at 2021-01-20 15-45-40](https://user-images.githubusercontent.com/76184211/105397756-2390b500-5c2a-11eb-8c6a-ef4cd9755827.png)
![Screenshot at 2021-01-21 05-02-14](https://user-images.githubusercontent.com/76184211/105397771-268ba580-5c2a-11eb-983d-771d49333d89.png)

**Comment by cjb900** [comment]
if you post your issue on our discord we can try to help you further there.

**Comment by mohamedmzeka1** [comment]
Tell me how to join you there This is my invite link https://discord.gg/nepsthk2

**Comment by mohamedmzeka1** [comment]
![image](https://user-images.githubusercontent.com/76184211/105398990-a9f9c680-5c2b-11eb-94db-5b9681e4f32a.png)

**Comment by mohamedmzeka1** [comment]
https://discord.gg/Hkuq4NHv

**Comment by cjb900** [comment]
you obviously have a discord account now. you can join our discord here https://discord.com/invite/sQ9dgt9. We are not going to join the one you created when we already have one specifically for aireddon

**Comment by OscarAkaElvis** [comment]
Opening an issue twice? You'll be blocked here. Contact us on discord and remember to read the rules before talk in the channel.
