### ISSUE TITLE
All types of death not working only in Evil twins 

### ISSUE THREAD

**Issue by Dylan433447** [v1s1t0r1sh3r3/airgeddon#421]
Using Kali 2020.4 
 Network adapter :TP-Link N150 TL-WN722N
Latest version of airegeddon

Everything fine the death methods working when grabbing the handshake but when I run Evil twins it doesn't kick anymore but it runs the AP FINE and login fine, also packet injection fine no problem except on evil twins deauth

**Comment by xpz3** [comment]
Your tplink card might be v2 or v3 which comes with a chipset that's incompatible for evil twin attack. For evil twin to work properly, it needs to support vif(interface combinations) which you card lacks. Only version 1 of tl-wn722n has a supported chipset.. So you better get a supported adapter. See wiki for compatible adapters. If you do have a spare adapter, we can make that adapter to do the deauth. Join discord for more info. https://discord.gg/sQ9dgt9

**Comment by Dylan433447** [comment]
I tried using two of them and now it works one for dos pursuit and other for ap

**Comment by xpz3** [comment]
Without deauth working, dos pursuit is not of any use. So you better buy a compatible adapter or run deauth using the second adapter you currently have and skip dos pursuit.
