### ISSUE TITLE
Replace dsniff with a modern supported alternative

### ISSUE THREAD

**Issue by blshkv** [v1s1t0r1sh3r3/airgeddon#422]
dsniff was written back in 2000, 21 years ago. It were no updates since then and each linux distribution has to patch it with more and more patches every year. Currently, debian has 35 unofficial patches written by random people. These patches fix critical functionality such pcap reading, 64-bit support, segfault, openssl, spoofing and so on. The list is insane.

Please replace it with a better supported alternative like https://github.com/Ettercap/ettercap

https://github.com/pentoo/pentoo-overlay/issues/700

**Comment by OscarAkaElvis** [comment]
thanks for the advice but while dnsiff package is still on main repos (pentoo, kali, parrot, blackarch, etc) is pointless for us to replace it. It fits its functionality very well. We are not using any of the features you enumerated. We are using it exclusively for the dns blackhole on the evil twin captive portal attack. And as I said, it work like a charm for that... so is enough. No need of changes. Thanks anyway.

**Comment by blshkv** [comment]
We are trying to convince upstreams like your self to provide alternative option.  SET, for example, gives two options dniff or ettercap. 
Dsniff is hard to support and I have just killed dsniff from pentoo.

Please reconsider

**Comment by OscarAkaElvis** [comment]
omg, really? you removed dsniff from pentoo? .... hmmm.... that will cause trouble for us... no doubt about it.

Ok, ettercap is already a dependency on airgeddon so it can be used instead... do you think we can do the dns blackhole using that? we need a tool (a popular one, existing in all main distros repos) to perform that task... we'll dig into this... but I must say that to remove tools is not a good idea... is my humble opinion. Anyway, thanks for alerting us about it. I'll check with @ZeroChaos- on our Discord channel where he is pretty active.

**Comment by OscarAkaElvis** [comment]
This is done... dsniff was replaced by dnsmasq. It will be released on next v10.41. Closing.

**Comment by blshkv** [comment]
great work, thanks!
