### ISSUE TITLE
Invalid request-line

### ISSUE THREAD

**Issue by hartotarigan** [v1s1t0r1sh3r3/airgeddon#423]
![index](https://user-images.githubusercontent.com/43029885/107209770-2b5aa280-69fb-11eb-9395-4e04abea4faf.jpeg)

**Comment by hartotarigan** [comment]
and login pages do not appear

**Comment by OscarAkaElvis** [comment]
Sorry but without data is impossible to help you. You need to fill correctly the issue creation template telling to us your airgeddon version, your Linux distribution, chipset of your card, etc... any issue created without filling it correctly will be closed immediately as you can see.
