### ISSUE TITLE
Captive Portal Not Working

### ISSUE THREAD

**Issue by MikzG** [v1s1t0r1sh3r3/airgeddon#426]
So when I installed airgeddon the evil twin attack with captive portal was working but after I installed some plugins from (https://github.com/KeyofBlueS/airgeddon-plugins) I doesnt show when I launch the attack like it connects to the fake network but the captive portal doesnt show! 
I already tried to reinstall airgeddon without the plugins

**Comment by xpz3** [comment]
It could be just a coincidence. And since you haven't filled the issue template, we can't help you. So for further discussion join airgeddon discord channel and provide details regarding your setup, relevant screenshot etc..
https://discord.gg/sQ9dgt9
