### ISSUE TITLE
Interface Disabled (AP) and immediatly reconnected, after that: handle_probe_req: send_failed

### ISSUE THREAD

**Issue by Ewwwer** [v1s1t0r1sh3r3/airgeddon#427]
#### What is your airgeddon version?
V10.40

#### What is your Linux O.S. and which version?
Kali Arm Linux

#### Which is the chipset of your wireless card?
RT5370

#### Describe the issue and the steps to reproduce it
Hi, first of all thanks for have creating this tool and share with us, is fantastic!
Problem:
I can start normally the Twin Evil Ap attack with captive portal and all works well. After 2 - 5 minutes it's running i get the error in AP window wlan0: INTERFACE-DISABLED and immediately wlan0: INTERFACE-ENABLED.
After that i get multiples errors of handle_probe_req: send fail and the evil twin BBSID still up but i can't join in it.
I've try to find "cards & chipset" in wiki but i cannot find mine, maybe can i change something for make it works?
It seems like the card fall in standby mode but immediately wake up.
Any solution? i have not seen anything in close issues.

Thanks a lot

![IMG_1103](https://user-images.githubusercontent.com/48954179/108827171-2f6eee80-75bd-11eb-9c2f-ea7c83b3fca8.jpg)

**Comment by xpz3** [comment]
Run `airmon-ng check kill` before running airgeddon. Or judo clone the dev branch of airgeddon. Join discord for further questions.
https://discord.gg/sQ9dgt9
