### ISSUE TITLE
no attempts on captive portal

### ISSUE THREAD

**Issue by xxx9** [v1s1t0r1sh3r3/airgeddon#428]
What minimum signal is required for a successful captive portal attack? Everything goes well, fake site appears, de-auth window pops up, no errors but I've never had any attempts.

**Comment by OscarAkaElvis** [comment]
There is a social engineering human factor there. It is impossible to control. If the victim decides to don't trust the new network, there is nothing to do.

Please, for further discussion join to our discord channel.
https://discord.gg/sQ9dgt9
