### ISSUE TITLE
Intel Wifi Link 5150

### ISSUE THREAD

**Issue by SCCOBN** [v1s1t0r1sh3r3/airgeddon#429]
What's up. This is kind of bug and kind of not bug, and kind of new feature. Basically this card, Intel Wifi Link 5150 - 512agx-hru. This card is finicky but I love it. I was able to modify firmware and get txpower of 36. It does pixiewps better than my other cards (all of them atheros). There is a special method putting it into monitor and changing it's mac.

To put it into monitor you have to bring down the interface.

ifconfig wlan0 down
airmon-ng start wlan0
macchanger -r wlan0
ifconfig wlan0 up

At that, notice, interface name does not change to wlan0mon, it stays wlan0..

Card works, and you can crack pixiewps and do other stuff using wifite2.

However, here where problems with airgeddon arise. Because it does not change its name and because it has finicky ways about it, airgeddon can not put it into into monitor mode. Thus this is the problem. 

Perhaps you can do something with the code to recognize this card and change the way things are put into monitor mode, or perhaps you can give me line number so I can modify it myself??

**Comment by OscarAkaElvis** [comment]
Hello. In first place, you didn't fill the issue creation template... for that, we'll close the issue. Anyway, I can tell you some stuff.

1. We are not developing stuff for specific cards. As we know there are "two kind of cards". One able to set mode just using airmon-ng and other which are treated different, but your card seems pretty different. Maybe due the weird driver. 
2. Anyway, if you know your card is a weird card and you know how to change mode out of airgeddon, you can use for basic operations. I guess your card is not supporting VIF (Multiple Virtual Interface), so you won't be able to perform Evil Twin attacks deauthing at the same time that creating fake AP. Try to get a better usb card. Check our wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
3. Join discord channel for further discussion: https://discord.gg/sQ9dgt9
