### ISSUE TITLE
tplink wn722 v2

### ISSUE THREAD

**Issue by kissmorning** [v1s1t0r1sh3r3/airgeddon#431]
Although I installed the patch for wn722 v2, tp-link is not working properly. injection and listening mode is working. I caught a handshake with Airgeddon. After this stage, it doesn't work properly. What is your solution suggestion?

**Comment by cjb900** [comment]
There is no solution for that adapter. My guess with the patch you installed is you just got AP working. But that adapter does not support VIF which is needed to be able to deauth and create the fake AP at the same time and there is no patch i know of to get that to work. You will have to get a new adapter supported adapter/chipset. A list of supported adapter/chipsets can be found here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by kissmorning** [comment]
Realtek fix in wiki section doesn't work?

**Comment by cjb900** [comment]
No the chipset in that adapter as i mentioned does not support VIF. The fix on the wiki does not give the adapter VIP support. There is no fix for this that i have seen anyone find that will give this adapter VIF support. You are better off getting a new adapter from the link i shared before.

**Comment by kissmorning** [comment]
thank you so much

**Comment by Hood39** [comment]
Yo sup I know how to make it work. Like I was trying twin attack with it but the deauth don't work so I open another terminal and type sudo airodump-ng -w hack1  -c (channel) --bssid (Mac address) wlan0mon. And it work

**Comment by xpz3** [comment]
Yes but then the ap will fail..

> Yo sup I know how to make it work. Like I was trying twin attack with it but the deauth don't work so I open another terminal and type sudo airodump-ng -w hack1 -c (channel) --bssid (Mac address) wlan0mon. And it work

But then the ap wont work

**Comment by OscarAkaElvis** [comment]
yes, it will fail. That card is blacklisted and is not VIF capable: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

**Comment by Hood39** [comment]
Oh yeah, now I see. Thanks but it's not that big deal I have a deauther which can deauth for me.
