### ISSUE TITLE
Evil Twin with captive portal - questionmarks in passwords don't get recognized

### ISSUE THREAD

**Issue by metzgerchristian** [v1s1t0r1sh3r3/airgeddon#432]
#### What is your airgeddon version?

v10.41

#### What is your Linux O.S. and which version?

Kali 2021.1

#### Which is the chipset of your wireless card?

TP-Link Archer T3U [Realtek RTL8812BU]

#### Describe the issue and the steps to reproduce it

I'm doing the Evil-Twin AP Attack with captive portal and I noticed, if i enter my wifi password inside the captive portal the "?" doesn't get recognized. So if my password is eg. "test12345?!" and I enter it, the top right xterm window with the attempts, shows me "test12345!" as entered password. So I guess questionmarks don't get recognized correct when they are a part of the wifi password.

**Comment by OscarAkaElvis** [comment]
I'll check this. Thanks for the report.

**Comment by KeyofBlueS** [comment]
Aren't *&/?<> characters disabled for security reasons? See https://github.com/v1s1t0r1sh3r3/airgeddon/issues/184#issuecomment-432129343

**Comment by OscarAkaElvis** [comment]
Oh yes... I totally forgot it... it was developed a lot of time ago, and that issue is from 2 years ago. That's true. It is completely intentional. Anyway, using plugins system is pretty easy to hook that function to remove that security feature if we want that special chars on password. Just overwrite that function removing the two lines which are doing it.

Thanks @KeyofBlueS .

**Comment by metzgerchristian** [comment]
Thanks for the info @KeyofBlueS , I didn‘t went that far back in the issue history.

**Comment by xpz3** [comment]
> Thanks for the info @KeyofBlueS , I didn‘t went that far back in the issue history.


@KeyofBlueS has a plugin to overcome this issue. Check out his git

**Comment by OscarAkaElvis** [comment]
Yeah, awesome plugins page, the best I saw... already linked on [Plugins Hall of Fame](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Hall%20of%20Fame) at airgeddon's wiki. Anyway, some plugins need to be updated to add new strings for new languages like arabic.

**Comment by OscarAkaElvis** [comment]
I created a plugin exactly for this: https://github.com/OscarAkaElvis/airgeddon-plugins
