### ISSUE TITLE
[Feature] Search-That-Hash Support

### ISSUE THREAD

**Issue by zero77** [v1s1t0r1sh3r3/airgeddon#433]
#### Describe the feature or compatibility enhancement and involved versions if apply

Please add support for [Search-That-Hash](https://github.com/HashPals/Search-That-Hash) and instead of direct hash cracking pass all hashes to [Search-That-Hash](https://github.com/HashPals/Search-That-Hash).

#### What are the benefits of adding this?

This has the potential to speed up hash cracking for both individual users and the community in general. As already known hashes will not be cracked twice and hopefully newly cracked hashes will only need cracking once.

![Screenshot_2021-04-21 HashPals Search-That-Hash](https://user-images.githubusercontent.com/16563034/115551738-0310df00-a29b-11eb-82d4-23bb5638a299.png)

**Comment by OscarAkaElvis** [comment]
Thanks for the suggestion. Anyway, this sounds to me more like a developable plugin. Are you interested in developing it? It is very easy using the plugins system: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20System
