### ISSUE TITLE
support airmon-ng not making new interfaces

### ISSUE THREAD

**Issue by ZeroChaos-** [v1s1t0r1sh3r3/airgeddon#434]
airmon-ng prefers to make new vifs, but if the hardware doesn't support that, it doesn't.

To determine this, airmon-ng performs the following check:
```
iw phy ${PHYDEV} info | grep -q 'interface combinations are not supported'
```
Airgeddon could perform the same check to easily predict airmon-ng's behavior

**Comment by OscarAkaElvis** [comment]
Hi @ZeroChaos- , I'd like to ask to you some stuff referring this. If you don't mind we can do it on Discord in private messages to understand exactly this. Thanks.

**Comment by raioramalho** [comment]
you can use this for create a new wlan interface. 
https://github.com/raioramalho/virtualmon

**Comment by OscarAkaElvis** [comment]
If your card (hardware) doesn't support VIF (Virtual Interface), this script is not going to do that support it.
