### ISSUE TITLE
airgeddon interface selection missing

### ISSUE THREAD

**Issue by zerocoma** [v1s1t0r1sh3r3/airgeddon#435]
#### What is your airgeddon version?

10.41
#### What is your Linux O.S. and which version?

kali linux 2021.1
#### Which is the chipset of your wireless card?

Intel corporation 82540EM
#### Describe the issue and the steps to reproduce it

When selecting the interface, no options other than eth0 are displayed and the interface eth0 dosen't support monitor mode What can I do to solve this problem
thanks a lot

**Comment by cjb900** [comment]
That Intel corporation 82540EM is an Ethernet card not a wireless one. You will need a wifi adapter that supports monitor mode, AP mode and VIF to properly use airgeddon. You can find a list of supported adapters/chipsets that will work with airgeddon here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by zerocoma** [comment]
I'm connected to my wifi network right now!!

**Comment by cjb900** [comment]
if airgeddon is not detecting your wireless adapter than you are either using a VM which is not able to use the internal wireless card or the wireless card you have is not properly supported for wifi hacking. meaning you will have to get a new one from the link i provided before

**Comment by zerocoma** [comment]
I'm using orcal VM virtualbox

**Comment by cjb900** [comment]
Yes VM are not capable of using internal wifi adapters in computer and there is no way to get them to use the internal wifi adapter. You need a USB wifi adapter to be able to get wifi in a VM.

**Comment by zerocoma** [comment]
thanks for your help
