### ISSUE TITLE
old routers

### ISSUE THREAD

**Issue by tkrym02** [v1s1t0r1sh3r3/airgeddon#436]
hello i like this tool so much but there is 2 router used in all my county so i hope to support it in wps or any thing can get the password and this 2 routers is ZXHN H108N and hg531 v1
Thanks

**Comment by cjb900** [comment]
If the routers are not vulnerable to the WPS option already in airgeddon there isn't much more you can do. Unless you are able to find a list of default WPS pins for those routers to then add to airgeddon. Your best option would be an evil twin attack.
