### ISSUE TITLE
I guess it starting to work. Sometimes is better to rebbot, re-plug usb wireless interfaces, try again before posting issue. 😄

### ISSUE THREAD

**Issue by VladSabra** [v1s1t0r1sh3r3/airgeddon#437]
Please Help I tried everything I use Parrot Os .... When i open airgeddon i select my interface then i set it to monitor mode then i launch a handshake(option 5) then i press explore for targets(number 4 in airgeddon menu) a new terminal opens but no targets show even though im using 2.4 ghz and my wifi is 2.4 ghz. I also tried killing check to avoid conflicts still same problem On my network in the virtual machine i have wifi enabled and it says wired connection 1 i went to setting on parrot os virtual machine and set my usb router to remote network still the same issue i tried evil twin attack still nothing shows when exploring for targets. Also rather than showing the name wlan0 it shows as wlx00ea67c0a18 I also tried using aircrack same thing happens.

**Comment by OscarAkaElvis** [comment]
Spam? duplicate of #438 . Don't open two issues at the same time saying the same please, or you'll be banned.
