### ISSUE TITLE
Can't do the evin twin attack ...!!!

### ISSUE THREAD

**Issue by kevinjohn9812** [v1s1t0r1sh3r3/airgeddon#439]
After selecting the language in the evil twin attack .. I'm facing this error...

The interface changed its name while setting in managed mode. Autoselected 

./airgeddon.sh: line 9180: /sys/class/net//address: No such file or directory
./airgeddon.sh: line 9185: original_macs["${1}"]: bad array subscript

Please help...!!!

![Screenshot_2021-06-05_14_39_00](https://user-images.githubusercontent.com/52753422/120886617-85b3ea80-c60c-11eb-84d9-c14a46f98737.png)

**Comment by xpz3** [comment]
You have not filed the issue template properly. So we won't be able to help you without the bedded information. Most likely you have an unsupported wifi chipset. For further discussion, join airgeddon discord channel. https://discord.gg/sQ9dgt9

**Comment by messaouddhia** [comment]
Same problem

**Comment by OscarAkaElvis** [comment]
say "same problem" is like say nothing without providing the needed info. join discord or create an issue filling up ALL the needed info. Discord is better option... faster responses, more people helping, etc

**Comment by raghav29102008** [comment]
Hey,i also have the same problem while running evil twin with captive portal

**Comment by OscarAkaElvis** [comment]
I think you didn't read my last comment... just adding "same to me" is not helping at all. Can you provide data?? OS? chipset of your card? anything useful or just complaining?
