### ISSUE TITLE
airgeddon.sh: line 12338: /tmp/nws-01.csv: No such file or directory

### ISSUE THREAD

**Issue by McFarTech** [v1s1t0r1sh3r3/airgeddon#441]
#### What is your airgeddon version?

airgeddon-2463.7eba4f6-1

#### What is your Linux O.S. and which version?

BlackArch Slim 2021.03.01

#### Which is the chipset of your wireless card?

Chipset: Qualcomm Atheros Communications AR9271 802.11n

#### Describe the issue and the steps to reproduce it

I am able to select my wireless card. I am able to put it in to monitor mode but when i explore for targets i see the following message. 

**************************** Exploring for targets ***************************** 
Exploring for targets option chosen (monitor mode needed) 

Selected interface wlan1mon is in monitor mode. Exploration can be performed 

WPA/WPA2 filter enabled in scan. When started, press [Ctrl+C] to stop... 
Press [Enter] key to continue...
airgeddon.sh: line 12338: /tmp/nws-01.csv: No such file or directory

No networks found 
Press [Enter] key to continue...

**Comment by OscarAkaElvis** [comment]
It seems that the scanning window is not opening for you for some reason. Try to launch `xhosts +` before launching airgeddon.

Anyway, I don't know what airgeddon version you have. It should be v10.41 or similar... You can check it on first screen while flying saucer is shown or on about and credits menu. Let us know.

Feel free to join to discord channel for further discussion. Invitation link is on wiki at contact section.

**Comment by McFarTech** [comment]
Hi mate. yep v10.41 is what i am running

**Comment by McFarTech** [comment]
Assuming i am doing this right. xhost + then running airgeddon script but produces the same result / error

**Comment by xpz3** [comment]
Try using tmux instead of xterm. You can change that in options menu

**Comment by McFarTech** [comment]
Can you explain the steps. Never actually done that before

**Comment by xpz3** [comment]
Read wiki

**Comment by McFarTech** [comment]
Thanks!

**Comment by OscarAkaElvis** [comment]
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

You can do it from options menu, launching "on the fly" params when launch airgeddon or editing .airgeddonrc file. The link is showing it.

**Comment by OscarAkaElvis** [comment]
Let us know if finally tmux method worked for you. Otherwise without more information we'll close the issue in some days.
