### ISSUE TITLE
Got error while attempting Evil twin attack with airgiddon

### ISSUE THREAD

**Issue by jeevan572** [v1s1t0r1sh3r3/airgeddon#443]
[SAVE_20210702_103323](https://user-images.githubusercontent.com/86725638/124222174-f7eef080-db20-11eb-8c9d-b7a5a98a9969.jpg)
Got error while attempting Evil twin attack with airgiddon.

**Comment by xpz3** [comment]
This isn't the way you are supposed to open an issue. You didn't fill up the issue template making it hard for us to help you. Join airgeddon discord channel for easier rectification of issues. https://discord.gg/sQ9dgt9
Closing...
