### ISSUE TITLE
error while attempting hacking on  my wifi with airgiddon with evil twin attack

### ISSUE THREAD

**Issue by jeevan572** [v1s1t0r1sh3r3/airgeddon#444]
#### What is your airgeddon version?

6.9

#### What is your Linux O.S. and which version?

2021.1

#### Which is the chipset of your wireless card?
Model ; bl-wn155a

#### Describe the issue and the steps to reproduce it
[Screenshot 2021-07-01 205240](https://user-images.githubusercontent.com/86725638/124229759-f4c51780-dac2-11eb-89f3-507099b9f9e8.jpg)

**Comment by xpz3** [comment]
I think your card has mt7601 chipset which is unsupported for airgeddon. You can try downloading airgeddon from the dev branch and see if it works or not. If not, you need to buy a compatible card.
```git clone https://github.com/v1s1t0r1sh3r3/airgeddon/ -b dev airgeddondev && cd airgeddondev && bash airgeddon.sh```

**Comment by OscarAkaElvis** [comment]
Check supported cards here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by jeevan572** [comment]
@xpz3  bro do you have any information about other tool in Kali which is compatible with this adapter and can attempt speed brut force attack.
           -_- your advice could save my day

**Comment by jeevan572** [comment]
@xpz3 bro can I do attempt hacking with this adapter on WiFi networks with other tool not a distonary attck I need tool which is compatible with this adapter and can do brut force attack or man in middle attack.

      Your help could save my day 🙁

**Comment by jeevan572** [comment]
> 6.9 is not airgeddon version. Its the version of some other tool you are using. I think your card has mt7601 chipset which is unsupported for airgeddon. You can try downloading airgeddon from the dev branch and see if it works or not. If not, you need to buy a compatible card.
> `git clone https://github.com/v1s1t0r1sh3r3/airgeddon/ -b dev airgeddondev && cd airgeddondev && bash airgeddon.sh`

@xpz3 bro can I do attempt hacking with this adapter on WiFi networks with other tool in Kali but not a distonary attck

**Comment by OscarAkaElvis** [comment]
@jeevan572 please, stop spamming issues or you'll be banned from here. Please stop asking for other tools here. Here is not the place to do that. Join Discord and maybe in #offtopic channel somebody could help you.
