### ISSUE TITLE
an invalid --bssid or -essid was provid

### ISSUE THREAD

**Issue by skar4444** [v1s1t0r1sh3r3/airgeddon#445]
#### What is your airgeddon version?

v10.41 

#### What is your Linux O.S. and which version?

Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2021.2
Codename:       kali-rolling

#### Which is the chipset of your wireless card?

Tplink

#### Describe the issue and the steps to reproduce it

Once I start the attack (7) then showing this error.
![image](https://user-images.githubusercontent.com/43452298/125164026-b22fc900-e1ad-11eb-8aba-53927c567767.png)

**Comment by OscarAkaElvis** [comment]
Can't reproduce your problem... tested on same airgeddon version v10.41, using same bully version /v1.40-00) and the attack is performed for me (even if finally the target is not vulnerable which is the most likely nowadays).

![image](https://user-images.githubusercontent.com/5803348/125168872-ddafb500-e1a7-11eb-840c-838152c99380.png)

Did you test over other targets? what is the result? is happening to you only on that target network?

**Comment by OscarAkaElvis** [comment]
I tested over different of my networks and in all of them is working for me... tested using differentd O.S. (Parrot, Kali, etc). Tested using different cards.

Is the problem only on bully pixie dust attack or in any bully attack?

Can you test out of airgeddon?  The command that airgeddon is using is this:

`bully wlan0mon -b 00:00:00:00:00:11 -c 1 -d -v`

Remember to change the params to fit your card (wlan0mon in my case), your BSSID target, channel (1 in my case) and if is a 5ghz target (channel >36) don't for get to add param -5 but based on your screenshot I think you don't need it.

**Comment by OscarAkaElvis** [comment]
Closing due lack of response
