### ISSUE TITLE
interface resets after setting monitor mode

### ISSUE THREAD

**Issue by Bogdan107** [v1s1t0r1sh3r3/airgeddon#447]
#### What is your airgeddon version?

10.41

#### Describe the issue and the steps to reproduce it

Steps to reproduce bug:
1) Start program. Program say "Press Enter" and "Select an interface".
2) Select interface wlan1. Program say "Interface wlan1 selected. Mode: Managed. Supported bands: 2.4Ghz".
3) Select "Put interface in monitor mode". Program say "Interface wlan1 now in monitor mode" and next screen say "Interface enabled selected. Mode: (Non wifi card)". E.g. - intreface selection resets in program.
4) Now, I need to select "Select another network interface" to activate interface in program.

Expected results:
In step 3, after switching to Monitor mode, interface selection must stay on wlan1 interface.

**Comment by OscarAkaElvis** [comment]
You omitted a VERY IMPORTANT data here... what is your card and chipset? any screenshot could help

**Comment by Bogdan107** [comment]
> You omitted a VERY IMPORTANT data here... what is your card and chipset? any screenshot could help

Is it has any sence, if "current selected interface" is stored in airgeddon local variable?

Your "ommited a very important data" looks like an attempt to collect marketing data - not as interest in bug resolving.
**I disable to use info from my report in any way, other than bug resolving.**

Bug reproduced Always in system with:
1) integrated module: Realtek Semiconductor Co., Ltd. RTL8822CE;
2) extrernal USB-dongle: Ralink Technology, Corp. MT7601U Wireless Adapter.

With each of those cards, airgeddon have the same issue: airgeddon lose cursor of current selected interface after switching mode from Managed to Monitor. This bug manifests itself after each action of switching interface mode from Managed to Monitor - at program startup initiation or after active program usage.

**Comment by xpz3** [comment]
> > You omitted a VERY IMPORTANT data here... what is your card and chipset? any screenshot could help
> 
> Is it has any sence, if "current selected interface" is stored in airgeddon local variable?
> 
> Your "ommited a very important data" looks like an attempt to collect marketing data - not as interest in bug resolving.
> **I disable to use info from my report in any way, other than bug resolving.**
> 
> Bug reproduced Always in system with:
> 
> 1. integrated module: Realtek Semiconductor Co., Ltd. RTL8822CE;
> 2. extrernal USB-dongle: Ralink Technology, Corp. MT7601U Wireless Adapter.
> 
> With each of those cards, airgeddon have the same issue: airgeddon lose cursor of current selected interface after switching mode from Managed to Monitor. This bug manifests itself after each action of switching interface mode from Managed to Monitor - at program startup initiation or after active program usage.

Marketing data!! Seriously? If you have gone through previous issues or atleast read the wiki page, you could have known yourself that both the cards you use are not supported for airgeddon or similar tools to run captive portal attack. Both of them lack a necessary feature called `virtual interface` which is required for captive portal attack. The mt7601 lacks even the ap mode. You did not research about the problem yourself by either googling or searching recent issues and when we ask you for your chipset you are blaming us for collecting marketing data!!

**Comment by xpz3** [comment]
[https://github.com/xpz3/airgeddonplugins](https://github.com/xpz3/airgeddonplugins)
This page has a plugin called multint.sh. Since you have 2 cards, if one of them support master mode and the other one support monitor mode, you can use this plugin to use two cards with airgeddon-one for ap and other one for deauth..
If you want to use airgeddon with a single card you must buy a card with supported chipset. Read wiki for a small list of tested working cards/chipsets

**Comment by Bogdan107** [comment]
airgeddon can be used even for use cases, where harware interface can no support all features, which airgeddon support.
This is not problem for me.

The mechanism for "mode switching" is always the same in all use cases: switching between Managed and Monitor modes - and nothing more.
Any additional interface functions, such as "virtual interface", are used in additional airgeddon modes (captive portal attack or something else), and not for general purposes. So why does airgeddon require hardware support for these advanced features to work "as expected", even if I don't need to use this hardware features? I think that airgeddon does not need its functions and should work correctly even without them. And resetting the "current interface" in my case - is a bug of application, not a bug of instruments selection.

In my case, the "mode switching" mechanism does not work as intuitively expected.

I argee, that info about Manufacturer/Model help you to detect problem place in airgeddon code.

**Comment by xpz3** [comment]
On the plugins page I posted above you can see avoid_airmon.sh plugin. Use that and see if the interface mode switching works without issue or not

**Comment by Bogdan107** [comment]
> On the plugins page I posted above you can see avoid_airmon.sh plugin. Use that and see if the interface mode switching works without issue or not

I have plugins activated and file _avoid_airmon.sh_ downloaded to _/usr/share/airgeddon/plugins_, and then switching mode function works correctly - current interface cursor restored after switching interface mode!

Can this plugin be enabled by default and automatically disabled in modes where the hardware "virtual interface" function is actually required?

**Comment by xpz3** [comment]
Airmon-ng handles rtlxxxx cards not like any other cards. So if airgeddon chooses airmon-ng to switch interface mode, its going to create prob on any attack within airgeddon. So you can use the plugin for any attack in airgeddon. If you want to disable it for specific attack, you need to modify the plugin..

**Comment by OscarAkaElvis** [comment]
`Your "ommited a very important data" looks like an attempt to collect marketing data` <- 🙄  no comments...

You can find the list of supported cards and the cards which are "blacklisted" at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

`So why does airgeddon require hardware support for these advanced features`  <- you the answer also in FAQ section at wiki explaining you why this feature is used: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#my-fake-ap-is-not-working-on-any-evil-twin-attack-why

A solution for people who have these kind of non-supported cards is the plugin @xpz3 told you. I'll close this. Any other comment at Discord channel (invitation link is in contact section at wiki)

**Comment by Bogdan107** [comment]
> you the answer also in FAQ section at wiki explaining you why this feature is used: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#my-fake-ap-is-not-working-on-any-evil-twin-attack-why

My use case - just WPS attak - not Evil-Twin or any other, and does not require virtual interface mode in hardware.
Problem from my use case is not represented in FAQ.
"Change monitor mode" function, realized in airgeddon by default, has incorrect name. More reasonable name - "Add monitor mode to your main interface (VLAN require)", rather than "Put interface in monitor mode".

In my case:
```
iw list | grep "Supported interface modes" -A 8 
        Supported interface modes:
                 * managed
                 * monitor
--
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
```
But by default, mode switching function fails for each of adapter in single manner - by losing cursor of currently selected interface. And presented AP/VLAN feature has no effect to it.

> I'll close this
OK - this is not a program error. Now I know that this is a "feature" and program is not a user-frendly.

**Comment by xpz3** [comment]
> > you the answer also in FAQ section at wiki explaining you why this feature is used: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#my-fake-ap-is-not-working-on-any-evil-twin-attack-why
> 
> My use case - just WPS attak - not Evil-Twin or any other, and does not require virtual interface mode in hardware.
> Problem from my use case is not represented in FAQ.
> "Change monitor mode" function, realized in airgeddon by default, has incorrect name. More reasonable name - "Activate monitor mode on your main interface (VLAN require)", rather than "Put interface in monitor mode".

There are some cards that are fully supported for wifi attacks and some are partially supported or not supported at all. Airgeddon prefers to use airmon-ng for changing modes of it's supported and expects a certain interface name change from airmon. But some cards like the rtlxxxx are handled not like other cards. If you check airmon-ng source code you can see comment like `crap driver ` or something when it sees rtl cards.
So since the cards are supported by airmon-ng but in a different way, airgeddon doesn't get the expected output from airmon-ng. That's why it fails. There may be other cards like these as well. We cannot keep on adding support for all those. For this reason, we created a plugin for those few ppl with such cards.. I think from the next version of airgeddon, you'll get a warning for such cards.
