### ISSUE TITLE
script can't check for current wifi adapter status

### ISSUE THREAD

**Issue by sudo-WearTherinG** [v1s1t0r1sh3r3/airgeddon#449]
**[adapter monitor mode is up]**

(https://user-images.githubusercontent.com/60429981/126863101-4ad248b4-cd25-46ba-986c-384da0d2f133.png)
(https://user-images.githubusercontent.com/60429981/126863517-e569288d-ca71-455b-bc0d-5ef605017468.png) <-all detail

So my wifi adapter is Tp-link wn722n v3. I managed to get it running on monitor mode but unlike other adapter my adapter    name doesn't change to wlan0mon it stays on wlan0 unchanged but be sure monitor mode working.
So when i select option 9 < Evil Twin AP attack with captive portal (monitor mode needed) >
it says this error < This interface wlan0 is not in monitor mode  >
it's monitor mode is already up.

**Comment by xpz3** [comment]
This card has a chipset which is among the blacklisted cards for performing evil twin attacks as it lacks proper vif support. If you have two v3 cards, you can use a plugin that allows you to use one for ap and another one for deauth. https://github.com/xpz3/airgeddonplugins

The above page contains a plugin called multint.sh. Download and copy that to plugins folder of airgeddon if you have 2 cards. 
Join airgeddon discord channel for further questions.

**Comment by OscarAkaElvis** [comment]
Check the list of supported cards: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Closing.
