### ISSUE TITLE
cannot copy root terminal output

### ISSUE THREAD

**Issue by algreen702021** [v1s1t0r1sh3r3/airgeddon#455]
#### Describe the feature or compatibility enhancement and involved versions if apply

**Last just update release;  copy cmd from terminal output.** 

#### What are the benefits of adding this?

_**I'd like to copy text output from "Root terminal emulator" (I mean that with red X one on the bar); i.e. to execute pixie --force cmd.
Benefit it's execute code out of airgeddon to test results.
thanks**_

**Comment by OscarAkaElvis** [comment]
And really do you think that we can control what you do in your OS or in your terminal? I mean, airgeddon just use standard stdout and if you are not able to copy is not related to airgeddon. Use another terminal more friendly (terminator or any other). That terminal you are referring to even is not existing in the most of the linux. Not sure if you are using Parrot, Kali or what is the OS you are using (we should happily guess it), but in any case, this is not related to airgeddon. Closing.

**Comment by xpz3** [comment]
> #### Describe the feature or compatibility enhancement and involved versions if apply
> **Last just update release; copy cmd from terminal output.**
> 
> #### What are the benefits of adding this?
> _**I'd like to copy text output from "Root terminal emulator" (I mean that with red X one on the bar); i.e. to execute pixie --force cmd. Benefit it's execute code out of airgeddon to test results. thanks**_

Why don't you just use `ps`. You'll get the exact command from there

**Comment by algreen702021** [comment]
I'm using Kali 2021;  ps save an image and cannot copy a 400 chars long from screen manually. Have no idea why airgeddon open 2 different kind of terminal, Xroot and standard.  Anyway, thanks for response. Stay safe.

**Comment by xpz3** [comment]
> I'm using Kali 2021; ps save an image and cannot copy a 400 chars long from screen manually. Have no idea why airgeddon open 2 different kind of terminal, Xroot and standard. Anyway, thanks for response. Stay safe.

You can use ps aux | grep <process name> to get the command line.
Airgeddon needs to run multiple process for evil twin. So it's using xterm

**Comment by algreen702021** [comment]
Thanks but Xterm is read only. Appreciated.   :)

**Comment by algreen702021** [comment]
Last but not least, any chance to add to reaver bruteforce attack (10)  --delay parameter manually?

**Comment by xpz3** [comment]
> Last but not least, any chance to add to reaver bruteforce attack (10) --delay parameter manually?

You can either edit the source of airgeddon or use plugins system to do changes without editing airgeddon source.. https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Development

**Comment by xpz3** [comment]
> Thanks but Xterm is read only. Appreciated. :)

I didn't see this msg until now. I dont get what you mean by this statement. You said you wanted to copy some command line issued by airgeddon so that you can copy that and run it externally after modification..
For that i told you to grep the process list and it will give you the command line which is running inside xterm

**Comment by algreen702021** [comment]
Hi, just realize airgeddon create a 'output.txt' of the attack in /root/tmp/ of Kali 2021. It is what I was looking for. Thanks guys.
