### ISSUE TITLE
wireless adapter is not supporting VIF 

### ISSUE THREAD

**Issue by killer-bee-create** [v1s1t0r1sh3r3/airgeddon#456]
hello
i'm trying to launch airgeddon on kali linux but when its the moment to chose the evil twin attack after turning the adapter into monitor mode there is an error saying that my network adapter is not supporting VIF virtual interface despite that i have already checked kill any interferences 
![Screenshot_2021-08-20_13_17_36](https://user-images.githubusercontent.com/89270400/130270340-f5cb241d-dda4-4642-9340-eed47ecb5cad.png)

**Comment by OscarAkaElvis** [comment]
Error is pretty clear, don't you think? Is a controlled check to tell you that you need to buy a better adapter. Read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#my-fake-ap-is-not-working-on-any-evil-twin-attack-why

You can check the list of nice cards here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Read wiki before posting next time. Thanks.

**Comment by algreen702021** [comment]
I have a realtek does not supporting virtual interface but I guess it's adapter issue.
