### ISSUE TITLE
Hashcat using mode 2500 with hccapx over mode 22000 

### ISSUE THREAD

**Issue by clem9669** [v1s1t0r1sh3r3/airgeddon#460]
In the latest version, after getting a handshake and select cracking with hashcat. 

The cracking process start with a mode 2500 (WPA-EAPOL-PBKDF2), and a hccapx file.

However, it is mentioned in hashcat forums: https://hashcat.net/forum/thread-10253.html. The mode 2500/2501 and 16800/16801 are deprecated, as well as the file format hccapx.

**Comment by OscarAkaElvis** [comment]
Are you kidding me? We did a commit this morning before your issue to fix this 😄 

Here is the commit for the next v11.0: https://github.com/v1s1t0r1sh3r3/airgeddon/commit/c71d9ea2b1db78de3240c801e6d097b1ca8ce9d9

Anyway, thanks for alerting us.

Closing.
