### ISSUE TITLE
airgeddon on raspberry pi

### ISSUE THREAD

**Issue by ntoskrnl-exe** [v1s1t0r1sh3r3/airgeddon#461]
#### What is your airgeddon version?

10.42

#### What is your Linux O.S. and which version?

Kali Linux Rolling Release 2021.3 on raspberry pi 4 (64 bit version of kali).

#### Which is the chipset of your wireless card?

my wifi card is external running as wlan1. Atheros adapter.

#### Describe the issue and the steps to reproduce it

So I am starting to build a raspberry pi with kali linux for a remote hacking tool (drop it and run).
Want to set up an evil twin and use bettercap for sniffing.
The first problem is this, in my home environment, my target router is my own. No problems can configure airgeddon and the configuration is correctly created.
The problem is that bringing up the eviltwin - sometimes the target phone connects sometimes it does not. If it does connect there is no internet activity. sometimes the phone disassociates
So I decided to start bringing each component  up manually. Firstly, hostapd is more stable and appears to behave better than in the airgeddon process.
If I allowed the airgeddon to control the process, bettercap fails 9/10 with .cap script exiting with a status code 4.

I did briefly install airgeddon on my desktop (64bit amd kali linux build) and it looked more stable.

My suspicion is this is all driver and OS problems, however what is the best way for me to debug this to get it to work. I would like to get it work, if I can.

**Comment by OscarAkaElvis** [comment]
Yeah, it should work flawlessly. If is not working for you is probably because of something of your environment. If you want you can enable debug mode on the options file `.airgeddonrc` to see the name of the functions called.

You also can join discord channel to get help there.
