### ISSUE TITLE
Not reporting chipsets correctly

### ISSUE THREAD

**Issue by ntoskrnl-exe** [v1s1t0r1sh3r3/airgeddon#462]
#### Is your question related to any concrete technology?

Kali Linux Rolling
Version 2021.3

#### Describe your question as detailed as possible

I am trying to get airgeddon running on a RaspberryPI. I can run it on my desktop with no obvious issue.

The first issue I come against on the Rpi is when I select the interface to act as an evil twin.

I have onboard Ethernet
I have onboard Wireless
I have onboard bridge

I have a USB connected external wireless interface.

The 3 onboard devices are reported as unknown. The USB wireless interface is correctly reported as Qualcomm Atheros.

If I use my Desktop it correctly reports device manufacturer.

If I switch on debugging

"Select Interface to work with:"

1. eth0 Line:2621 set_chipset
// Chipset: Unknown
2. wlan0 Line:2621 set_chipset
// Chipset: Unknown
3. wlan1 Line:2621 set_chipset
Line: 2626 check_interface_wifi
Line: 2628 get_5ghz_band_info_from_phy_interface
// 2.4Ghz // Chipset: Qualcomm Atheros ...
4. br0 Line:2621 set_chipset
5. // Chipset: Unknown 

I have never had a problem with using eth0 or wlan0 outside of airgeddon.

This maybe just a display issue or maybe something more fundamental.

**Comment by OscarAkaElvis** [comment]
And what is the problem here? A card can be used in the same way if detected as unknown. It is just info. 

No Issue here. airgeddon gets what OS is providing. If is unknown is because OS is not showing it correctly due to drivers but airgeddon can't "invent" it. I think there is nothing that airgeddon can do here. And as I said before, it is just info.

**Comment by ntoskrnl-exe** [comment]
I apologize if i worded this incorrectly. I was merely trying to eliminate it as an "issue" as I progressing my way through the performing an evil twin attack

I was not suggesting to invent something - merely whether there is an issue. As you are saying this is not an issue, I have no reason other than than to take your comment at face value.

**Comment by OscarAkaElvis** [comment]
Ok. Join discord channel for further discussion.
