### ISSUE TITLE
I need Chinese service

### ISSUE THREAD

**Issue by yangyang1144** [v1s1t0r1sh3r3/airgeddon#464]

**Comment by yangyang1144** [comment]
I need Chinese service,I am very interested in your project and hope to add Chinese service

**Comment by OscarAkaElvis** [comment]
Do you mean that you are interested in collaborate translating airgeddon to chinese? You'll need to speak chinese natively, speak english fluently, and basic git knowledge. If you fit these requirements, please, contact our staff on Discord channel. Join at: https://discord.gg/sQ9dgt9

**Comment by OscarAkaElvis** [comment]
I must say that the chinese translation is done. Not released yet but you can see it at dev branch for the new 10.21 version.
