### ISSUE TITLE
issue with password capturing in airgeddon

### ISSUE THREAD

**Issue by kartik753** [v1s1t0r1sh3r3/airgeddon#469]
#### Is your question related to any concrete technology?

Airgeddon

#### Describe your question as detailed as possible

Hi team,

I face some issue while capturing password from evil twin attack capture portal in airgeddon. Suppose target wifi password is kartik*#*#  . Now, when i run evil twin attack in airgeddon and target enter password. Airgeddon will show kartik##, it miss the * . Please assist why it is missing * in the password

Thanks team

**Comment by cjb900** [comment]
You can download this file and put it into the plugin folder in airgeddon https://raw.githubusercontent.com/OscarAkaElvis/airgeddon-plugins/main/allchars_captiveportal.sh. This will allow the captive portal to then accept all special characters. For why some special characters are not allowed by default. There was some speculation that allowing all special characters there could be some type of injection that could then allow the attacker to get hacked.

**Comment by OscarAkaElvis** [comment]
Exactly. There is a plugin to allow that chars. Closing.
