### ISSUE TITLE
Locked menu option was chosen  Press [Enter] key to continue...

### ISSUE THREAD

**Issue by rohanraj-aipro** [v1s1t0r1sh3r3/airgeddon#470]

**Comment by cjb900** [comment]
How is anyone supposed to help here if you don't give any of the needed information we ask for when creating an issue?

**Comment by OscarAkaElvis** [comment]
Anyway, the unique reason to have a blocked option menu is because there are missing optional dependencies. But on the same line it is shown what is needed. So just need to read. Closing.

**Comment by rohanraj-aipro** [comment]
Thankyou ! I got it
