### ISSUE TITLE
Not work in sway

### ISSUE THREAD

**Issue by tuxarch** [v1s1t0r1sh3r3/airgeddon#474]
### No graphical X system found. If it already exists, check its functionality. This is important for airgeddon. Script cannot continue
Is this fixable without installing xorg?

**Comment by OscarAkaElvis** [comment]
You didn't fill the issue template needed to help you, so I'll close the issue. Anyway, read FAQ on wiki. Probably that problem is there... read read read please, before asking.

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting

**Comment by OscarAkaElvis** [comment]
Yes, you can use tmux instead of xterm. Read options

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options
