### ISSUE TITLE
Evil twin attack on dual band router

### ISSUE THREAD

**Issue by Jakarrrg** [v1s1t0r1sh3r3/airgeddon#486]
#### What is your airgeddon version?

v11.0

#### What is your Linux O.S. and which version?

Kali Linux 2022.1

#### Which is the chipset of your wireless card?

1)TP-LINK ARCHER T2U PLUS (RTL8811AU/RTL8812AU)
2)Ralink RT2870/RT3070

#### Describe the issue and the steps to reproduce it

Hello, I am trying to perform an evil twin attack on a dual band router. I am using two WiFi adapters. I tried using one of them for an evil attack on the 2.4GHz network (with the included mdk4 ddos attack), and then opened another terminal with airgeddon and tried to perform simultaneously a single second ddos attack with my second WiFi adapter on the 5GHz network. The outcome was that after the ddos attack on the 5GHz network started, the other ddos (from evil twin) attack also started attacking the 5GHz network, and not the 2.4GHz network it was attacking before. So, bottomline, is there any way to disconnect someone from both channels of dual band router while performing evil twin attack? I bought the second adapter for this reason and I am dissapointed by this outcome. I guessed that having two adapters should allow me performing two seperate ddos attacks to two different targets at the same time.

**Comment by cjb900** [comment]
This is not possible because the chipset being used for the evil twin attack (Ralink RT2870/RT3070) is only capable of seeing/attacking 2.4ghz bands only as the hardware only supports 2.4ghz. it would have no way to deauth a 5ghz band. Also, others have used 2 instances of airgeddon like this before (can't say if any of them had the same adapter/chipsets you do) and none of them have mentioned this issue. I have also tested this just now and starting a second instance of airgeddon does not change anything on my end with the deauthing in the evil twin attack.

**Comment by Jakarrrg** [comment]
With my Ralink RT2870/RT3070 adapter I attack the 2.4 band network and create the evil twin. I use the TP-LINK ARCHER T2U PLUS (RTL8811AU/RTL8812AU) only to deauth the 5GHz band network, so I should be capable of creating an evil network as well deauthing on both bands. I also just tried running the deauth to the 5GHz network from fluxion (through the handshake attack option) and it worked fine. I have reproduced this on airgeddon multiple times and always happens what I described. Both deauth attacks end up targeting the same network. I even tried running the first airgeddon session on one Kali account and the second on another.

**Comment by xpz3** [comment]
Try this.. Clone airgeddon master branch on a different folder and then download this file and replace it in the new folder. Then run the 2nd instance of airgeddon from this new folder with replaced airgeddon.sh file and perform deauth on 5ghz using that.. Use deauth feok DoS attacks menu.. https://www.filemail.com/d/dzpgrzwwnvmgpws

**Comment by xpz3** [comment]
Please join discord if the issue persists.. https://discord.gg/sQ9dgt9

**Comment by Jakarrrg** [comment]
First of all thank you both for your interrest. I tried your steps. There is an error when trying to start deauth attack: "airgeddon.sh: line 4528: /tmp/2/bl.txt: No such file or directory"

**Comment by OscarAkaElvis** [comment]
hi @Jakarrrg , there is no DDoS in airgeddon, just DoS. Distributed DoS is for botnets and that kind of things.

DoS is tricky, read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do

Please, continue the discussion/testing in Discord channel. I'll close this.

**Comment by xpz3** [comment]
> First of all thank you both for your interrest. I tried your steps. There is an error when trying to start deauth attack: "airgeddon.sh: line 4528: /tmp/2/bl.txt: No such file or directory"
> 
> * [ ]  Should I just try to remove the line from the file? *tried it , the same message appeared for another line, removed it too, then it didnt even start, so maybe I should try finding this/tmp/2/bl.txt file or is it vain?

From a terminal run `mkdir -p /tmp/2` then do as i said above
