### ISSUE TITLE
handshake save location

### ISSUE THREAD

**Issue by ayoparky1066** [v1s1t0r1sh3r3/airgeddon#489]
#### Describe your question as detailed as possible

Hi, this question has to do with the version of airgeddon that comes preinstalled in Parrot OS. Was curious what the file location is for saved handshake captures

**Comment by xpz3** [comment]
> #### Is your question related to any concrete technology?
> #### Describe your question as detailed as possible
> Hi, this question has to do with the version of airgeddon that comes preinstalled in Parrot OS. Was curious what the file location is for saved handshake captures

I think it's on the home dir of the current user..

**Comment by OscarAkaElvis** [comment]
@ayoparky1066 , what is the question? what do you want to know or what is the problem?

I can't see any clear question here. Closing. For further discussion join our Discord channel (invitation link is at wiki on contact section).

**Comment by ayoparky1066** [comment]
Weird. Anyways. In the version of airgeddon that comes prepackaged with the latest ParrotOS distro, I was hoping you would be kind enough to tell me the file location in the file manager of any captured handshakes captured via deauth or any other method. 

⁣Get BlueMail for Android ​

On Apr 12, 2022, 11:36 PM, at 11:36 PM, "Óscar Alfonso Díaz" ***@***.***> wrote:
***@***.*** , what is the question? what do you want to know or what

**Comment by ayoparky1066** [comment]
Hey....you know what....I'm sorry and I apologize for wasting your time. I should have directed this question at parrot os support and not you. I always forget about the open source nature of the programs engineers develop and that you don't have any control over what others choose to do with it.....

⁣Get BlueMail for Android ​

**Comment by OscarAkaElvis** [comment]
Don't worry but I'm not sure to understand the problem. I have a Parrot OS virtual machine using airgeddon installed by apt and everything looks normal. Can you put screenshots about your case? Is not there a step where airgeddon prompts to you about where to save the captured file???

I insist, join to discord. More people supporting there.
