### ISSUE TITLE
Showing too much WiFi interface..

### ISSUE THREAD

**Issue by BIPUTHEROCK** [v1s1t0r1sh3r3/airgeddon#496]
I am using Airgeddon with termux in Ubuntu...
Why does it shows that much interface? And wlan0 , swlan0 and I tried last 4 WiFi interface each one says it is not a WiFi card..
How can I get solution of this?

![Screenshot_20220520-165101_Termux](https://user-images.githubusercontent.com/61649091/169513396-54c20fb4-4eef-4899-b22d-1eaddece896f.jpg)

![Screenshot_20220520-165602_Termux](https://user-images.githubusercontent.com/61649091/169513884-3c23b7cd-a14c-4d48-8fde-aa61759c91e6.jpg)

**Comment by xpz3** [comment]
Airgeddon won't work on termux. You need to root your phone, install chroot custom kernel with wifi drivers etc to make it work..
