### ISSUE TITLE
does it support panda pau04

### ISSUE THREAD

**Issue by T3MRX** [v1s1t0r1sh3r3/airgeddon#497]
#### Is your question related to any concrete technology?

Yes

#### Describe your question as detailed as possible

I am buying panda pau04 as its shown as compatible in your wiki page https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets but when I search if it is compatible with packet injection most results just talks about the panda pau06 and nothing about panda pau04 which got me confused, can anyone please check if its actually compatible.

**Comment by cjb900** [comment]
Every wifi adapter/chipset in that list has at one time or another been tested and support all the modes needed to work with airgeddon. So yes that adapter supports packet injection. What would have helped your search is to not search the adapter name but search the chipset in it to get more in if it supports packet injection. You can verify that the chipset in the panda PAU04 which is the RT5370 supports packet injection here https://deviwiki.com/wiki/Wireless_adapters/Chipset_table

**Comment by OscarAkaElvis** [comment]
Yeah, it is compatible. Closing this.
