### ISSUE TITLE
Not supporting VIF

### ISSUE THREAD

**Issue by FrisKoo** [v1s1t0r1sh3r3/airgeddon#507]

**Comment by cjb900** [comment]
If your wifi adapter/chipset does not support VIF(the ability to split you card into 2 virtual interfaces so one can deauth and the other can create the fake AP) there is nothing anyone here can do other then recommend you get a better supported wifi adapter/chipset from here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets
