### ISSUE TITLE
It would be great if the network hiding WiFi name could be attacked by evil twins

### ISSUE THREAD

**Issue by QianSong1** [v1s1t0r1sh3r3/airgeddon#508]
#### Describe the feature or compatibility enhancement and involved versions if apply

Hello, boss!! Can you do a function to display the hidden SSIDs whose names are sniffed out after scanning the wifi list with the [airodump ng] tool. Then it can be used for evil twin attacks. In this way, the hidden WiFi can also be attacked, which is perfect

#### What are the benefits of adding this?

It would be great if the network hiding WiFi name could be attacked by evil twins

**Comment by cjb900** [comment]
Just sniffing near by AP does not have anyway to reveal the SSID of hidden AP. Only when if a client connects to the AP while scanning would the name be revealed.

**Comment by QianSong1** [comment]
Yes, I have scanned. It is true. As long as the scanning time is enough, there is a hidden name under the [probe]. Can you extract that name as an SSID. Then the evil twins can attack?

**Comment by OscarAkaElvis** [comment]
as cjb900 said, to reveal a hidden ssid just need to be listening while a legit client connects. That's a feature of airodump. Once you keep the scanning enough time and the hidden network is revealed, write down its ssid and you'll no need to do the same again, you can launch the attack and enter the data (ssid, channel and bssid) manually. So yes, it can be done, you only need to know the ssid and that is a question of time scanning. There is nothing we can do here, is something you must do... listen, wait, and write down the data once appeared.

Closing.

**Comment by QianSong1** [comment]
Hello, boss, can you add a judgment function after scanning? If the client list of the [dump-01. csv] file sniffs the hidden SSID, then use it for the evil twin attack. Otherwise, consider it a hidden network (not sniffed out)

(In the scanning phase, I will scan for enough time until I feel that I can sniff out the SSID, and then I will manually proceed to the next step)

**Comment by QianSong1** [comment]
That is, only when the SSID of the AP list and the [probed] SSID of the client list are empty, can we think that it is a real hidden SSID. In this way, the evil twins can attack the hidden AP that is sniffed out. It would be perfect if this could be done

**Comment by OscarAkaElvis** [comment]
I'm not understanding... as soon as while you scan it is shown, you can select it as target, so then you can launch the attack. No development action is needed.

**Comment by QianSong1** [comment]
But with the hidden WiFi, I can't create fake WiFi without SSID, so I can't wipe the network~~

**Comment by OscarAkaElvis** [comment]
not sure if you could be not understanding how it works. Yes, we can't launch the attack if we don't have the ssid, but you can get it if you scan enough time and you are lucky getting it from a client connecting to the legitimate network. But not sure what you need because if you get it, then you can launch the evil twin attack. What feature are you asking for????

**Comment by QianSong1** [comment]
That is, the first step of this software is to scan the wifi list. It will set the WiFi that hides the SSIDs to [Hide Network]. What I want is if the client list sniffs out the SSIDs and the AP list also has SSIDs. We will give priority to using the SSID of the AP list for evil twin attacks. If the SSID of the AP list is empty but the SSID of the client list is not empty (sniffed out), we will use the SSID of the client list for evil twin attacks. Otherwise, if the SSID of both lists is empty, we will consider that WiFi as [hidden network]

**Comment by QianSong1** [comment]
![image](https://user-images.githubusercontent.com/101644710/192254602-ff104386-7f1d-4c43-ab9d-d194c2a2f258.png)

**Comment by QianSong1** [comment]
I used your latest version of this software to sniff [Alma] at the first step, but after scanning, it still displays [Hidden Network]

**Comment by OscarAkaElvis** [comment]
I don't understand your point... why to give priority to decloaked networks? you should be free to choose any network... if it is decloaked due to legit client connecting while scanning, then you can see the data, select it and launch an attack.

If what you want is some kind of "state saving" to see in a while if a network is discovered to "mark" them as "decloaked network" or something like that.... hmm... maybe, but I think that can be done using the plugin system. Feel free to create it.

**Comment by QianSong1** [comment]
![image](https://user-images.githubusercontent.com/101644710/192311963-1dedc4b2-a718-458c-8011-d052978d5c81.png)
![image](https://user-images.githubusercontent.com/101644710/192312543-b1010809-a3f7-4030-adba-be2e85e99010.png)
Thank you for your answer. I modified the function I want according to your code

**Comment by QianSong1** [comment]
【Alma】It's a hidden network. I sniff it out, and then use this SSID to launch an evil twin attack to steal the network
