### ISSUE TITLE
Does it support the raspberry pi mini USB

### ISSUE THREAD

**Issue by T3MRX** [v1s1t0r1sh3r3/airgeddon#509]
Does it support the raspberry pi mini USB?

Chipset: RT5370N

**Comment by cjb900** [comment]
I'm not finding much information on that chipset. Being that the RT5370 is a known supported on for wifi hacking the RT5370N is probably an updated version of that adapter. Now whether it will work with the raspberry pi mini(which i assume you mean the raspberry pi zero) i can't say. You would have to find someone that has that chipset and uses it on the raspberry pi zero or just risk it and hope that it will work.

**Comment by OscarAkaElvis** [comment]
Let's ask this in Discord channel. https://discord.gg/sQ9dgt9
