### ISSUE TITLE
How to cycle tmux windows

### ISSUE THREAD

**Issue by usama7628674** [v1s1t0r1sh3r3/airgeddon#510]
![image](https://user-images.githubusercontent.com/29252277/193392189-574a7aa3-78a2-4206-82bd-c2494bd05634.png)

**Comment by cjb900** [comment]
tmux usage can be found here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options#about-tmux-usage

**Comment by usama7628674** [comment]
thanks @cjb900
