### ISSUE TITLE
airgeddon

### ISSUE THREAD

**Issue by jo-the** [v1s1t0r1sh3r3/airgeddon#511]
> 9

The interface wlan0 you have already selected is not supporting VIF (Virtual Interface). This attack needs it to virtually unfold itself to create the fake access point while also performing denial of service (DoS). Do you want to continue? If yes, the denial of service will not work being an important part of the attack and making it probably ineffective [y/N] 
> y

The port 53/tcp is being used by some program or process different than airgeddon (probably dnsmasq). The attack will not be able to be carried out because airgeddon needs that port to perform it. Please release the port by terminating the process that is causing the conflict in order to be able to perform this attack 
Press [Enter] key to continue...

**Comment by cjb900** [comment]
If the chipset in your wifi adapter does not support VIF you will not be able to use airgeddon with that adapter. At least not alone. You will either have to get a second adapter and use 2 adapter in airgeddon with this plugin https://github.com/xpz3/airgeddonplugins/blob/main/multint.sh or personally i would recommend getting a better supported adapter/chipset from here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets. 

regarding port 53 being in use you will have to find what ever is running on that port and stop it before starting airgeddon.
