### ISSUE TITLE
I suspect that android devices are blocking captive portal pages

### ISSUE THREAD

**Issue by czg123698741** [v1s1t0r1sh3r3/airgeddon#513]
Hello, I have been troubled by one thing recently. There are many Android mobile phone clients connecting to my fake WiFi, but I see that "webserver" has not been refreshed with relevant code information, just like the picture I showed, I once suspected Huawei's The Android system automatically blocked the captive portal page, or the captive portal page could not be loaded due to weak signal. But I did my own experimental test at home to be able to trigger the opening of the captive portal page. My phone is also a Huawei phone, and my device is Android 11.

![QQ截图20221010192724](https://user-images.githubusercontent.com/59021691/194858727-23d40d88-0ba6-4ec0-9d29-92d4f47f7336.png)

**Comment by OscarAkaElvis** [comment]
Everything seems to me like is working as expected. Your warning at webserver window is documented. It is related to this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#once-connected-to-the-evil-twin-fake-network-captive-portal-is-not-triggered-what-am-i-doing-wrong
