### ISSUE TITLE
How can I modify the source code so that the WiFi hotspot requires a password to connect to the WiFi hotspot

### ISSUE THREAD

**Issue by czg123698741** [v1s1t0r1sh3r3/airgeddon#514]
How can I modify the source code so that the WiFi hotspot requires a password to connect to the WiFi hotspot

**Comment by OscarAkaElvis** [comment]
Please. Before opening an issue, read the wiki. That is documented

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#can-be-the-evil-twin-captive-portal-page-be-customized-how

There are also so many issues asking the same. Take time to search before asking.

Consider to join discord server to keep asking things. If you open an issue fill correctly the issue creation template or you will be banned from the repo. Read read read.

**Comment by czg123698741** [comment]
> 请。在打开问题之前，请阅读wiki。这是记录在案的
> 
> https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#can-be-the-evil-twin-captive-portal-page-be-customized-how
> 
> 在了解问题之前花点时间搜索。
> 
> 考虑加入不和谐的服务器以继续调查问题。如果您打开一个，请正确创建模板，否则将被禁止进入 repo。读读读。

I have found no such problem, I mean, the fake WiFi I want to create, he needs to enter a password to connect to WiFi, because of the captive portal page, there are SSL security issues, some devices can't be opened, so I think One way is to create a fake WiFi with the same name, induce him to connect to it, and then I capture his WiFi password.
