### ISSUE TITLE
How to create a WiFi that requires password access, what code needs to be modified

### ISSUE THREAD

**Issue by czg123698741** [v1s1t0r1sh3r3/airgeddon#515]
I have found no such problem, I mean, the fake WiFi I want to create, he needs to enter a password to connect to WiFi, because of the captive portal page, there are SSL security issues, some devices can't be opened, so I think One way is to create a fake WiFi with the same name, induce him to connect to it, and then I capture his WiFi password.

![QQ截图20221011201345](https://user-images.githubusercontent.com/59021691/195086693-98870e29-8e8b-4b58-8293-6bcb5d7823f2.png)
![QQ截图20221011201402](https://user-images.githubusercontent.com/59021691/195086704-54e2b041-4348-4664-9d53-69b464e71fd0.png)

**Comment by OscarAkaElvis** [comment]
I warned you in the last issue. If you don't respect the rules and keep opening issues without filling up the issue creation template and asking basic things that are documented, you'll be banned. Here it is your ban.

By the way, I don't know what the hell are you doing... Fake network created by airgeddon doesn't need password to connect.
