### ISSUE TITLE
Enterprise Evil-Twin Attack SSL3 Error

### ISSUE THREAD

**Issue by lordgzar** [v1s1t0r1sh3r3/airgeddon#518]
#### What is your airgeddon version?

11.02

#### What is your Linux O.S. and which version?

Kali linux 2022.3 x64

#### Which is the chipset of your wireless card?

ALFA AWUS036NH

#### Describe the issue and the steps to reproduce it

when i try to initiate an enterprise attack "all the three methods it doesn't matter"

first i create my own self signed certificate then i choose the AP and start the attack and as soon as a victim connects to the fake AP an SSL error appears then the victim disconnects as shown in the screenshot.
![Screenshot_1](https://user-images.githubusercontent.com/20982225/197178724-f158df03-4539-45f7-a398-8d28caf3e24f.jpg)

**Comment by OscarAkaElvis** [comment]
I saw you asked the same at Discord server. Let's talk about this there. Thanks.
