### ISSUE TITLE
Help me in table

### ISSUE THREAD

**Issue by Hasji** [v1s1t0r1sh3r3/airgeddon#520]
Is there a way to remove the need for a graphical interface? I use his series, but I refuse to work in the nethunter terminal, I constantly load Cupcakes and already launch airgeddon in it. So he writes "I want a graphical interface!" A cupcake in a case with an adapter is like this: the tablet battery is a very strange thing, it just was, but now it's gone.

**Comment by cjb900** [comment]
not sure i understand half of what you are saying here. But if you want to use airgedon with out the need for a graphical interface you can use tmux and enable it in the `.airgecconrc` file.

**Comment by OscarAkaElvis** [comment]
The info you need is in the Wiki. https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

**Comment by Hasji** [comment]
*********************************** Welcome ************************************ 
This script is only for educational purposes. Be good boyz&girlz!
Use it only on your own networks!!

Accepted bash version (5.1.16(1)-release). Minimum required version: 4.2

Root permissions successfully detected

A graphical X window system has not been detected. If you already have one, check it's working properly. It's essential for airgeddon. The script can't continue

*********************************** Exiting ************************************
Exiting airgeddon script v11.02 - See you soon! :)

Checking if cleaning/restoring tasks are needed...
No tasks to perform on exit

**Comment by OscarAkaElvis** [comment]
Did you read first the wiki?

https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#when-i-start-airgeddon-i-see-this-message-a-graphical-x-window-system-has-not-been-detected-if-you-already-have-one-check-its-working-properly-its-essential-for-airgeddon-the-script-cant-continue

And if that is not working for you, as we said, you can use tmux instead of xterm.
