### ISSUE TITLE
Evil Twin - Deauth several targets at the same time instead of only 1.

### ISSUE THREAD

**Issue by usuarionuevor** [v1s1t0r1sh3r3/airgeddon#526]
Now that it also support 5ghz I noticed deauth only goes on one selected option, can't find an option to choose two instead, for example one in 2.4ghz and another in 5ghz to deauth both at the same time.
Or even more in the same band for example deauth several targets in 2,4ghz instead of only one, (having more adapters is no issue).

**Comment by cjb900** [comment]
you would need 2 separate wifi adapters and 2 instances of airgeddon if you wanted to deauth both 2.4 and 5ghz. This is because 1 wifi adapter can not create the fake AP and deauth 2 wifi bands all at the same time.

**Comment by usuarionuevor** [comment]
> 

So? 

this attack already requires a second adapter... what's wrong with another feature that requires another adapter?

**Comment by QianSong1** [comment]
> Now that it also support 5ghz I noticed deauth only goes on one selected option, can't find an option to choose two instead, for example one in 2.4ghz and another in 5ghz to deauth both at the same time. Or even more in the same band for example deauth several targets in 2,4ghz instead of only one, (having more adapters is no issue).
> 
> PS: Also making pursuit mode to mimic the original target as much as possible would be cool feature, for example auto-disable AP if the target is disabled too, basically mimic the original target as it is "pursuit mode".

Hi, brother, I have an automated DOS script that can attack multiple 2.4Ghz/5Ghz targets as long as there are sufficient WLAN adapters. Even if the target owner restarts the wireless router, they cannot escape the attack. Hee hee ^^
