### ISSUE TITLE
It seems we failed... try it again, choose another attack or increase the timeout 

### ISSUE THREAD

**Issue by dogukankurnaz** [v1s1t0r1sh3r3/airgeddon#528]
What is your airgeddon version?
11.11

What is your Linux O.S. and which version?
Kali Linux 22.04

Which is the chipset of your wireless card?
Qualcomm Atheros Communications AR9271 802.11n -- TPLINK WN722N V1

Describe the issue and the steps to reproduce it
Hm, I think I found a bug, steps to reproduce:

Select an option from menu: 
--------- 
0.  Return to main menu 
1.  Select another network interface 
2.  Put interface in monitor mode 
3.  Put interface in managed mode 
4.  Explore for targets (monitor mode needed) 
---------------- (without sniffing, just AP) ----------------- 
5.  Evil Twin attack just AP 
---------------------- (with sniffing) ----------------------- 
6.  Evil Twin AP attack with sniffing 
7.  Evil Twin AP attack with sniffing and bettercap-sslstrip2 
8.  Evil Twin AP attack with sniffing and bettercap-sslstrip2/BeEF 
------------- (without sniffing, captive portal) ------------- 
9.  Evil Twin AP attack with captive portal (monitor mode needed) 
--------- 
*Hint* Do you have any problem with your wireless card? Do you want to know what card could be nice to be used in airgeddon? Check wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets 
--------- 
> 9

******************************* Evil Twin deauth ******************************* 
Interface wlan0mon selected. Mode: Monitor. Supported bands: 2.4Ghz 
Selected BSSID: 98:00:6A:32:7E:60 
Selected channel: 13 
Selected ESSID: xxxxxxxxxxxx
Handshake file selected: None 

Select an option from menu: 
--------- 
0.  Return to Evil Twin attacks menu 
--------- 
1.  Deauth / disassoc amok mdk4 attack 
2.  Deauth aireplay attack 
3.  WIDS / WIPS / WDS Confusion attack 

> 2

Do you want to spoof your MAC address during this attack? [y/N] 
> n
This attack requires that you have previously a WPA/WPA2 network captured Handshake file 

If you don't have a captured Handshake file from the target network you can get it now 
--------- 

Do you already have a captured Handshake file? Answer yes ("y") to enter the path or answer no ("n") to capture a new one now [y/N] 
> n

Type value in seconds (10-100) for timeout or press [Enter] to accept the proposal [20]: 
> 

Timeout set to 20 seconds 

Two windows will be opened. One with the Handshake capturer and other with the attack to force clients to reconnect 

Don't close any window manually, script will do when needed. In about 20 seconds maximum you'll know if you've got the Handshake 
Press [Enter] key to continue...

Wait. Be patient... 
    
**It seems we failed... try it again, choose another attack or increase the timeout** 
Press [Enter] key to continue...

It was working about 10 days ago, I didn't touch anything and I wanted to try again. It's not working now. If I choose 1 or 3 instead of 2, the aireplay deauth attack log appears at the bottom left.

When I select 2, the log does not flow and that window closes. then the message failed appears on the screen. Please help me.

![](https://i.hizliresim.com/cvdc201.png)

**Comment by dogukankurnaz** [comment]
![](https://i.hizliresim.com/99zorm9.png)

**Comment by OscarAkaElvis** [comment]
Not sure if you know how the handshake capturing is working. You need legitimate clients connected to the network. And you need to be listening in that moment. Probably there are no clients, or if is not the case, there are many factors that can do the Denial of Service unreliable. Read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do

Are you trying with your own Access Point and can check using another device (a mobile device or whatever) to connect while the attack si ongoing just after the closing of the DoS window? you should try this, you'll see that it works.

If you didn't touch anything, we can say the same.... we didn't touch anything related to this in airgeddon from a week ago. Maybe it could sound obvious but sometimes the cards for whatever reason get frozen... unplug and replug it again. You have a chipset that should work.

If you want to continue testing, feel free to connect to our Discord server. Check the invitation link at contact section in our wiki. There we can discuss further or make more testing. Closing.
