### ISSUE TITLE
How to get "wrong passwords" entered by victim 

### ISSUE THREAD

**Issue by Anooppk007** [v1s1t0r1sh3r3/airgeddon#531]
Is it possible to see all attempted passwords ( even wrong / right ) in file manager?? ( Like all last entered password log )
Airgeddon  capitive portal attack

**Comment by OscarAkaElvis** [comment]
Are you kidding me? You didn't even try after asking. Captive portal is already capturing all password attempts in the trophy file (the good and the bad).

**Comment by Anooppk007** [comment]
Where is the file location?

**Comment by OscarAkaElvis** [comment]
I think I'm going to ban you. You should read the screen while using airgeddon. Launch the attack and read.

**Comment by Anooppk007** [comment]
I have selected default location only . And can't find any files there.

**Comment by OscarAkaElvis** [comment]
I don't understand what you mean. The trophy file is generated in the location you entered after a successful password is captured. It will have the good and the bad passwords.

**Comment by Anooppk007** [comment]
My question is whether I will get wrong passwords typed by victim on capitive portal when they not typed any successful password. ( For some reason even though I typed correct password it showing it as incorrect in capitive portal and terminal. That's why I asked this . )

**Comment by OscarAkaElvis** [comment]
I think that is pointless. But anyway you can check on temporary files at /tmp/www . They are there waiting for the right pass.

Next time explain what you want clearer since the beginning please. I thought you were just another troll.

**Comment by Anooppk007** [comment]
Thanks for understanding bro . Yeah now I can find all passwords there . Cheers

**Comment by OscarAkaElvis** [comment]
I think right path is /tmp/www/ag.et_attempts.txt
