### ISSUE TITLE
Don't work in android kali nethunter

### ISSUE THREAD

**Issue by dclxviclan** [v1s1t0r1sh3r3/airgeddon#534]
I try use this, but programm exit in the start without my agree, im use nethunter in android, why this don't work?

![Screenshot_20230407-013002_Termux](https://user-images.githubusercontent.com/109929818/230505439-4a068975-f82a-4099-b5b8-fe25016c9b75.jpg)
![Screenshot_20230407-013008_Termux](https://user-images.githubusercontent.com/109929818/230505440-6e417af2-853a-412d-8a0d-6b68cad75fd2.jpg)

**Comment by cjb900** [comment]
The error you are getting basically tells you what you need to do and you give no information if you tried those options. You also did not fill out the requested information so this issue is getting closed.

**Comment by Mainak009** [comment]
Termux won't work...need GUI use kex

**Comment by OscarAkaElvis** [comment]
You can also run airgeddon without any graphics system. Please, read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

Check about AIRGEDDON_WINDOWS_HANDLING to use tmux
