### ISSUE TITLE
compaudit:103: permission denied: /dev/null /home/rtfm/.zshrc:84: permission denied: /dev/null

### ISSUE THREAD

**Issue by Spl0yt** [v1s1t0r1sh3r3/airgeddon#535]
Hello everyone.

I've rencently installed airgeddon on my Vmware VM kali linux. I'm running version 2023.1 of kali linux.

My airgeddon version is v11.11 and i'm using a MediaTek Inc. MT7612U bought it of Hak5. Not sure if it was modified by them in any way or so.

THE ISSUE

---------

Well i wanted to do a WPS Pixie attack (option 8) using bully. It guesses the PIN very fast since it's a router with bad security. After that i closed the terminal and wanted to do something else so i opened a new one. There are i got the issue (see picture number 1). Bully or airgeddon somehow has messed up my whole /dev directory. There is a fix by rebooting the system, but it's quite annoying to always reboot. I have searched for similar issues like this but i found nothing related to it sadly.
![image](https://user-images.githubusercontent.com/123738674/230611467-4e72cbbf-90fe-441c-b2ee-23e765c436f6.png)

**Comment by OscarAkaElvis** [comment]
This was already discussed at Discord. It was not related directly to airgeddon.

**Comment by OscarAkaElvis** [comment]
Ok maybe in the end this was a bug related to this: #536
