### ISSUE TITLE
MT7612 support

### ISSUE THREAD

**Issue by magbuhosjames** [v1s1t0r1sh3r3/airgeddon#538]
#### What is your airgeddon version?

v11.11

#### What is your Linux O.S. and which version?

Kali Linux Purple Edition 2023.1a

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Native

#### Which is the chipset of your wireless card?

MT7612u (Alfa AWUS036ACM)

#### Describe the issue and the steps to reproduce it

Handshake capture is OK
Error faced:
The interface changed its name while setting in managed mode. Autoselected 
Fake IP not created

https://imgur.com/kq7s80t
https://imgur.com/66xxZ2N

**Comment by cjb900** [comment]
Resolved via discord

**Comment by ChillVibesMushroom** [comment]
Yeah all we had to do was do a search for mediatek with apt-cache and install some bin files in the firmware folder
if it aint broke dont fix it am I right lol
