### ISSUE TITLE
Nethunter graphics problem

### ISSUE THREAD

**Issue by RollexGrief** [v1s1t0r1sh3r3/airgeddon#540]
After updating, I ran into a problem on my Kali NetHunter. After starting airgeddon I get an error that the GUI was not found. Earlier it was working. Before launching it, I made sure to type the command **xhost +** but that did not work.

![vncviewer_43i7sl0o6s](https://user-images.githubusercontent.com/38622094/234216335-e744fac8-69fb-4f84-9e88-b1a8aa7dbd9a.png)

Airgeddon version: **v11.11(Latest)** 
Nethunter: **2023.1** 
Phone: **Xiaomi Mi A3 (Offical supported device)**
Kernel: **4.14.246-NetHunter-18.1-yesimxev**
Version: **LineageOS 18.1 (By Harukey)**

**Comment by RollexGrief** [comment]
But on v11.10 everything works at the moment!

**Comment by xpz3** [comment]
Please download and use airgeddon from dev branch

**Comment by RollexGrief** [comment]
> Please download and use airgeddon from dev branch

![vncviewer_ZdDxJp80wV](https://user-images.githubusercontent.com/38622094/234225799-9ab15fd6-8284-465e-ad79-1e01994b3a83.png)

**Comment by OscarAkaElvis** [comment]
Yes, use airgeddon v11.20 which has not been released yet, but as xpz3 said, it is available on dev branch. Give it a try and tell to us if it worked for you.

**Comment by OscarAkaElvis** [comment]
Ok sorry, I saw now that your last screenshot was on v11.20 . So it is not working for you. Let me ask you about some tests to do... hold on.

**Comment by RollexGrief** [comment]
> Ok sorry, I saw now that your last screenshot was on v11.20 . So it is not working for you. Let me ask you about some tests to do... hold on.
All working if i'm using root user

**Comment by OscarAkaElvis** [comment]
I'm glad it is working for you. But anyway, can you answer this questions?

Try this as the user which where failing to you (probably using a user and using sudo, confirm this):
`loginctl` <- please, paste the output. And if you don't have this installed, install it and try airgeddon again
`sudecho ${XDG_SESSION_TYPE}` <- please, pate the output

That will help me to do some improvements. Thanks.

**Comment by Mainak009** [comment]
How to change to dev channel?....I installed it from Kali apt and am having the same issue in v11.11
![PXL_20230511_101011314.MP.jpg](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/52679017/c79103aa-a45c-4d46-af8b-8590c1121164)

**Comment by OscarAkaElvis** [comment]
dev channel? is a branch on Github. Just clone it `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon`.

Please, for further support, join to our Discord server instead of using other issues threads. Invitation link: https://discord.gg/sQ9dgt9

**Comment by Mainak009** [comment]
> dev channel? is a branch on Github. Just clone it `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon`.
> 
> Please, for further support, join to our Discord server instead of using other issues threads. Invitation link: https://discord.gg/sQ9dgt9

When will the fix go live in Kali repo?

**Comment by OscarAkaElvis** [comment]
still pending for some translations and last minute changes. After we decide to do the release (maybe end of this month) usually kali is fast to deploy it on their repos (2-3 days).

**Comment by OscarAkaElvis** [comment]
I repeat, if you join our Discord server you'll have a community plenty of users able to help, to guide you, give you support and you'll know before anybody about any change or improvement. I fully recommend to join and participate there instead of write here on issues.

**Comment by Mainak009** [comment]
> I repeat, if you join our Discord server you'll have a community plenty of users able to help, to guide you, give you support and you'll know before anybody about any change or improvement. I fully recommend to join and participate there instead of write here on issues.

Ahhh... I am already a member, LoL... joined long ago I forgot![Screenshot_20230511-164814_Discord.png](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/52679017/82c03eed-3747-4fba-a61e-7dbf83436ef3)

 😂

**Comment by Mainak009** [comment]
> > Ok sorry, I saw now that your last screenshot was on v11.20 . So it is not working for you. Let me ask you about some tests to do... hold on.
> 
> All working if i'm using root user
> 

How do you manage to work?.... I'm in root user too but not working.

**Comment by OscarAkaElvis** [comment]
I see you launch the echo command twice using same user (root). Probably the graphics system was launched with another (non-root) user, so get a shell of that user (not root) and do the echo command to see the output. if you launch airgeddon from there doing `sudo bash airgeddon.sh` it will probably work.

Other option is to use tmux like in a headless system setting AIRGEDDON_WINDOWS_HANDLING to tmux value. Check this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Options

I repeat, ask better in discord channel.

**Comment by OscarAkaElvis** [comment]
We did some recent changes on 11.20 (not released yet, available at dev branch at the time of writing). That changes made nethunter to work properly on this.

**Comment by Mainak009** [comment]
> We did some recent changes on 11.20 (not released yet, available at dev branch at the time of writing). That changes made nethunter to work properly on this.

Yeah I already replied to you on discord that your changes worked properly without any other forced x11 plugin....GUI is working and normal terminal not as it should.

![Screenshot_20230601-221723381_102119.jpg](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/52679017/1b38738a-ab2c-4c21-b5e9-971498baa78f)

![Screenshot_20230601-221904765_102124.jpg](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/52679017/2265433e-aa29-41ae-95fc-b2b1dbe139b8)
