### ISSUE TITLE
Captive portal without evil twin?

### ISSUE THREAD

**Issue by dwasyluk** [v1s1t0r1sh3r3/airgeddon#542]
Is it possible to use Airgeddon to create a captive portal with a custom AP name without it having to be an evil twin of an existing AP?

**Comment by OscarAkaElvis** [comment]
No  That doesn't make sense. You need a handshake to check on it if the password entered is the good one, and without DoSsing a real AP, nobody is going to connect to your fake AP. Anyway, it is something if you prepare a plugin for it, bit in my opinion is pointless.

**Comment by xpz3** [comment]
Plugin development help
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Plugins%20Development

Existing plugin for custom essid which detects hidden network and allows for custom name. You can modify it to use custom name always by removing the hidden ap check condition
https://github.com/xpz3/airgeddonplugins/blob/main/custom_essid.sh

**Comment by dwasyluk** [comment]
This is great thanks for the helpful links, very much appreciated 👍

**Comment by dwasyluk** [comment]
Any tips or suggestions on how to grab an additional form field from the captive portal for reporting in the "handshake solution captured" phase?

**Comment by OscarAkaElvis** [comment]
You have a blank plugin template to fill in the plugins folder (plugin_template.sh). You have an example of a plugin included also in airgeddon (missing_dependencies.sh) also placed in plugins folder. Read the docs to understand the three types of hooking: prehook, override and posthook.

For further help, join to our discord server. Invitation link is in contact section at wiki. Don't try to get here large answers.

Cheers.
