### ISSUE TITLE
An unexpected error occurred, redirecting to the menu

### ISSUE THREAD

**Issue by omarkhallill** [v1s1t0r1sh3r3/airgeddon#545]
When i try to explore a new targets in WPS attack menu , im getting this : ******************************* WPS attacks menu ******************************* 
Interface wlx90de8066fbb5 selected. Mode: Monitor. Supported bands: 2.4Ghz 
Selected WPS BSSID: None 
Selected WPS channel: None 
Selected WPS ESSID: None 
WPS locked network: None 

Select an option from menu: 
--------- 
0.  Return to main menu 
1.  Select another network interface 
2.  Put interface in monitor mode 
3.  Put interface in managed mode 
4.  Explore for targets (monitor mode needed) 
------------- (monitor mode needed for attacks) -------------- 
5.  (bully) Custom PIN association 
6.  (reaver) Custom PIN association 
7.  (bully) Pixie Dust attack 
8.  (reaver) Pixie Dust attack 
9.  (bully) Bruteforce PIN attack 
10. (reaver) Bruteforce PIN attack 
11. (bully) Known PINs database based attack 
12. (reaver) Known PINs database based attack 
13. (reaver) Null PIN attack 
--------- 
14. Offline PIN generation using algorithms and database 
--------- 
*Hint* The Arcadyan algorithm needs a very specific data to calculate the PIN (the serial number of the access point). Getting this data can take a lot of time. You can optionally choose to try to generate it. This generated PIN is very useful in networks of type Orange-XXXX 
--------- 
> 4

**************************** Exploring for targets ***************************** 
Exploring for targets option chosen (monitor mode needed) 

Selected interface wlx90de8066fbb5 is in monitor mode. Exploration can be performed 

Checking to solve possible "bad FCS" problem if exists. Parameterizing... 
Done! parameter set 

WPS filter enabled in scan. When started, press [Ctrl+C] to stop... 
Press [Enter] key to continue...

An unexpected error occurred, redirecting to the menu 
Press [Enter] key to continue...

**Comment by cjb900** [comment]
Your problem may be that you are using a long wifi interface name and not the standard wlan0, wlan1, etc... You can try changing your interface name and see if that helps. Information on that can be found here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

**Comment by omarkhallill** [comment]
> Your problem may be that you are using a long wifi interface name and not the standard wlan0, wlan1, etc... You can try changing your interface name and see if that helps. Information on that can be found here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming

i changed my interface name , and the same issue : ******************************* WPS attacks menu ******************************* 
Interface wlan1 selected. Mode: Monitor. Supported bands: 2.4Ghz 
Selected WPS BSSID: None 
Selected WPS channel: None 
Selected WPS ESSID: None 
WPS locked network: None 

Select an option from menu: 
--------- 
0.  Return to main menu 
1.  Select another network interface 
2.  Put interface in monitor mode 
3.  Put interface in managed mode 
4.  Explore for targets (monitor mode needed) 
------------- (monitor mode needed for attacks) -------------- 
5.  (bully) Custom PIN association 
6.  (reaver) Custom PIN association 
7.  (bully) Pixie Dust attack 
8.  (reaver) Pixie Dust attack 
9.  (bully) Bruteforce PIN attack 
10. (reaver) Bruteforce PIN attack 
11. (bully) Known PINs database based attack 
12. (reaver) Known PINs database based attack 
13. (reaver) Null PIN attack 
--------- 
14. Offline PIN generation using algorithms and database 
--------- 
*Hint* Some access points have only PBC (Push Button Connect) enabled and you can't connect via WPS if you don't press the physical button on the device 
--------- 
> 4

**************************** Exploring for targets ***************************** 
Exploring for targets option chosen (monitor mode needed) 

Selected interface wlan1 is in monitor mode. Exploration can be performed 

Checking to solve possible "bad FCS" problem if exists. Parameterizing... 
Done! parameter set 

WPS filter enabled in scan. When started, press [Ctrl+C] to stop... 
Press [Enter] key to continue...

An unexpected error occurred, redirecting to the menu 
Press [Enter] key to continue...

**Comment by cjb900** [comment]
What wifi adapter and chipset are you using? What Linux distro are you using? Because I'm unable to replicate this issue here in Kali using my panda pau09 with a RT5572 chipset or my laptops built in wifi adapter which is an Intel wireless 7265 (rev 59)

**Comment by omarkhallill** [comment]
> What wifi adapter and chipset are you using? What Linux distro are you using? Because I'm unable to replicate this issue here in Kali using my panda pau09 with a RT5572 chipset or my laptops built in wifi adapter which is an Intel wireless 7265 (rev 59)

Im using the adapter ( Ralink MT7601U ) , my linux distro is ubuntu 23.04 .

**Comment by cjb900** [comment]
That chipset is most likely going to be your issue. It's completely crap for wifi hacking and as you can see here is on our black list https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by OscarAkaElvis** [comment]
MT7601U is not Ralink, it's Mediatek. Anyway, as cjb900 said, it is crap for wifi hacking. Check the list on the given link and choose a nice hacking-friendly chipset. Note the difference between MT7601U and MT7610U (01 and 10). The second one is nice, yours is blacklisted.

Anyway, even with a good chipset, you should not use long interface names as explained here (https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming). The reason is that some 3rd party tools (like Reaver) are not compatible with that kind of name nomenclature. So we recommend to follow the instructions on the link to use short interface names to avoid possible conflicts.
