### ISSUE TITLE
Explore for targets - add option to return to last scan targets list

### ISSUE THREAD

**Issue by blasbalgitay** [v1s1t0r1sh3r3/airgeddon#546]
#### Describe the feature or compatibility enhancement and involved versions if apply

after exploring targets => choosing your desired targets and doing your thing... I want to change the target and instead of exploring for targets again, I would like to have the option to return to the target list of the last scan I have performed instead of exploring for targets again.

#### What are the benefits of adding this?

This Feature will make life easier(and make my dream come true) with changing targets

**Comment by OscarAkaElvis** [comment]
Sorry but that is absolutely intentional. The less time from the scan to the action, the better. Sometimes the APs could change the channel and if you don't scan again to detect it, that willake in that case the attack ineffective.

Anyway, thanks for your suggestion.

**Comment by OscarAkaElvis** [comment]
Anyway, it's doable using the plugins system. You can do it yourself: 😉
