### ISSUE TITLE
Airgeddon Not Working Stable

### ISSUE THREAD

**Issue by applusinc** [v1s1t0r1sh3r3/airgeddon#552]
#### What is your airgeddon version?
v 11.20

#### What is your Linux O.S. and which version?
Kali Linux 2023.2

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?
Usb Persistance

#### Which is the chipset of your wireless card?
Network controller: MEDIATEK Corp. MT7921 802.11ax PCI Express Wireless Network Adapter
        DeviceName: Tequini MediaTek Wi-Fi 6 MT7921 + BT5.2
        Subsystem: AzureWave MT7921 802.11ax PCI Express Wireless Network Adapter
        Flags: bus master, fast devsel, latency 0, IRQ 96, IOMMU group 16
        Memory at ff10100000 (64-bit, prefetchable) [size=1M]
        Memory at ff10200000 (64-bit, prefetchable) [size=16K]
        Memory at ff10204000 (64-bit, prefetchable) [size=4K]
        Capabilities: [80] Express Endpoint, MSI 00
        Capabilities: [e0] MSI: Enable+ Count=1/32 Maskable+ 64bit+
        Capabilities: [f8] Power Management version 3
        Capabilities: [100] Vendor Specific Information: ID=1556 Rev=1 Len=008 <?>
        Capabilities: [108] Latency Tolerance Reporting
        Capabilities: [110] L1 PM Substates
        Capabilities: [200] Advanced Error Reporting
        Kernel driver in use: mt7921e
        Kernel modules: mt7921e

#### Describe the issue and the steps to reproduce it
Hi, When I want to launch an Evil Twin AP attack with captive portal (monitor mode needed), sometimes the access point does not start or stops again a few minutes after it is started but sometimes it works fine. what is the reason of this ?

**Comment by OscarAkaElvis** [comment]
hi @applusinc , if it works for you sometimes then it must be related to something on your side. I mean, airgeddon is executing same code when it works for you and when is not working. There must be something messing it up on your end. My suggestions:

-Be sure that your card is a good card for wifi hacking. To be honest, never used that chipset MT7921e and not sure if is a nice card for wifi hacking. Maybe it's an unstable card or is a driver problem. As you can see it is neither whitelisted nor blacklisted/greylisted here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

-Sometimes seems obvious but card may freeze after some working due its mode change. Sometimes when this happens, unplug and replug it again is enough, but in your case I think is an internal card... so you can't do this. Maybe a reboot is needed in your case.

-Usb bootable linux are working as native linux (which is nice) but depending on the hardware they are working, sometimes they can be extremely slow. Maybe to work with this kind of linux is no the best option for wifi hacking.

-Try to launch from console `airmon-ng check kill` before launching airgeddon. Maybe this can make your card to work better.

I'd suggest to use 10.21 version from dev branch, but I think in this case there will be no difference. New changes are not related to this.

I encourage you to join to our Discord server for further discussion. You can find the invitation link in the contact section at wiki.

**Comment by Fuse8499** [comment]
unsubscribe
