### ISSUE TITLE
RTL8821CU, Only 2 Windows Instead of 6 Windows During Captive Portal (Fake AP Launched, Captive Portal Didn't)

### ISSUE THREAD

**Issue by mfazrinizar** [v1s1t0r1sh3r3/airgeddon#556]
#### What is your airgeddon version?

11.20

#### What is your Linux O.S. and which version?

Parrot OS 5.3 (Electro Ara) x86_64

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

VirtualBox

#### Which is the chipset of your wireless card?

Prolink AC650 (RTL8821CU)

#### Describe the issue and the steps to reproduce it
Screenshot: https://imgur.com/a/teAOg7w

As you can see, there are only 2 windows showed up. It's supposed to be 6 windows. The captive portal didn't launch and the user wasn't directed to the captive portal website to input the password from Evil Twin AP.  (I had captured the handshake, using NodeMCU ESP8266 to deauth, so I used only 1 USB Wi-Fi Adapter).

Note: the AP was created, but was useless, since it didn't host the captive portal. Same issue applied to all Evil Twin methods. Kindly tell if you have any advice or solution regarding this issue. Thanks in advance.

**Comment by cjb900** [comment]
Your main issue here is that you are using a crap RTL chipset. Those are notoriously problematic for wifi hacking and not recommended. You will need to get a better supported card/chipset from our list here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets. Second you are using Parrot OS and may have the long wifi interface name issue and would need to fix that after you get a better supported card/chipset. Information on fixing this can be found here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Consistent%20Network%20Device%20Naming
