### ISSUE TITLE
How can both of them be possible at the same time?

### ISSUE THREAD

**Issue by shahmal1yev** [v1s1t0r1sh3r3/airgeddon#560]
In some usage modes of Airgeddon, there is a peculiar situation. It attempts to simultaneously keep an access point active using a single network card and actively send deauthentication packets. How is this possible?

**Comment by cjb900** [comment]
I assume you are referring to evil twin attacks in airgeddon. This is done using wifi cards/chipsets supporting VIF (not all do). VIF is the ability to spit a wifi card into 2 virtual interfaces where one is used for the fake AP and the other for deauthign.

**Comment by OscarAkaElvis** [comment]
exactly, as cjb said. Read this: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif

**Comment by shahmal1yev** [comment]
Even though my network card supports AP/VLAN, it creates a portal to log in during an Evil Twin attack but cannot send deauthentication packets. I tried manually by creating a virtual network card, and it still didn't work. What could be the reason?

**Comment by OscarAkaElvis** [comment]
Maybe you have a card from the greylist which supports VIF but is still not recommended. What is your chipset? Check the list at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Please, for further discussion join to our discord channel. Invitation link is in contact section on wiki.
