### ISSUE TITLE
Unable to attack 5 ghz networks 

### ISSUE THREAD

**Issue by Mike1997-1018** [v1s1t0r1sh3r3/airgeddon#564]
#### What is your airgeddon version?

11.21
#### What is your Linux O.S. and which version?

2023.3
#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Native mode
#### Which is the chipset of your wireless card?

Ralink RT5572

#### Describe the issue and the steps to reproduce it

I’m attempting to preform an evil twin attack on a 5ghz network with my Panda pau09 n600 but when I try to capture a hand shake this message appears what should I do ? /
![A2F50A7B-EBE3-472B-84E7-BCF2556E0E50](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/145815172/235bf3a4-d20d-4b36-bab9-8f1ca66eaf76)

**Comment by cjb900** [comment]
I mean it's pretty obvious. Whatever wifi adapter/chipset you are trying to use for DoS pursuit does not support 5ghz. You will either need to use a different wifi adapter/chipset that supports 5ghz for DoS pursuit or just not use DoS pursuit.

**Comment by Mike1997-1018** [comment]
> I mean it's pretty obvious. Whatever wifi adapter/chipset you are trying to use for DoS pursuit does not support 5ghz. You will either need to use a different wifi adapter/chipset that supports 5ghz for DoS pursuit or just not use DoS pursuit.

Hello my friend what wireless adapters do you recommend I use to preform a evil twin attack with dos pursuit mode ?

**Comment by OscarAkaElvis** [comment]
Read our wiki to find a list of whitelisted VIF capable adapters: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

If you have more questions, please join to our Discord server. Invitation link is on contact section at wiki.
