### ISSUE TITLE
Deauth packets not sending in "Evil Twin attack"

### ISSUE THREAD

**Issue by ktauchathuranga** [v1s1t0r1sh3r3/airgeddon#565]
#### What is your airgeddon version?

v11.21

#### What is your Linux O.S. and which version?

Kali Linux 2023.3

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

native mode

#### Which is the chipset of your wireless card?

Intel Corporation Wi-Fi 6 AX201

#### Describe the issue and the steps to reproduce it

when i do Evil Twin attack, DoS/Deauth window not sending deauth packets. its just sits there.
and i know that airgeddon require VIF (Virtual Interface) ability. i ran this command `sudo iw list | grep "Supported interface modes" -A 8` and the results down here,

![image](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/79928743/811ff623-0fb5-443c-a7a2-7e92954452ec)

**Comment by cjb900** [comment]
Even internal wifi adapters that support all the modes needed do not allows work well for wifi hacking. You will have to look at getting a better supported one from our list here https://discord.com/channels/1093562233612673097/1113210217031802880/1126805469294497892

**Comment by OscarAkaElvis** [comment]
As you can see in the link, some cards are VIF capable (by hardware) but they are problematic when they are used depending on the driver or the kernel (greylist). Maybe we should add this adapter to that list.

**Comment by OscarAkaElvis** [comment]
Done, it is appearing now in the greylist now as VIF capable but also as a problematic one.

**Comment by ktauchathuranga** [comment]
> Done, it is appearing now in the greylist now as VIF capable but also as a problematic one.

ooh okiii,
it says it needs "patched drivers"
any idea where I can find that or ....
adapters are really not an option for me right now...🖤

**Comment by OscarAkaElvis** [comment]
To be honest, no idea about what drivers or kernel combination could work for you. We recommend to get a card from the whitelist.

For further discussion, join to our Discord server. Invitation link is in contact section at Wiki.
