### ISSUE TITLE
Not sure where to put this Panda PAU09 failing to host a 5ghz ap

### ISSUE THREAD

**Issue by obnoxiousish** [v1s1t0r1sh3r3/airgeddon#567]
Frequency 5180 (primary) not allowed for AP mode, flags: 0x53 NO-IR
Primary frequency not allowed
wlp0s20u10: IEEE 802.11 Configured channel (48) or frequency (5240) (secondary_channel=0) not found from the channel list of the current mode (2) IEEE 802.11a
wlp0s20u10: IEEE 802.11 Hardware does not support configured channel
Could not select hw_mode and channel. (-3)
wlp0s20u10: interface state UNINITIALIZED->DISABLED
wlp0s20u10: AP-DISABLED
wlp0s20u10: Unable to setup interface.
wlp0s20u10: interface state DISABLED->DISABLED
wlp0s20u10: AP-DISABLED
wlp0s20u10: CTRL-EVENT-TERMINATING
hostapd_free_hapd_data: Interface wlp0s20u10 wasn't started
nl80211: deinit ifname=wlp0s20u10 disabled_11b_rates=0

**Comment by OscarAkaElvis** [comment]
Closing due issue creation policy violation. Please, read carefully the issue creation template and fill all the fields. Or consider to join to our Discord server instead of opening GitHub issues. Invitation link is on contact section at wiki.
