### ISSUE TITLE
scanning for accesspoints can't find something

### ISSUE THREAD

**Issue by Flow44A** [v1s1t0r1sh3r3/airgeddon#569]
Hi the installation was without errors, but scanning for accesspoints can't find something. wlan adapter is working in monitor mode and works correctly.

**Comment by cjb900** [comment]
Well you gave no helpful information so i'm just going to guess this is your issue https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#when-i-scan-for-wireless-networks-no-networks-are-found
