### ISSUE TITLE
Change Index Page

### ISSUE THREAD

**Issue by sapahere** [v1s1t0r1sh3r3/airgeddon#572]
How can you change the Index page?

**Comment by cjb900** [comment]
Not sure what you mean by index page.

**Comment by xpz3** [comment]
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#can-the-evil-twin-captive-portal-page-be-customized-if-so-how
If that's what you asked..

**Comment by OscarAkaElvis** [comment]
Please, be more specific next time. Closing.

**Comment by NuBz-GeN** [comment]
You really need to take me off of this fucking list.

I cant count the number of friggin times I have gone in my account and told
it not to email me this crap.
I could care less if johnny fuckwad wnts to know how to hack his neihbor
lesve me the fuck out of it you cunt
Pretty fed up with this shit.

**Comment by OscarAkaElvis** [comment]
If you are receiving emails is totally your fault. You are demonstrating right now a very high n00b level.

Check your Github account, disable your notifications or click on "unwatch" of the project. Blocking and reporting such a n00b user using bad words when the only guilty of what is happening to him is his own ignorance.
