### ISSUE TITLE
how to configure the backround color of terminal?

### ISSUE THREAD

**Issue by Reyuki-san** [v1s1t0r1sh3r3/airgeddon#573]
I run airgeddon on my terminal emulator, but this one seems not readable for me:
![12-28-2023](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/126035476/f647643d-2e9a-4568-b1d4-afe58c09c71c)

However I've no idea how to change the white background color, what should I do?

I use dwm as window manager
and st as terminal emulator

**Comment by OscarAkaElvis** [comment]
Hello. That seems something to configure on your system. The scan window opens like this: 

![image](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/5803348/a524bb16-35e4-48f2-89ba-46269f81dc82)

As you can see, background is black and font is white... if your system is doing the opposite, probably is something that you need to deal with.

Maybe you want to try some colors and backgrounds manually. You can modify that line on `explore_for_targets_option` function. Closing.
