### ISSUE TITLE
When I perform a captive portal attack, only 2 windows open and the remaining 4 windows do not load. What is the reason for this? Can you help me?

### ISSUE THREAD

**Issue by ankajunioritta** [v1s1t0r1sh3r3/airgeddon#577]
![1](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/157321093/57f0d297-82e5-457d-b270-d29c785d0b77)
Im attacking my network but only 2 windows opened and I can't connect to the network.I don't speak English very well.PLEASE HELP ME GUYSSSS.

**Comment by OscarAkaElvis** [comment]
Closing due to a issue creation policy. Read the requirements to open an issue.
