### ISSUE TITLE
Unbanned from Discord.

### ISSUE THREAD

**Issue by hyekalhitech** [v1s1t0r1sh3r3/airgeddon#585]
Hello,
I apologize for the unintended spam messages sent in the airgeddon server—I was the unfortunate victim of an account compromise. Swift action was taken to mitigate this issue: I disconnected all applications linked to my Discord account, changed my password, and enabled two-factor authentication to ensure the security of my account. I have also scanned for and cleared any potential malicious software or bots.

As a result of these remediations, I believe my account is now secure and poses no threat to the airgeddon discord server. I am reaching out to kindly request assistance in lifting the ban placed on my account so I may rejoin the server community. 
Thank you very much for your understanding and help in this matter.

Discord username: hyekalhitech

**Comment by OscarAkaElvis** [comment]
Your ban was revoked. Closing.
