### ISSUE TITLE
BrosTrend Chipset Compatibility

### ISSUE THREAD

**Issue by MatteeG** [v1s1t0r1sh3r3/airgeddon#586]
#### Describe the feature or compatibility enhancement and involved versions if apply

The BrosTrend line of wireless adapters is of excellent quality, with specific adapters for Linux, Ubuntu, Debian, etc.

I'm using Airgeddon 11.22 from Kali Linux with VM.

I noticed that many of these have chipsets that are not compatible with airgeddon functionality.

The improvement would be substantial, given that these adapters are on par with Alfa.

For example:
I use the BrosTrend model n: AC5L Duel Band adapter with Chipset: Realtek Semiconductor Corp. 802.11ac NIC, but this is not compatible with airgeddon (Evil twin attack), despite being fully functional with all Kali Linux programs.

#### What are the benefits of adding this?

The advantages of making such devices compatible would be enormous, as you would broaden the compatibility of your product, opening the doors to a medium-high range device.

**Comment by xpz3** [comment]
It's not that airgeddon is incompatible, it's just that realtek chipsets have poor driver support for compatibility with tools like airgeddon. Evil twin attack using just one card needs vif support which unfortunately isn't there for newer realtek cards. Read more here. https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif
If you have more than one card, you can use the following plug-in to run evil twin attack even if the cards doesn't support vif..
https://github.com/xpz3/airgeddonplugins/blob/main/multint.sh

**Comment by OscarAkaElvis** [comment]
yeah, nothing we can do. There is a list with the recommended chipsets: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

Try to read these links before buying a wireless adapter!!
