### ISSUE TITLE
Cannot start hostapd

### ISSUE THREAD

**Issue by RealYukiSan** [v1s1t0r1sh3r3/airgeddon#588]
#### What is your airgeddon version?

11.22

#### What is your Linux O.S. and which version?

Arch linux 6.8.9

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

Native mode

#### Which is the chipset of your wireless card?

Qualcomm Atheros AR9285
```
Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
                 * outside context of a BSS
```

#### Describe the issue and the steps to reproduce it

The interface name somehow renamed when putting the interface into monitor mode and it cause the temporary hostapd configuration become invalid

sometimes it's named `wlan0mon`, and sometimes `mon0`:

![05-23-2024_000](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/126035476/178f4738-351b-40bb-8b80-27df466fbbd0)

How to prevent airgeddon from renaming network interface?

**Comment by RealYukiSan** [comment]
I try to force rename the interface while running the airgeddon:
```
ip link set dev wlan0mon down
ip link set dev wlan0mon name wlan0
ip link set dev wlan0 up
```

but it makes the airgeddon not work properly:
![05-23-2024_001](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/126035476/d540ce26-b67d-4e5f-905d-d655ac28d7ba)

**Comment by xpz3** [comment]
Renaming of the interface is intentional and has nothing to do with the failure of hostapd. It clearly says cant connect to kernel driver. So it's something else

**Comment by xpz3** [comment]
You don't have to manually rename the interface. When airgeddon uses airmon-ng to start monitor mode, the interface gets renamed to wlanXmon and while doing evil twin attack, additional vif is created with the name monX which is intentional..

**Comment by RealYukiSan** [comment]
It seems I'm misunderstanding the problem. Any suggestions for debugging the problem? let me know if you need additional information

**Comment by xpz3** [comment]
Not sure if your chipset is supported. Could be it or the driver.. join the discord server and others might be able to help you out with this..
