### ISSUE TITLE
Chipsets choice

### ISSUE THREAD

**Issue by Nek0-San** [v1s1t0r1sh3r3/airgeddon#590]
Hey, hope to bother less possible.
I'm looking for an adapter that can do 2.4 a 5ghz.
I tried rt5572 but it seems that the driver allows only 2.4 on my machine. I need to buy another one.

"Not working on Parrot OS <=5 (vm or native). Deauth not working while using VIF on kernels >= 6.2"

It's about the first and second chipset in the list.
Does that mean that on latest kali kernels the deauth does not work? How can i solve, using another wifi usb to deauth?
Thank you

**Comment by cjb900** [comment]
Your issue isn't that the wifi adapter/chipset you have isn't compatible it's that an update in one of the dependencies caused some version of Linux to not work with dual band wifi adapters. You cau use the dev version of airgeddon that has a fix for this https://github.com/v1s1t0r1sh3r3/airgeddon/tree/dev

**Comment by OscarAkaElvis** [comment]
yeah, this looks like the "problem" generated by the modified output by the modern versions of the iw command. On the dev version that is fixed as it was stated here.
