### ISSUE TITLE
Support

### ISSUE THREAD

**Issue by Nek0-San** [v1s1t0r1sh3r3/airgeddon#591]
Thank you so much for your answer. As I am still learning, could you Please write down HOW should I do this. (I mean install the dev version).
If possible, write me down the exact commands.
Please help, a small donation will be on it's way.
Thank you

**Comment by cjb900** [comment]
I don't believe there is a way to install this via apt if that's how you installed/used it initially. But you can download and run the dev version with `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon`

**Comment by Nek0-San** [comment]
Thank you . Once cloned what are the commands?

Il gio 6 giu 2024, 00:21 cjb900 ***@***.***> ha scritto:

**Comment by cjb900** [comment]
once you git clone it you run it from the directory where you cloned it from. You do not need to install the version you already have as once the dev version is released you can then update the installed version to that new version.

**Comment by OscarAkaElvis** [comment]
Please, stope asking basic questions that can be answered just checking our wiki. There is a section where you can see how airgeddon can be git cloned and executed: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Installation%20&%20Usage

If you need further assistance, connect to our discord server. You can find the invitation link on contact section at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Contact

**Comment by Nek0-San** [comment]
Ok, i will stop asking.
I executed airgeddon, i was just saying that in evil twin it just doesn't
make the 5ghz AP.
Thank you!

Il gio 6 giu 2024, 08:22 Óscar Alfonso Díaz ***@***.***> ha
scritto:

**Comment by OscarAkaElvis** [comment]
You didn't filled out the issue creation template when created the issue, so we are missing precious information to be able to help you like airgeddon version, O.S, wireless adapter and chipset, etc etc.

Connect to discord to provide further details. We'll be waiting there for more details.
