### ISSUE TITLE
Not able to find specific network when using Evil Twin 

### ISSUE THREAD

**Issue by AadiBiyani** [v1s1t0r1sh3r3/airgeddon#592]
I am trying to use the evil twin tool, I have all of the necessary prerequisite installations done and everything runs smoothly until the point where the script looks for WiFi networks. The network that I am trying to use does not show up. In the network settings it says that the network is on channel 1, but on my mac it says the network is on channel 44. How can I fix this?

**Comment by cjb900** [comment]
you probably have to use another wifi adapter and use DoS pursuit mode https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-dos-pursuit-mode-exactly

**Comment by OscarAkaElvis** [comment]
It looks like target network is using a "feature" that some APs have. Depending on the vendor it is called "smart wireless" or is just there an option like this (extracted from a Zyxel AP-router): 

![image](https://github.com/v1s1t0r1sh3r3/airgeddon/assets/5803348/c224dac8-e638-4224-8197-ea41a60125fd)

So, the 2,4Ghz and the 5Ghz bands, both have the same ESSID. What cjb suggested is to avoid channel hopping of an AP switching its channel in a band: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-dos-pursuit-mode-exactly

But in this case, you are talking about different bands (channel 1 is 2,4ghz and 44 is 5ghz), so probably you'll need 4 adapters to perform a reliable attack. You need to attack both bands at the same time and also performing DoS pursuit mode on each one to chase the AP in the case of channel hopping. A tough scenario. And of course, at least 2 of the 4 adapters required, need to be VIF capable. Read about VIF here: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#what-is-vif . The secondary adapters to perform just the DoS pursuit mode just need to support monitor mode, so even crappy Realtek chipsets are valid for this.

If you need further assistance, please connect to our discord server. You can find the invitation link on contact section at wiki: https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Contact
