### ISSUE TITLE
Can't find answer in FAQ

### ISSUE THREAD

**Issue by Nek0-San** [v1s1t0r1sh3r3/airgeddon#593]
Hi again.
I have a question that I haven't been able to find an answer:
Is it possible to run 2 instances of Airgeddon simultaneously? Obviously using 2 cards.
I have two folders of airgeddon-dev and i execute 2 instances, but i am non sure they work. (I don't know if there is a process that the two instances should share)
Can you give me a hint?
(I already know about the plugin for using two cards, i want two instances instead. Then if it works I will give feedback about what I want to do)
Thank you

**Comment by cjb900** [comment]
Many have run 2 instances of airgeddon but it depends on what exactly you are trying to do here if you will run into issues or not. You can try this version of [airgeddon](https://github.com/v1s1t0r1sh3r3/airgeddon/tree/multi_instance) that lets you run 2 instances of an evil twin attack from one airgeddon. but that is still in development so nay not work 100%

**Comment by Nek0-San** [comment]
Thank you for your answer. Basically i'm trying to deauth in more that one
way, for example mdk4 and aireplay or something in order to get a sure
deauth. I will try the multiinstance one. Thank you so much

Il ven 14 giu 2024, 20:56 cjb900 ***@***.***> ha scritto:

**Comment by OscarAkaElvis** [comment]
The development of the multi-instance version is very close to the end. I'd say that you can now launch different evil twin attacks. But some more testing is needed yet. Hopefully, it will be released soon. Give it a try.

**Comment by Nek0-San** [comment]
I shall try, thank you. I will let you know. You have the most complete
tool for Kali.

Il ven 14 giu 2024, 21:21 Óscar Alfonso Díaz ***@***.***> ha
scritto:

**Comment by OscarAkaElvis** [comment]
Is not only for Kali. Is for any Linux distribution which can install the needed dependencies. Give it a try, but please put your comments or results on our discord server, not here. Invitation link is in contact section at wiki.
