### ISSUE TITLE
bug on WPS 

### ISSUE THREAD

**Issue by SiNaPsEr0x** [v1s1t0r1sh3r3/airgeddon#596]
#### What is your airgeddon version?

11.22

#### What is your Linux O.S. and which version?

kali last

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

no

#### Which is the chipset of your wireless card?

ar9271

#### Describe the issue and the steps to reproduce it

only problem on wps test .. this appare but in other tools or test all are ok

./airgeddon.sh: riga 9822: /sys/class/net/wlan1/address:

**Comment by OscarAkaElvis** [comment]
Hi, could you be more specific? what means "wps test"? please, tell us what attack were you trying, and the exact steps to be able to to reproduce it. I was testing today and I launched some wps attacks flawlessly using even the same chipset as you (that chipset should work fine).

Anyway, I encourage you to do two things in addition to providing more data:
-1 Try airgeddon dev version v11.30 from dev branch. `git clone -b dev https://github.com/v1s1t0r1sh3r3/airgeddon`
-2 Join to our Discord server for further discussion. Invitation link is in contact section at wiki.

**Comment by SiNaPsEr0x** [comment]
I arrived on discord

**Comment by SiNaPsEr0x** [comment]
resolved... I have a auto spoof my mac... and wps attack dont revel changed mac... resolve to disable this plugin
