### ISSUE TITLE
Password protected rogue/Eviltwin AP.

### ISSUE THREAD

**Issue by padranina** [v1s1t0r1sh3r3/airgeddon#605]
When attacking evil we won't make a captive portal instead we make a password protected AP, when original ap disconnected victim will try to connect our ap and have to insert password (like connecting unknown /new network ) and we will get that password. It would be less suspicious I guess. (idk it's possible or not just sharing )

**Comment by OscarAkaElvis** [comment]
This is not a forum. I told you on the other issue that if you have further questions, please do them in our Discord server.

It's evident that you don't know about what you are saying and need to familiarize more with wireless hacking.
1. If you don't know the password of the target network, you can't make victims to connect automatically
2. Even if they do click manually into your fake protected network and they insert the right key, you can't see that key in plaintext. You get what it is called a half-handshake which can be cracked offline in a similar way as a standard handshake, so to do this it's pointless. You always can do a standard handshake or pmkid capture and then try to crack it.

Please, don't open Github issues to share "happy ideas". I think you were warned about this some days ago by another admin. If you want to keep discussing I repeat, connect to our Discord server. Closing.
