### ISSUE TITLE
supported band 5Ghz not detected / does not appear

### ISSUE THREAD

**Issue by AlfredoCubitos** [v1s1t0r1sh3r3/airgeddon#606]
#### What is your airgeddon version?

11.22

#### What is your Linux O.S. and which version?

Kali-Linux 2024.2

#### Is your O.S. running in native mode or is a virtualized system? in that case, VMware? VirtualBox? Other?

No

#### Which is the chipset of your wireless card?

RTL8812AU

#### Describe the issue and the steps to reproduce it
The 5Ghz Band is not shown in the main menu. Only 2.4Ghz is detected.
But when I run 
  `iw phy1 channels | grep -Ei "5180(\.0)? MHz"`
The output is:
      `* 5180 MHz [36]`

So 5Ghz is available but not shown in the main menu 

When I use `Explore for targets`, in the result list appear also 5Ghz APs. But when I try to attack them an error appears saying that the device does not support 5Ghz :-(

**Comment by OscarAkaElvis** [comment]
That was fixed in v11.30.

Update airgeddon. I see you are using Kali, so just a `apt update && apt install airgeddon` command should be enough.

**Comment by AlfredoCubitos** [comment]
¡Gracias! :+1:
