### ISSUE TITLE
Exploring for WPS targers (not work)

### ISSUE THREAD

**Issue by M0rn1ng574r** [v1s1t0r1sh3r3/airgeddon#610]
Hello, I have a problem on Airgeddon when I launch the discovery of WPS networks, the scan displays nothing, I tried on my 2nd computer same thing. Is it related to a missing dependency, or it's hardware related, I use kali latest update on virtualBox latest update too, linux compatible hardware d-link usb dongle DWL-G122. 
Could you please help me 
![17239789347292881634109010087811](https://github.com/user-attachments/assets/50ae2d8a-0fbb-4b62-9be4-d26bdae79f02)

**Comment by cjb900** [comment]
Your issue could be related to this https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#when-i-scan-for-wireless-networks-no-networks-are-found. It's also possible there are just no AP's around you that have WPS enabled as well.
