### ISSUE TITLE
Add support for aic8800 

### ISSUE THREAD

**Issue by kilarhasina6** [v1s1t0r1sh3r3/airgeddon#611]
Aic8800 used in wifi 6 cheap adapters, which doesn't works with airgeddon. Please add this chipset.

**Comment by cjb900** [comment]
We don't add support for specific wifi adapters/chipsets. If it does not work that would indicate that it does not properly support the modes needed to work well for wifi hacking. So if you can not get that adapter/chipset to work then you would need to get a new one from our list here https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Cards%20and%20Chipsets

**Comment by OscarAkaElvis** [comment]
Sorry, but adding support to chipsets is not something we do. The chipsets are just valid for WiFi hacking or not. They are just valid to use the third party tools used by airgeddon or not, but we are not able to add support or not for the chipsets.
