### ISSUE TITLE
No screen after 'explore for targets'

### ISSUE THREAD

**Issue by youthanazia** [v1s1t0r1sh3r3/airgeddon#617]
#### What is your airgeddon version?

11.30

#### What is your Linux O.S. and which version?

Kali Linux 2024.3

#### Which is the chipset of your wireless card?

Realtek RTL8812au/8812au

#### Describe the issue and the steps to reproduce it

 I have a really annoying issue, where when trying to explore for targets, nothing happens. It looks like it's almost crashed. HOWEVER, upon Ctrl+C the finished scan results then display, as a finished scan naturally. But no 'live viewing' like it should be. Same with any other attack/monitor, it just stops. No 'popup screens etc. When, before I had to reinstall Kali and VMBOX it worked perfectly, barring VIF of course.  

Ok, before you say anything, I see this card is now on the blacklist. But it worked flawlessly untill I had to do a system reset and reinstall of VMBOX and Kali. Previous working installs were with the same version of VMBOX, but I cant remember what Kali version I had that was working. I've tried older builds of Kali with the same result/problem I'll explain below..

I have a Win7 host machine, running VMBOX 5.2.44. Kali 2024. 3. 
Kali installed vial Net installer, as well as trying other iso
The card can go into monitor mode in, or outside Airgeddon. And works perfectly with Wifite, Wash and Airodump, which leads me to point to something between the card and Airgeddon. Which I would have accepted as a issue, had it not worked perfectly before I had to reinstall. 

All distros are installed according to Airgeddon startup, and I've ran apt update/upgrade. 

Also, the driver for the card is 5.6.4.2. git 20240726.
RTL88xxau-dkms. 

I'm pretty Linux illiterate, and try what I can to get stuff working, but this is now busting my nuts beyond belief. Is there anything you can suggest  to help? I'm only asking you guys and gals, because everything works, like it did, as it should with my card, just not with Airgeddon anymore. 

Anyway, thank you for your time, hopefully you can be of help,

Cheers,

youthanazia

**Comment by OscarAkaElvis** [comment]
It is not an airgeddon issue. Duplicated of:
https://github.com/v1s1t0r1sh3r3/airgeddon/issues/612

There you can find all you need. Cause, workarounds, etc. Closing.

**Comment by youthanazia** [comment]
Thank you 👍
