### ISSUE TITLE
Evil twin

### ISSUE THREAD

**Issue by Hadinish** [v1s1t0r1sh3r3/airgeddon#626]
#### Is your question related to any concrete technology?

When I select the wifi to attacke and press start it does not start why

**Comment by Hadinish** [comment]
Plesss seee and write answer plesss

**Comment by OscarAkaElvis** [comment]
wow, how detailed your issue is... with that data we can help you, for sure! we can activate our mind powers to guess your setup, your airgeddon version, your operating system, the card and chipset you are using... etc.

Closing due to issue creation policy violation. Please, read before write.
