### ISSUE TITLE
xterm window does not appear as it should

### ISSUE THREAD

**Issue by Aggelos11** [v1s1t0r1sh3r3/airgeddon#628]
Something is really wrong with the windows because even though it appears it shows nothing .
![IMG_1406](https://github.com/user-attachments/assets/d81b816a-2630-42a8-a4f8-bd8adeda867c)

**Comment by cjb900** [comment]
this is a known issue but not with airgeddon. Its an issue with Bash https://github.com/v1s1t0r1sh3r3/airgeddon/issues/612

**Comment by Aggelos11** [comment]
And how can it be solved ? Last time I used it (some months ago) it wasn’t
the case and it would work just fine

Στις Σάβ 9 Νοε 2024 στις 9:16 πμ ο χρήστης cjb900 ***@***.***>
έγραψε:

**Comment by cjb900** [comment]
If you have to ask this, you did not even read the link I shared.
