### ISSUE TITLE
Deauthentication does not work 

### ISSUE THREAD

**Issue by Aggelos11** [v1s1t0r1sh3r3/airgeddon#629]
I use airgeddon from Kali repo . Even though I get no error the client is not deauthentication from the network . However when I try it manually using Aireplay the client is indeed disconnected . I tried with 2 different network cards and  same problem .

**Comment by cjb900** [comment]
https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/FAQ%20&%20Troubleshooting#dos-deauth-is-not-working-what-can-i-do

**Comment by OscarAkaElvis** [comment]
Stop opening issues that are not really issues. Read the wiki before opening them please. Or consider to join discord server (Indo on contact section at wiki).
