### ISSUE TITLE
[New feature request] Add ESSID/BSSID listing

### ISSUE THREAD

**Issue by wikijm** [v1s1t0r1sh3r3/airgeddon#63]
#### What is your airgeddon version?

6.1

#### What is your Linux O.S. and which version?

Linux kali 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux

#### Which is the chipset of your wireless card?

Realtek Semiconductor Corp. RTL8187 Wireless Adapter

#### Describe the issue and the steps to reproduce it

In case of 'Evil Twin AP attack with sniffing and bettercap-sslstrip2/BeEF', we need to get manually BSSID, channel and ESSID.

Is it possible to get a result of 'airodump-ng' or something similar?
Plus, it will help to avoid typing error on this step.

If you find this feature request unhelpfull or irrelevant, feel free to close this issue.

Sincerely,
@WikiJM

**Comment by OscarAkaElvis** [comment]
Yeah, is already implemented. Just perform a scan before launching the attack and you will have selected the network with all parameters, so is not needed to type the data manually.

**Comment by wikijm** [comment]
Shame on me, I finally find where to go thanks to your help.
For users who looking at the same thing, go to "5.  Handshake tools menu", "2.  Put interface in monitor mode" then "4.  Explore for targets (monitor mode needed)".
