### ISSUE TITLE
 'explore for target' option do nothing(no window shows, so can't proceed) after selecting an attack approach

### ISSUE THREAD

**Issue by ToLiveBetter** [v1s1t0r1sh3r3/airgeddon#630]
#### Is your question related to any concrete technology?

airgeddon version: 11.11,  kali linux: 2024.3 ,wireless chipset : intel ax200 (support monitormode  and packet inject) 2.4g&&5g
other possible useful info: device is laptop of lenovo thinkbook. cpu is amd ryzen 7 6800h.
#### Describe your question as detailed as possible

i am using airgeddon with wps attack or evil twins attack.
After selecting either of them, when i enabled monitor mode on wireless card, then selected 'explore for target', 
it did nothing and no new window opened for scaning wifi. But when i use airmon-ng or airodump-ng start wlan0, all is normal.

Hope your reply.Thanks!

**Comment by OscarAkaElvis** [comment]
Duplicated of https://github.com/v1s1t0r1sh3r3/airgeddon/issues/612

Read there on that link the solution. It is not an airgeddon bug, but a bash bug.

A last advice: update your airgeddn version, in Kali can be done using apt.

Closing.
