### ISSUE TITLE
Manual enlargement of Xterm on fluxion instead of automatic enlargement with six windows

### ISSUE THREAD

**Issue by KreativeNerd** [v1s1t0r1sh3r3/airgeddon#632]
I am using VMware workstation 17.6.1. This problem appeared with me after updating and upgrading Kali Linux to 2024.3. It became small and I had to enlarge it manually. When I search for networks or attack the evil twin, the windows that appear automatically are very small. They used to appear normally before the update. Also this seems to affect both Airgeddon and Fluxion that uses Xterm terminal. Please what is the solution to the problem? 

![image](https://github.com/user-attachments/assets/9738d1df-7833-44cb-b7c8-ecce5b2bf869)

**Comment by cjb900** [comment]
This is not an issue with airgeddon but a bug in bash as you can see in the thread on it here https://github.com/v1s1t0r1sh3r3/airgeddon/issues/612. Also please do not reference any other tools here. We only care about airgeddon and its dependencies.

**Comment by OscarAkaElvis** [comment]
If you have a problem with other tool, why don't you open an issue on the other tool's GitHub? This is unbelievable.
