### ISSUE TITLE
Manual enlargement of Xterm on Airgeddon instead of automatic enlargement

### ISSUE THREAD

**Issue by KreativeNerd** [v1s1t0r1sh3r3/airgeddon#633]
I am using VMware workstation 17.6.1. This problem appeared with me after updating and upgrading Kali Linux to 2024.3. It became small and I had to enlarge it manually. When I search for networks or attack the evil twin, the windows that appear automatically are very small. They used to appear normally before the update and upgrade. I have tried everything on my own including using chatgpt to get this resolve yet no success. Also this seems to be a problem with Xterm terminal. Please what is the solution to this problem?
I use this image below to drive home my point.

![image](https://github.com/user-attachments/assets/61bf54fc-3b0e-42bd-b12b-ada3b3c18ce1)

**Comment by cjb900** [comment]
Opening up a second issue after you were already told this is a known issue with accompanying github link is not going to get anyone to want to help you any better.
