### ISSUE TITLE
small terminal problem

### ISSUE THREAD

**Issue by hazartaspinar** [v1s1t0r1sh3r3/airgeddon#634]
Hello everyone, the problem I'm having is this: When I open airgeddon on my virtual Kali Linux machine, the terminals open in the handshake capture section or the evil twin section, tiny on the right and left. I changed the entire computer, installed from scratch and the problem continues the same. When I try it on parrotOS, it works without any problems.

**Comment by OscarAkaElvis** [comment]
Duplicated. Not an airgeddon problem. Is a bug in bash package. All the workaround and solutions here:

https://github.com/v1s1t0r1sh3r3/airgeddon/issues/612
