### ISSUE TITLE
Capture handshake. Syntax error in expression 

### ISSUE THREAD

**Issue by Vanchesss** [v1s1t0r1sh3r3/airgeddon#69]
#### What is your airgeddon version?

airgeddon script v6.11 
bash version (4.4.11(1)-release)

#### What is your Linux O.S. and which version?

[    0.000000] Linux version 4.6.0-kali1-amd64 (devel@kali.org) (gcc version 5.4.0 20160609 (Debian 5.4.0-6) ) #1 SMP Debian 4.6.4-1kali1 (2016-07-21)

#### Which is the chipset of your wireless card?

Alpha awus 036h. Realtek RTL8187

#### Describe the issue and the steps to reproduce it

The script exits when the item is selected
Capture handshake.
When you press Ctrl + C, for end the scan an error occurs.

#### PROGRAM LOG
***************************** Handshake tools menu ***************************** 
Interface wlan0mon selected. Mode: Monitor 

Select an option from menu : 

1.  Select another network interface 
2.  Put interface in monitor mode 
3.  Put interface in managed mode 
4.  Explore for targets (monitor mode needed) 
------------ (monitor mode needed for capturing) ------------- 
5.  Capture Handshake 

6.  Clean/optimize Handshake file 

7.  Return to main menu 

*Hint* Obtaining a Handshake is only for networks with encryption WPA or WPA2 

5

There is no valid target network selected. You'll be redirected to select one 
Press [Enter] key to continue...

**************************** Exploring for targets ***************************** 
Exploring for targets option chosen (monitor mode needed) 

Selected interface wlan0mon is in monitor mode. Exploration can be performed 

When started, press [Ctrl+C] to stop... 
Press [Enter] key to continue...
**airgeddon.sh: line 6117: 5
20: syntax error in expression (error token is "20")** 
root@kali:~/airgeddon#

**Comment by v1s1t0r1sh3r3** [comment]
I'm trying to reproduce this but is not possible. Is working for me... when you press Ctrl+C to stop the capture, are you getting networks of capture window? I mean, everything is normal until you press Ctrl+C and the error happens at the moment of pressing that keys?

I checked line 6117 on that version. The code is:

    6116>- targetline=$(awk '/(Station|Client[es])/{print NR}' < "${tmpdir}nws-01.csv")
    6117>- targetline=$((targetline - 1))

I did some debug and everything seems fine. This searches in the file for the strings "Station" or "Cliente" or "Clients". I don't know... maybe there is a detected network on your network list which contain some of this string... Maybe I can improve the regex of line 6116 to `targetline=$(awk '/(^Station[s]?|^Client[es]?)/{print NR}' < "${tmpdir}nws-01.csv")` . In this way the problem of a detected network with any of that strings in the name of its ESSID is avoided.

Can you provide a screenshot of your detected networks window before the "crash"? I want to see if there is some kind of strange text on the ESSIDs detected.

**Comment by Vanchesss** [comment]
_the error happens at the moment of pressing that keys?_
Yes that's right.
I think you're right. I marked the network with the red in the screenshot. It has a string - "Station".
![screenshot](https://cloud.githubusercontent.com/assets/25343708/24185330/9feec97c-0ee3-11e7-9468-62b00edf0a34.jpg)

Thank you. 
`targetline=$(awk '/(^Station[s]?|^Client[es]?)/{print NR}' < "${tmpdir}nws-01.csv")`
I'll try your solution tonight.

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, One of the name of the detected networks is matching the regex and probably breaking the process. Test it with the 6117 line I put in my last post and tell to us the result. If it works I can do the patch easily for v6.12.

Thank you.

Other possible reason for the crash is the CR

Beware of carriage returns! Be pretty sure of using only LF and not CRLF. If you are going to edit the script for the test, beware of this.

**Comment by Vanchesss** [comment]
I tested
`targetline=$(awk '/(^Station[s]?|^Client[es]?)/{print NR}' < "${tmpdir}nws-01.csv")`
it worked perfectly. An error has disappeared.

**Comment by v1s1t0r1sh3r3** [comment]
Ok, I'll do the fix for v6.12 . Thank you.

**Comment by v1s1t0r1sh3r3** [comment]
Patch done. The issue will be closed automatically once merged to master.
