### ISSUE TITLE
evil twin attack / Captive portal page customisation

### ISSUE THREAD

**Issue by wice22** [v1s1t0r1sh3r3/airgeddon#74]
- Please, answer the questions to provide maximum of info.
 - Answer ALWAYS in english.
 - If more info is needed and requested by airgeddon staff but there is no answer in 10 days, the issue will be closed.

#### What is your airgeddon version?

*6.12*

#### What is your Linux O.S. and which version?

*Kali latest*

#### Which is the chipset of your wireless card?

*AtherosUB91C*

#### Describe the issue and the steps to reproduce it

*ITs more a question than an issue, Where can I change Evil twean's details , such as design of the login page and  url of that page ?*

**Comment by v1s1t0r1sh3r3** [comment]
That's not a feature for the users. Anyway, this is open source, you can modify your code. You have a function "set_captive_portal_page" on which is setting the html, the js file, etc.

Beware of setting auto_update=0 in order to don't loose your changes after modifying it

Closing.

**Comment by freemakerz** [comment]
@v1s1t0r1sh3r3 - Im looking for the directory of portal.js, portal.css, index.html indicate on the airgeddon.sh. Im looking forward to customize the captive portal. Hope you'll answer my concerns. Thank you!

**Comment by mamatb** [comment]
It's easy @freemakerz. Searching for portal.js and portal.css in airgeddon.sh shows
`cssfile="portal.css"
jsfile="portal.js"`
then searching for jsfile and cssfile shows
`} >> "${tmpdir}${webdir}${jsfile}"
} >> "${tmpdir}${webdir}${cssfile}"`
and searching for tmpdir  and webdir shows
`tmpdir="/tmp/"
webdir="www/"`

Next time search a bit before posting please. I leave looking for the index to you.

**Comment by v1s1t0r1sh3r3** [comment]
Yeah, this was already asked here: https://github.com/v1s1t0r1sh3r3/airgeddon/issues/132

**Comment by mehdimers** [comment]
how i can change the index 'evil twin' by steps pleez

**Comment by OscarAkaElvis** [comment]
We are not a helpdesk support team. Just developers. If you want to customize the captive portal you must do it on your own. Here you have enough info about where is in the code or where are the deployed files. You should change them using html, javascript and bash cgi. You should learn this to do it. We can't teach you here. Locking.
