### ISSUE TITLE
issue with captured handshake

### ISSUE THREAD

**Issue by wice22** [v1s1t0r1sh3r3/airgeddon#75]
- Please, answer the questions to provide maximum of info.
 - Answer ALWAYS in english.
 - If more info is needed and requested by airgeddon staff but there is no answer in 10 days, the issue will be closed.

#### What is your airgeddon version?

*I6.12*

#### What is your Linux O.S. and which version?

*Kali Latest*

#### Which is the chipset of your wireless card?
*black Alfa*

#### Describe the issue and the steps to reproduce it

*Basically in 499 from 500 attempts I'm getting the following error: 
```
No networks found with Handshake captured on the selected file 
Press [Enter] key to continue...
```
after I'm capturing handshake offered by Evil twin option 9 from the menu, and saving it in default root directory, , is there anything particular I shall know in this ? or any way around ?, 

 When opening this handshake files, with wireshark, it gives an error saying that : "The capture File appears to have been cut short in the middle of a packet"*

**Comment by v1s1t0r1sh3r3** [comment]
Ok you put your wireless card brand, not your chipset. I can guess is a AWUS036NHA and probably your chipset is Atheros AR9271. Is shown on airgeddon's network interface selection screen.

I think you are doing something bad or have some kind of problem with your driver or something like that. You must be pretty sure about capturing the handshake. while capturing it, look at the top right side of the capture window. If you captured it, you must see there somethig like this (look at the yellow mark):

![handshake](https://s14.postimg.org/6h7ndrwwx/WPA_handshake.jpg)

You will get handshake only if a client connects to the network while you are capturing and not always happens.

You can check if a captured file already have a handshake doing this simple command: `aircrack-ng yourfile.cap`. With that, you will see if your network has this `WPA (1 handshake)`.

I propose you an exercise for testing... Handshake capturing is the same mechanism before Evil Twin capture portal than the Handshake tools menu... so check it with your own network. Keep capturing while you connect to your network with another device (a phone or whatever). You'll see the handshake appear. Then check it with the command I told you.

I think you are trying to capture a Handshake from a network without clients and that is not possible.

In any case, that is not airgeddon's fault. airgeddon does it using aircrack. Any problem could be a misuse, a driver problem or in last instance an aircrack's problem. Closing this.

**Comment by wice22** [comment]
Hi yes AWUS036NHA   with Atheros AR9271 chipset, 
and there is No driver needed, it's linux default, driver
To make sure updates I made on the kali are not causing this
I did install a fresh version of Kali to test this issue, the problem there remains the same....
I'll try your sugestion today ...  Thanks

Also Did you though about the cases when Wifi requests Login and Password, not a Key only ?
in all new modern systems , there is login password access or Email password, I'm talking about Evil Twin.

**Comment by v1s1t0r1sh3r3** [comment]
If you are requested for user and password that should be a Radius server auth or similar... not a standard WPA/WPA2 PSK auth and is out of the scope o airgeddon.
