### ISSUE TITLE
Evil Twin , Option 9

### ISSUE THREAD

**Issue by wice222** [v1s1t0r1sh3r3/airgeddon#80]
- Please, answer the questions to provide maximum of info.
 - Answer ALWAYS in english.
 - If more info is needed and requested by airgeddon staff but there is no answer in 10 days, the issue will be closed.

#### What is your airgeddon version?

*6.12*

#### What is your Linux O.S. and which version?

*Kali 2 - latest*

#### Which is the chipset of your wireless card?

*Ralink RT3070*

#### Describe the issue and the steps to reproduce it

*Hi, Its more question than issue, 
In Evil Twin attack 9, I've notice that the MAC Address is not fully replicated, there is 1 digit difference, and the original Network  stays online,  Is this done cause of some legal or ethical reasons or there is a technical reason to not fully replicate the target's IP  ?*

**Comment by v1s1t0r1sh3r3** [comment]
This is because if you clone all the mac entirely, then your fake AP is affected by your own DoS attack. So, the smartest option is to change a digit in the middle of the bssid because the three first groups are vendor, and the last ones are what you usually check.
