### ISSUE TITLE
AP creation

### ISSUE THREAD

**Issue by wice22** [v1s1t0r1sh3r3/airgeddon#81]
- Please, answer the questions to provide maximum of info.
 - Answer ALWAYS in english.
 - If more info is needed and requested by airgeddon staff but there is no answer in 10 days, the issue will be closed.

#### What is your airgeddon version?

*7*

#### What is your Linux O.S. and which version?

*Kali 2*

#### Which is the chipset of your wireless card?

*AR9271*

#### Describe the issue and the steps to reproduce it

*Hi, Could u guide me please, how can I simply create an Access point, Without Ddosing, and With the Exact same MAC address as a target ? *  

Regards

**Comment by v1s1t0r1sh3r3** [comment]
This question is out of scope I think. This is not a forum to ask questions. airgeddon's staff is working to improve the tool and fix possible bugs, but we don't have time to answer this kind of questions, sorry. What you need is a wireless/linux forum.

You can close manually DoS window if you want. If you want to know how airgeddon is doing its job, you can search through the code to see iptables rules, hostapd command and dhcpd config. Anyway, there are a lot of pages guiding you about how to use hostapd, dhcpd and iptables.

To change your mac you can use a lot of tools like macchanger or you can do it in the same way as airgeddon is doing it. Everything is in the code. Closing.

**Comment by wice22** [comment]
Thanks for your answer, 
I did try to change MAC manually (to match the targets MAC) before and after  Airgeddon runs, but no luck, 
I asked to know how to change this rule without breaking some functionality,  I'll search in script then

Regards

**Comment by v1s1t0r1sh3r3** [comment]
Look at set_hostapd_config function. There you have the code you are looking for to change the mac.

This is not useful for you, you can remove it:
    different_mac_digit=$(tr -dc A-F0-9 < /dev/urandom | fold -w2 | head -n100 | grep -v "${bssid:10:1}" | head -c 1)

Change this:
`et_bssid=${bssid::10}${different_mac_digit}${bssid:11:6}`
To this:
`et_bssid=${bssid}`

Change at the beginning of airgeddon `auto_update=1` to `auto_update=0` to avoid possible updates on which you'll loose your changes.

**Comment by wice22** [comment]
Thanks,

 I'll try it, 

cheers
