### ISSUE TITLE
/opt/airgeddon/airgeddon.sh: line 6128: /tmp/nws-01.csv: No such file or directory

### ISSUE THREAD

**Issue by 0000x0** [v1s1t0r1sh3r3/airgeddon#85]
localhost@localhost-x ~ $ docker run --rm -ti --name airgeddon --net=host --privileged -p 3000:3000 -v /home/localhost/AirgeDDon:/io v1s1t0r1sh3r3/airgeddon

*********************************** Welcome ************************************ 
Welcome to airgeddon script v6.21 

                  .__                         .___  .___
           _____  |__|______  ____   ____   __| _/__| _/____   ____
           \__  \ |  \_  __ \/ ___\_/ __ \ / __ |/ __ |/  _ \ /    \
            / __ \|  ||  | \/ /_/  >  ___// /_/ / /_/ (  <_> )   |  \
           (____  /__||__|  \___  / \___  >____ \____ |\____/|___|  /
                \/         /_____/      \/     \/    \/           \/

                             Developed by v1s1t0r 

                        *         .  _.---._          .      
                              *    .'       '.  .            
                               _.-~===========~-._ *         
                           .  (___________________)       *  
                            *       \_______/        .       
                                                             
^C
*********************************** Exiting ************************************ 
Exiting airgeddon script v6.21 - See you soon! :) 

Checking if cleaning/restoring tasks are needed... 
No tasks to perform on exit 

localhost@localhost-x ~ $ docker run --rm -ti --name airgeddon --net=host --privileged -p 3000:3000 -v /home/localhost/AirgeDDon:/io v1s1t0r1sh3r3/airgeddon /bin/bash
root@localhost-x:/opt# exit
exit
localhost@localhost-x ~ $ docker run --rm -ti --name airgeddon --net=host --privileged -p 3000:3000 -v /home/localhost/AirgeDDon:/io v1s1t0r1sh3r3/airgeddon

*********************************** Welcome ************************************ 
Welcome to airgeddon script v6.21 

                  .__                         .___  .___
           _____  |__|______  ____   ____   __| _/__| _/____   ____
           \__  \ |  \_  __ \/ ___\_/ __ \ / __ |/ __ |/  _ \ /    \
            / __ \|  ||  | \/ /_/  >  ___// /_/ / /_/ (  <_> )   |  \
           (____  /__||__|  \___  / \___  >____ \____ |\____/|___|  /
                \/         /_____/      \/     \/    \/           \/

                             Developed by v1s1t0r 

                        *         .  _.---._          .      
                              *    .'       '.  .            
                               _.-~===========~-._ *         
                           .  (___________________)       *  
                            *       \_______/        .       
                                                             

*********************************** Welcome ************************************ 
This script is only for educational purposes. Be good boyz&girlz! 
Use it only on your own networks!! 

Accepted bash version (4.4.11(1)-release). Minimum required version: 4.2 

Detecting resolution... Can't be detected!, using standard : 1024x768 

If make work xpdyinfo command, the script will be able to calculate your screen resolution and show you the windows in a better way. Depending of the system, the package name could be x11-utils, xdpyinfo, xorg-xdpyinfo, etc. 

Known compatible distros with this script : 
"Arch" "Backbox" "BlackArch" "CentOS" "Cyborg" "Debian" "Fedora" "Gentoo" "Kali" "Kali arm" "OpenMandriva" "Parrot" "Parrot arm" "Raspbian" "Red Hat" "SuSE" "Ubuntu" "Wifislax" 

Detecting system... 
Kali Linux (Docker)

Let's check if you have installed what script needs 
Press [Enter] key to continue...

Essential tools: checking... 
ifconfig .... Ok
iwconfig .... Ok
iw .... Ok
awk .... Ok
airmon-ng .... Ok
airodump-ng .... Ok
aircrack-ng .... Ok
xterm .... Ok

Optional tools: checking... 
beef-xss .... Ok
dhcpd .... Ok
wash .... Ok
etterlog .... Ok
dnsspoof .... Ok
reaver .... Ok
hostapd .... Ok
iptables .... Ok
wpaclean .... Ok
bully .... Ok
sslstrip .... Ok
aireplay-ng .... Ok
unbuffer .... Ok
lighttpd .... Ok
crunch .... Ok
ettercap .... Ok
hashcat .... Ok
mdk3 .... Ok
bettercap .... Ok
pixiewps .... Ok

Your distro has all necessary essential tools. Script can continue... 
Press [Enter] key to continue...

The automatic update has been disabled when airgeddon is running in a Docker container. If you want to update it, download again the image tagged as "latest" 
Press [Enter] key to continue...

***************************** Interface selection ****************************** 
Select an interface to work with : 
--------- 
1.  eno1 // Chipset: Intel Corporation 82577LM Gigabit
2.  wlp11s0 // Chipset: Qualcomm Atheros AR9285 Wireless Network Adapter
3.  wlp2s0b1 // Chipset: Unknown 
4.  vmnet1 // Chipset: Unknown 
5.  vmnet8 // Chipset: Unknown 
6.  docker0 // Chipset: Unknown 
7.  br-9c7d3c07ee81 // Chipset: Unknown 
8.  wlp1s0mon // Chipset: Qualcomm Atheros AR242x / AR542x Wireless Network Adapter
--------- 
*Hint* Every time you see a text with the prefix [PoT] acronym for "Pending of Translation", means the translation has been automatically generated and is still pending of review 
--------- 
8

***************************** airgeddon main menu ****************************** 
Interface wlp1s0mon selected. Mode: Monitor 

Select an option from menu : 
--------- 
1.  Select another network interface 
2.  Put interface in monitor mode 
3.  Put interface in managed mode 
--------- 
4.  DoS attacks menu 
5.  Handshake tools menu 
6.  Offline WPA/WPA2 decrypt menu 
7.  Evil Twin attacks menu 
8.  WPS attacks menu 
--------- 
9.  About & Credits 
10. Change language 
11. Exit script 
--------- 
*Hint* Select a wifi card to work in order to be able to do more actions than with an ethernet interface 
--------- 
5

***************************** Handshake tools menu ***************************** 
Interface wlp1s0mon selected. Mode: Monitor 

Select an option from menu : 
--------- 
1.  Select another network interface 
2.  Put interface in monitor mode 
3.  Put interface in managed mode 
4.  Explore for targets (monitor mode needed) 
------------ (monitor mode needed for capturing) ------------- 
5.  Capture Handshake 
--------- 
6.  Clean/optimize Handshake file 
--------- 
7.  Return to main menu 
--------- 
*Hint* Remember to select a target network with clients to capture Handshake 
--------- 
4

**************************** Exploring for targets ***************************** 
Exploring for targets option chosen (monitor mode needed) 

Selected interface wlp1s0mon is in monitor mode. Exploration can be performed 

When started, press [Ctrl+C] to stop... 
Press [Enter] key to continue...
/opt/airgeddon/airgeddon.sh: line 6128: /tmp/nws-01.csv: No such file or directory

No networks found 
Press [Enter] key to continue...

im not sure if i supose create them ? :)

**Comment by OscarAkaElvis** [comment]
Please, stop creating issues copying and pasting everything as is because the asterisks are interpreted by markdown as bold. Use screenshots instead next time.

I see in your data you are launching docker from a standard non-root account. Try to launch docker run with sudo or as root.

Anyway I think is not related to docker. What about launching it in native mode without using docker? Are you able to capture packets?

**Comment by v1s1t0r1sh3r3** [comment]
Ok the problem here is that your xterm windows can't reach your host X Window system. By default, on docker the DISPLAY used is ":0". So be pretty sure of having your X running there.

1. Be sure of having an X windows system running on your host.
2. Check where are they listening. You can check it launching `env | grep DISPLAY`

As I said, usually they are on ":0" and if that is the case it should work. If you have in ":1" for example, you must modify your `docker run` command to set the DISPLAY var pointing to the right place. So you should add `-e DISPLAY=:1` to your `docker run` command.

I updated right now [Linux Docker Wiki Section](https://github.com/v1s1t0r1sh3r3/airgeddon/wiki/Docker-Linux) with a new parameter which does this automatically. So your command should be:

    docker run --rm -ti --name airgeddon --net=host --privileged -p 3000:3000 -v /home/localhost/AirgeDDon:/io -e DISPLAY=$(env | grep DISPLAY | awk -F "=" '{print $2}') v1s1t0r1sh3r3/airgeddon

The key to see if it worked is the xdpy resolution detection. If the resolution is not detected something went wrong and probably the xterms are going to fail.

Closing.
