### ISSUE TITLE
nws-01.csv: No such file or directory

### ISSUE THREAD

**Issue by jaykumar-jnpr** [v1s1t0r1sh3r3/airgeddon#96]
Error
===============================================

**************************** Exploring for targets *****************************
Exploring for targets option chosen (monitor mode needed)

Selected interface wlan1mon is in monitor mode. Exploration can be performed

When started, press [Ctrl+C] to stop...
Press [Enter] key to continue...
./airgeddon.sh: line 7117: /tmp/nws-01.csv: No such file or directory

No networks found

===============================================

System setting

Detecting system...
Raspbian Linux

Let's check if you have installed what script needs
Press [Enter] key to continue...

Essential tools: checking...
ifconfig .... Ok
iwconfig .... Ok
iw .... Ok
awk .... Ok
airmon-ng .... Ok
airodump-ng .... Ok
aircrack-ng .... Ok
xterm .... Ok

Optional tools: checking...
iptables .... Ok
wpaclean .... Ok
packetforge-ng .... Ok
bully .... Ok
sslstrip .... Ok
aireplay-ng .... Ok
beef .... Error (Possible package name : beef-xss / beef-project)
unbuffer .... Ok
dhcpd .... Ok
lighttpd .... Ok
wash .... Ok
crunch .... Ok
etterlog .... Ok
dnsspoof .... Ok
ettercap .... Ok
hashcat .... Error (Possible package name : hashcat)
reaver .... Ok
mdk3 .... Ok
bettercap .... Error (Possible package name : bettercap)
pixiewps .... Ok
hostapd .... Ok

Update tools: checking...
curl .... Ok

**Comment by OscarAkaElvis** [comment]
It seems you are not running an Xwindow system. Not only having xterm installed is enough. You need an X window system up and running. So you can't run it from a remote ssh session. Run it on an Desktop session.

**Comment by v1s1t0r1sh3r3** [comment]
No more info is needed. Is pretty clear what is happening. On new 7.2 version a new blocking validation will be done for checking a working X window system to avoid this kind of errors.

**Comment by v1s1t0r1sh3r3** [comment]
Done. Issue will be closed automatically when merge is done from dev to master.
