### ISSUE TITLE
request:  add 3 or 6 fixed numbers to beginning of brute force 10 digit string as an option

### ISSUE THREAD

**Issue by partyexpress** [v1s1t0r1sh3r3/airgeddon#98]
#### What is your airgeddon version?

latest
#### What is your Linux O.S. and which version?

kali linux 2017
#### Which is the chipset of your wireless card?

raspberry pi
#### Describe the issue and the steps to reproduce it

thought about it, and it would be to start brute force at a certain number, which corresponds to the beginning of the number range.

**Comment by v1s1t0r1sh3r3** [comment]
version latest... which is latest? latest from master? latest from develop branch?

Start brute force at a certain number... what bruteforce are you referring to? wps pin?

**Comment by v1s1t0r1sh3r3** [comment]
Closing this because lack of info.
